### ISSUE TITLE
Typo in the Doxygen \todo documentation

### ISSUE THREAD

**Issue by StefanBattmer** [doxygen/doxygen#10050]
2 small typos in the current documentation:

![Capture](https://github.com/doxygen/doxygen/assets/33477553/fbb9cea0-b453-4d25-9793-2ae157be2fe4)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
