### ISSUE TITLE
markdown file does not shown up with content

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10068]
**Describe the bug**
markdown file `*.md` is found but i can not `\ref` to the file (readme) and documentation content is empty

**Expected behavior**
show up as a doxygen docu like `*.dot` file

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/27886664/a44d133f-b534-4296-9de2-920375f32a42)

**To Reproduce**
```
Reading /home/dev1usr/Project/NHI1/theGuard/docs/readme.md...
Parsing code for file readme.md...
Generating docs for file readme.md...
/home/dev1usr/Project/NHI1/theGuard/docs/main/main.doc:44: warning: unable to resolve reference to 'readme' for \ref command
Generating docs for page md_docs_readme..
```

**Version**
Doxyfile 1.9.6 und linux

**Additional context**

**Comment by aotto1968** [comment]
solution: the HTML comment have to be `-->`

**Comment by albert-github** [comment]
So I understand that you solved the problem as you made a small mistake using `--->` instead of `-->`.

An image can only be used to give some visual feedback (about the output) and from an image it is not possible to get the exact used code, so always attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by aotto1968** [comment]
you can close this. → my fault.
