### ISSUE TITLE
Newline missing in parser output

### ISSUE THREAD

**Issue by healermagnus** [doxygen/doxygen#10078]
doxygen.cpp line 11725 should have a newline at the end.

"Specified markdown mainpage '%s' has not been defined as input file"

I'm seeing the error message prepended to the next output message.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10080

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
