### ISSUE TITLE
object multiple referenced by many files sharing the same basename (Origin: bugzilla #135310)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1008]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-24 18:36:02 +0000, b.lecomte@free.fr wrote:

    if my foo function describe in /myspace/tools/toto.c
    is called from the main section of /myspace/type1/file.c
    and from the main section of /myspace/type2/file.c,
    
    the generated doc for foo will only show the first occures of file.c has
    referenced link.

On 2007-10-15 19:40:34 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
The problem here is the fact that there are 2 main sections with the same name an this cannot be generated in e.g. 1 executable.
For this there are solutions by defining separate main section names and during the compilation phase one can define those names (like main_pgm1 and main_pgm2) as e.g. `-Dmain_pgm1=main` and for the second program use `-Dmain_pgm2=main`

I think the problem is usage
