### ISSUE TITLE
Having a backslash as last character in quoted content breaks all subsequent output.

### ISSUE THREAD

**Issue by macawkitty** [doxygen/doxygen#10178]
**Describe the bug**
Having a backslash as last character in quoted content breaks all subsequent output.

**To Reproduce**
````
-# Do laborum dolore: 
   - In a magna sit in "E:\Aliqua\Dolore\" pariatur laborum ea sed. Est laborum officia in laborum consequat consequat.
-# Id laborum id exercitation ipsum "E:\Aliqua\officia\eu\aliqua.eu".
   - Nulla laborum excepteur tempor "E:\Aliqua\officia\dolor\aliqua_x_y_z\aliqua.dolor -u E:\Aliqua\officia\eu\aliqua.eu"
   - Fugiat cillum ea magna dolore. Elit esse voluptate sed laborum sunt et/lorem/irure in laborum magna id.
````
produces this in the webpage:

1. Do laborum dolore: 
   - In a magna sit in "E:\Aliqua\Dolore\\" pariatur laborum ea sed. Est laborum officia in laborum consequat consequat. -# Id laborum id exercitation ipsum "E:\Aliqua\officia\eu\aliqua.eu".   - Nulla laborum excepteur tempor "E:\Aliqua\officia\dolor\aliqua_x_y_z\aliqua.dolor -u E:\Aliqua\officia\eu\aliqua.eu"  - Fugiat cillum ea magna dolore. Elit esse voluptate sed laborum sunt et/lorem/irure in laborum magna id.

The html looks like this:
````
<ol type="1">
<li>Do laborum dolore:</li>
</ol>
<ul>
<li>In a magna sit in "E:\Aliqua\Dolore\" pariatur laborum ea sed. Est laborum officia in laborum consequat consequat.
-# Id laborum id exercitation ipsum "E:\Aliqua\officia\eu\aliqua.eu".
- Nulla laborum excepteur tempor "E:\Aliqua\officia\dolor\aliqua_x_y_z\aliqua.dolor -u E:\Aliqua\officia\eu\aliqua.eu"
- Fugiat cillum ea magna dolore. Elit esse voluptate sed laborum sunt et/lorem/irure in laborum magna id.
````

**Version**
Getting this issue on Windows 10 (64 bit) - doxygen 1.9.7
NOT getting this on doxygen 1.9.1

**Comment by albert-github** [comment]
Also in a quoted string  doxygen commands are possible and thus the backslash. In case the backslash is the last character in the quoted content this will indeed break the output.
Especially with Windows paths this can lead to problems but there is a solution for this:
- replace the backslashes by double backslashes and the double quotes by a backslash followed by a double quote
- or (in my opinion better) replace the double quotes with backticks, in that case the part between the backticks is seen as code and also shown in a code way manner.

Both solutions will also et ride of other errors regarding `warning: Found unknown command`
Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/11990280/example.tar.gz)

Note always (text is nice, but needs copy / paste etc. with all kinds of possible problems):
- attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.


I think the problem is usage

**Comment by macawkitty** [comment]
Sounds neat. We can use backticks, the only caveat is we do want the double quotes to show sometimes - but then this [bug](https://github.com/doxygen/doxygen/issues/8788) becomes a blocker to that.
