### ISSUE TITLE
@relates and @ingroup together produce incorrect results. (Origin: bugzilla #137111)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1035]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-13 22:23:30 +0000, sizraile@prdus.jnj.com wrote:

    The code below produces the correct results in the "Related Functions" 
    section of description of class A, but the summary section of group 
    (module) Functions shows void foo() as void A::foo(). Also, the 
    "Function Documentation" section of the module lists the correct 
    function signature, but lists void foo() as "[related, inherited]".
    While 'related' is correct, the function is not inherited.
    
                                                 -- Sergei Izrailev
    
    
    /// Class A.
    class A {};
    
    /** \defgroup group1 Functions
     * @{
     */
    
    /*! \relates A
    */
    /// Function related to class A.
    void foo() {}
    
    /** @} end group */

**Comment by albert-github** [comment]
Due to a missing settings file it is hard to reproduce the problem. When using a default settings file I can reproduce the `void A::foo()` problem with the doxygen 1.3.6 version but I don't see the `[inherited]` part.

With the current doxygen version 1.12.0 the function is shown as `void foo()`

All in al I think the problem has been solved in the mean time.
