### ISSUE TITLE
Math equation coming from Markdown

### ISSUE THREAD

**Issue by EdoFranzi** [doxygen/doxygen#10382]
If in my markdown I place an equation like this one:

$$ PCPU[\%] = \frac{(Ptavg.nexec)}{CPUt}.100 $$

Markdown display correctly the equation. But when Doxygen parses the project, it display only a part of the equation

PCPU[

If I remove the \% the equation is correctly displayed but without \%.
BR, Edo

**Comment by Laur59** [comment]
Hello
as requested I have created a small project in the attached archive.
[doxygen_example.zip](https://github.com/doxygen/doxygen/files/13113631/doxygen_example.zip)

To build the documentation we run:
`./build.sh`

in this archive are two screen captures:
- dillinger.png showing the rendering of the markdown
- doxygen.png showing the result page produced by doxygen

Version of doxygen : 1.9.8 (c2fe5c3e4986974eb2a97608b24086683502f07f)

**Comment by albert-github** [comment]
I was a bit amazed that first formula was shown.
When looking at the provided project I see a few things:
- `USE_MATHJAX=YES`
- we get warnings about the `\frac` and `\sum_` command but not about `\%`, but this is logical as `\%` is a doxygen command to output a `%`.
- As the "formulas" contains no further special doxygen commands it is outputted as it is and result in the HTML code (for the first 2 "formulas"):
```
<p>$$CPUt = \sum_{i=0}^P{(Ptavg_i + Ktavg_i).nexec}$$</p>
<p>$$PCPU[%] = \frac{(Ptavg.nexec)}{CPUt}.100$$</p>
```

We see here the sequence `$$` and this starts the MathJax processing till the end `$$`, so the first line can be processed properly, but why isn't the second one not processed properly? This is because the original `\%` is handled as a doxygen command and results in a `%` and as the `%` is the comment sign in `TeX` / `LaTeX` it means that the rest of the formula line (so till the closing `$$`) is not taken into account.

So in general it is "luck" that a formula is shown.

How to solve the problem?
- use an `INPUT_FILTER` to change the `$$ ... $$` in `\f[ ... \f]` or ` \f$ ... \f$`
