### ISSUE TITLE
Use doxygen to generate xml for header files. When there are functions with the same definition in different header files, only one of the functions has complete description information in xml.

### ISSUE THREAD

**Issue by LogicWuta** [doxygen/doxygen#10469]
there is same function in a.h and b.h。
function code:
```c
/**
* @fn case01(int a);
* @brief case01
* @param a a
* @return int
*/
int case01(int a);
```
use doxygen to generate xml for a.h and b.h.

xml for a.h
![a](https://github.com/doxygen/doxygen/assets/50962586/3a16c814-d16f-43ac-9613-c392bf89d83a)

xml for b.h
![b](https://github.com/doxygen/doxygen/assets/50962586/2610eddb-2734-4dbf-ad36-238509e6ef9b)

b had nothing in briefdescription and detaileddescription.

**Comment by albert-github** [comment]
I ran the problem with the current, 1.9.8, doxygen version and created 3 files:
- a.h with a case01
- b.h with a case02
- c.h as copy of b.h

and the default settings plus `GENERATE_XML=YES`.
We already got the warning:
```
.../c.h:9: warning: Member case02(int a) (function) of file c.h is not documented.
```
and this is because the function is declared twice and thus doxygen gets a bit confused as it sees twice an identical function (and merges the documentation leaving no documentation for the function in c.h). This is also reflected in the xml files.

I think the problem is usage.

**Comment by LogicWuta** [comment]
@albert-github 
sorry that i uploaded wrong screenshot.
but you do get what i mean and ran the problem.
i find that if remove the line with ‘@fn’，the problem is solved.

**Comment by albert-github** [comment]
You found the correct reason, the so called, out of place documentation although it is directly before the function.
I should have been a bit more precise in my writing. You create twice an out of place document block for the function with the same scope (namely the global scope) and these out of place blocks are joined and by doxygen added to the first real function (with the right signature) it finds.

It is anyway a bit strange to have in a project multiple functions with the same name (and scope).
