### ISSUE TITLE
Incorrect MinGW link in Installation Instructions

### ISSUE THREAD

**Issue by sgriffithjones** [doxygen/doxygen#10531]
The hotlink provided to MinGW under Installation->'Compiling from source on Windows' directs to a spam site 
(www.mingw.org) instead of the official site (https://www.mingw-w64.org/). 

<img width="628" alt="image" src="https://github.com/doxygen/doxygen/assets/155471529/4e6b44b5-c5d1-415b-9d40-7a28ea4965c7">

**Comment by doxygen** [comment]
@sgriffithjones Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by sgriffithjones** [comment]
Perfect. Thanks for the fix.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
