### ISSUE TITLE
LaTeX formula pngs not generated with doxygen 1.9.x

### ISSUE THREAD

**Issue by momorga** [doxygen/doxygen#10612]
When running doxygen, png files of LaTeX are not generated for formulas embedded in both C++ comments and markdown files. This results in the equations rendering in the html as their alt text, showing, for example,
\$ \bar{CG}^* \$
instead of the png of the rendered equation which cannot be found.

_formulas.aux, _formulas.dvi, _formulas.log, and _formulas.tex are all generated in the html directory. There is nothing in the log to suggest that rendering should have failed, and opening the .tex in TeXstudio and compliling successfully generates formulas.

This happens using doxygen-1.9.4, doxygen-1.9.5, and doxygen-1.9.8.
When using doxygen-1.8.14, all images of formulas are generated and rendered in the html as expected.

All of these are done with pdfTeX 3.141592653-2.6-1.40.24 and on RHEL 7.9.

1.8.14 will generate images for all formulas with LATEX_BATCHMODE set to YES and NO, with prompts for input when set to NO.
1.9.x will not generate images for either, and does not prompt user input when set to NO.

1.8.14 prints to the screen "Generating bitmaps for formulas in HTML..." followed by lines stating the generation of each expected formula png.
1.9.8 has a similar line of "Generating images for formulas in HTML..." but then has none of the following lines.

I am not sure, but based on these it seems like 1.9.x may be skipping a step somewhere in the LaTeX generation.

**Comment by albert-github** [comment]
From what you are presenting here it is hard to see what is actually happening, which commands are you using?

- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by momorga** [comment]
I am running
`doxygen-1.x.x Doxyfile.txt` 
in a local project repo that includes .cpp, .h, and .md files.

The Doxyfile.txt being used is for version 1.9.8 in all the above mentioned runs, but in the past 1.8.14 was run with a 1.8.14 Doxyfile that yielded the same results.

Unfortunately I cannot move any files over from the system where doxygen is being run, but if it would be useful I may be able to try to put together a pseudo-project to reflect what is on that system.

**Comment by albert-github** [comment]
You said you have a problem with a formula and, as far as I can see, the representation in the HTML output.
- So a small example is necessary as well as the used Doxyfiles (a project of just 1 small file will be sufficient as long as it shows the problem).
- interesting is also the result of the the commands
  -  `gs --version`
  - `doxygen -d extcmd` in both cases (probably best to set `QUIT=YES` in the used Doxyfiles).

**Comment by momorga** [comment]
Ghostscript 9.25

1.9.8 prints
`Generating images for formulas in HTML...`
`Executing external command 'latex -interaction=batchmode _formulas >/dev/null\'`

while 1.8.14 prints
`Generating bitmaps for formulas in HTML...`
`Executing external command 'latex _formulas.tex'`
`Generating image form_0.png for formula`
`Executing external command 'dvips -q -D 600 -E -n 1 -p 1 -o _form0.eps _formulas.dvi'`
`Executing external command 'gs -q -g72x50 -r384x384x -sDEVICE=ppmraw -sOutputFile=_form0.pnm -dNOPAUSE -dBATCH -- _form0.ps'`
`Generating image form1.png...` etc.


Both versions ignored the `QUIT=YES` in the doxyfile, but I may have done something wrong there.

I will see what I can put together in terms of an example now

**Comment by albert-github** [comment]
One thing that is a bit strange to me is the ending `\` of >/dev/null\' in the 1.9.8 version

**Comment by momorga** [comment]
I created  small project to try to share the behavior, but have found that it does render as expected.

When running with -d extcmd, I see

`Generating images for formulas in HTML...`
`Executing external command 'latex -interaction=batchmode _formulas >/dev/null'`
`Executing external command 'latex -interaction=batchmode _formulas >/dev/null'`
`Generating image...` etc.

I am now trying to see what differences there may be between the two projects.

**Comment by momorga** [comment]
Okay, so looking through the _formula.log debug output, I was able to identify that the problems seem to coming from when there are errors in the formulas. Namely, the two that I was coming across were
`! Extra }, or forgotten $.`
and
`! Missing delimeter (. inserted).`

Addressing these led to all of the LaTeX rendering again. It looks like when 1.8.14 came across these, LaTeX would make its best guess to correct the formulas and then render all of them. Looking at the log in 1.9.8, it still looks like LaTeX makes the same corrections, but then fails to render any of the formulas. 


Here's a little file that gives an example of the first LaTeX error. 
[main.cpp.txt](https://github.com/doxygen/doxygen/files/14130189/main.cpp.txt)

`doxygen-1.9.8 -g` was run to generate a default Doxyfile, and `INPUT=main.cpp` was added with no other changes made.
`doxygen-1.9.8 Doxyfile` was run.

There are two formulas included, the first renders on its own, but the addition of the second results in neither rendering.

Running `doxygen-1.8.14 Doxyfile` with the same Doxyfile results in both formulas rendering.

**Comment by albert-github** [comment]
So we can conclude that there is an error in the formulas and with the 1.8.14 doxygen version that depending on the setting of `LATEX_BATCHMODE` we see a bit different behavior. 

When `LATEX_BATCHMODE=NO` doxygen stops and waits or user input (which is bad for CI  / automatic systems) and with `LATEX_BATCHMODE=YES` doxygen continues as LaTeX tries to do a best guest. The error:
```
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
```
in the later case gets a bit lost in the other output from the LaTeX etc. processor.

With the doxygen 1.9.8 version we get independent of the `LATEX_BACHTMODE` setting just the error (and also all other. disturbing, output is gone) and the formula images are not generated (as one or another problem was encountered and in case LaTeX does a best guess it would still be a best guess). The fact that none of the images is generated is, generally speaking, because the basic step is done in one go (otherwise the LaTeX engine has to be started many times) and after the basic step the result is split so we get all individual images (but this stage is not reached because of the error). When an error occurs it is never clear whether or not this spills into the next formula.

The fact that both formulas render correctly is because the LaTeX engine chose in this case the right solution, but maybe the user wanted to have a `}` and the formula should have read `\f$ x_{subscript}\} \f$`.

So I think the current behavior is correct seen the fact that an error is given and there is no potential incorrect image generated.

**Comment by momorga** [comment]
Understood, as this is the intended behavior I'll close the issue. Thanks for the help!
