### ISSUE TITLE
How do I generate a document for a function comment in a namespace?

### ISSUE THREAD

**Issue by Dawsonqw** [doxygen/doxygen#10624]
Hi.
I declared a test.h file like this:
```cpp
namespace Show
{
    class A
    {
    public:
        void Test();
    };
}
```

I declare a test.cpp file as follows:
```cpp
#include "test.h"
/**
 * @brief simple test
 */
void Show::A::Test()
{
}
```
However, the generated html document does not display corresponding functions and comments, how can I solve this problem?
The entire generated document reads as follows:
```cpp
test.cpp File Reference
#include "test.h"
[Go to the source code of this file.](https://github.com/doxygen/doxygen/issues/test_8cpp_source.html)
```

**Comment by albert-github** [comment]
It is hard to tell what is wrong in your case but it looks like some information is not processed due to used settings and / or missing documentation blocks. To be able to tell more:

- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by Dawsonqw** [comment]
> It is hard to tell what is wrong in your case but it looks like some information is not processed due to used settings and / or missing documentation blocks. To be able to tell more:
> 
> * Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
> * Please also specify the **full** doxygen version used (`doxygen -v`).

Thanks for the reply.The attachment is a source file in zip format.I'll fix my problem. I need to write the comment information under src/test.cpp instead of include/test.h, however, when I access the generated html file, the page test.cpp displayed is not commented. How do I modify the configuration to achieve this effect?The version of doxygen is 1.10.0
[test_cpp.zip](https://github.com/doxygen/doxygen/files/14232202/test_cpp.zip)
![example](https://github.com/doxygen/doxygen/assets/71950898/b66e18d7-5d25-4437-8df9-d1bc7c73aeb4)

**Comment by albert-github** [comment]
We see the source file
```
#include "test.h"
/**
 * @brief comment...
 */
void test::A::print()
{
}
```
so just the implementation and documentation of the function `test::A::print()`
in the include file we see:
```
namespace test
{
    class A
    {
    public:
        void print();
    };
}
```
so just the definitions.

And in the result pages we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/5a245e68-0566-4900-a685-268c84cba9f9)

and

![image](https://github.com/doxygen/doxygen/assets/5223533/c639be9d-b7f3-4fef-b5e5-6b286c93c74f)

and

![image](https://github.com/doxygen/doxygen/assets/5223533/4c044ed3-3a5b-4de4-88b0-f5cfe1371457)


so doxygen merged the information of the function to one place.

What would you like to see on the `test.cpp` page?

You see the page "test.cpp" due to the fact that you set `EXTRACT_ALL=YES`, setting `EXTRACT_ALL=NO` and documenting the namespace and class would give you the results you would like.

**Comment by Dawsonqw** [comment]
Thank you for your reply！I'm sorry that my previous conversation didn't explain my problem.Below is a file of my original code.I was hoping to generate comments for all member functions in the test.h file, but it didn't work as expected.The final result of the html page is as follows, only one class and its corresponding member functions are generated, but I want all the classes and functions defined in test.h to be generated. So how do I change it to get the effect I want?
[Te.zip](https://github.com/doxygen/doxygen/files/14326581/Te.zip)


![result](https://github.com/doxygen/doxygen/assets/71950898/5e8589d7-f382-4ea3-8921-cb2d7f36c221)

**Comment by albert-github** [comment]
- Which functions / classes are missing?
- which page do you want to view?

I see (when expanding the treeview a bit, in index.html):
![image](https://github.com/doxygen/doxygen/assets/5223533/62b00bf1-16ad-4c66-b580-206df1869ba1)

**Comment by Dawsonqw** [comment]
The following screenshot shows the classes and their functions, which are defined in the test.h file.In fact, only the documentation for the TiaraABs-related classes is generated, while the documentation for the other classes and functions is lost.
![result](https://github.com/doxygen/doxygen/assets/71950898/367042f3-7c35-43fd-b50a-fa4ab380d46e)
I found that the reason for this is the macro shown in the screenshot below. When I remove all the macros from the file, I have the documentation for generating the classes and functions. But this macro should be kept, I don't know how to write Doxygen configuration information to keep the macro and get all the classes and functions documentation.
![macro](https://github.com/doxygen/doxygen/assets/71950898/b5750de9-9c2e-4adc-98b6-315186782770)

**Comment by albert-github** [comment]
There are a number of possibilities:
- define the `MLIR_DECLARE_EXPLICIT_TYPE_ID` where normally the `MLIR_DECLARE_EXPLICIT_TYPE_ID` is defined and guard it with something like `#ifdef RUN_DOXYGEN` and in the setting file under the `PREDEFINED` part set `RUN_DOXYGEN=1`
- define the `MLIR_DECLARE_EXPLICIT_TYPE_ID` n the setting file under the `PREDEFINED` part

Note you should also check the setting of `EXPAND_ONLY_PREDEF` in the settings file whether or not this is intended (especially for the first solution I mentioned this might be important.

**Comment by Dawsonqw** [comment]
I solved the problem. Thank you very much for your meticulous reply.
