### ISSUE TITLE
First element of enum is not properly copied by @addtogroup

### ISSUE THREAD

**Issue by vetri2906** [doxygen/doxygen#10783]
```
/** @addtogroup MT25flash
  * @{
  */
  
  typedef enum
{
  ELEMENT1,      /** element1    */
  ELEMENT2,     /** element2   */
  ELEMENT3,     /** element3    */
} myenum_t;
/** 
  * @}
  */
```

**Comment by albert-github** [comment]
It is a bit clear what you mean:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

but when I run the example with the default doxygen settings the result is:
![image](https://github.com/doxygen/doxygen/assets/5223533/6674f50b-b9a3-4a1c-883c-85129d202fd5)


So the `Element1`  is nor present and the documentation "element1" is added to the `Element2`. This looks all correct 
- the `/** ... */` is for the next element and thus `/** element1    */` will be added to `Element2` . You probably should have used the `/**< ...` construct for documentation after the element
- `Element2` is not documented and due to the settings it is left out

**Comment by vetri2906** [comment]
I used this /**< ... and it fixed the issue. Thankyou so much for your help. Appreciate it a lot !
