### ISSUE TITLE
Create ALIAS with argument for plantUML graph

### ISSUE THREAD

**Issue by SalahEddineGhamri** [doxygen/doxygen#10804]
**Describe the bug**
I am trying to create a single custom command:
```
\include_graph{test.pu}
```

unfortunately this is not working: 
```
ALIASES          += "include_graph{1}=@startuml !include \1 @enduml"
ALIASES          += "include_graph{1}=@startuml ^^ !include \1 ^^ @enduml"
ALIASES          += "include_graph{1}=@startuml @n !include \1 @n @enduml"
ALIASES          += "include_graph{1}=@startuml \\n !include \1 \\n @enduml"
```
The reason is new lines cannot be passed to plantuml generator. This will result in an error. 

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/11904520/18d3c1f9-ca92-4478-834d-f49c7e0a7172)

is there a way to achieve a single custom command (instead of 3 ) to include plantUML files ?  

doxygen 1.8.15

**Comment by albert-github** [comment]
In `ALIASES` the placeholder for a newline is `^^`, so your command would read:
```
ALIASES          += "include_graph{1}=@startuml ^^ !include \1 ^^ @enduml"
```
see: https://www.doxygen.nl/manual/config.html#cfg_aliases
> ... Note that you cannot put [\n](https://www.doxygen.nl/manual/commands.html#cmdn)'s in the value part of an alias to insert newlines (in the resulting output). You can put ^^ in the value part of an alias to insert a newline as if a physical newline was in the original file. ...

I think the problem is usage, otherwise:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by SalahEddineGhamri** [comment]
This was already tried and did not fix the issue.

**Comment by SalahEddineGhamri** [comment]
upgrading to version 1.10.0 fixed my issue
```
ALIASES          += "include_graph{1}=@startuml ^^ !include \1 ^^ @enduml"
````
