### ISSUE TITLE
! LaTex Error: File 'topics.text' not found

### ISSUE THREAD

**Issue by bernatLeclanche** [doxygen/doxygen#10816]
**Describe the bug**
While trying to generate the pdf report using pdflatex the tool fails indicating a  missing .tex file not generated.
! LaTex Error: File 'topics.tex' not found

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/167233866/5cddd6ed-d70e-40c2-a2ea-7616c34d9ef2)

**To Reproduce**
I attach our DoxygenLayout and our template for our .c/.h files
[DoxygenTest.zip](https://github.com/doxygen/doxygen/files/15073810/DoxygenTest.zip)

Tools used=
doxygen  -  1.10.0
graphviz -  10.0.1
https://www.tug.org/texlive/windows.html

**Expected behavior**
Generation of pdf, based on Latex tool.

**Version**
doxygen  -  1.10.0 (Windows 10, 64 bit)

**Stack trace**

**Additional context**
The html report is correctly generated, the problem is in the interpretation of the Latex tool.

**Comment by albert-github** [comment]
You use your own `DoxygenLayout.xml` and this has not been updated to the newest version.
In doxygen 1.9.8 the C++ concept of Modules was introduced and as a result the term "modules" used in doxygen for was (even more) confusing as it was in the past and has been renamed to "topics" (used for commands like `defgroup` etc).

so in `DoxygenLayout.xml` the line:
```
<tab type="modules" visible="yes" title="" intro=""/>
```
should be replaced by:
```
<tab type="topics" visible="yes" title="" intro=""/>
```
(Better would even be to take a new `DoxygenLayout.xml` file and update this to your likings, looks like the only differences are:
```
146a147
>     <detaileddescription title=""/>
165d165
<     <detaileddescription title=""/>
182a183
>       <detaileddescription title=""/>
207d207
<     <detaileddescription title=""/>
```
where the `<` parts are from the default and the `>` parts are from your layout file.

I think the problem is usage.

**Comment by bernatLeclanche** [comment]
Many thanks Albert, I will try it out !

**Comment by bernatLeclanche** [comment]
Problem solved !
