### ISSUE TITLE
Use upstream FindIconv

### ISSUE THREAD

**Issue by Croydon** [doxygen/doxygen#10887]
Similar to https://github.com/doxygen/doxygen/commit/e5c75032987e4b45b04ac978df1e28751f1d08c6 I think it is a good idea to switch to upstream FindIconv

CMake's FindIconv is available since CMake 3.11, so no CMake version bump required https://cmake.org/cmake/help/latest/module/FindIconv.html

**Comment by Croydon** [comment]
Please note that the upstream FindIconv uses a `Iconv_` instead of `ICONV_` prefix for CMake variables, so that needs to be adjusted too in Doxygen's usage.

I am currently trying to update Conan's package for doxygen, we are are currently shipping CMake patches for it, to use the upstream names (which also makes it working with Conan specific things) https://github.com/conan-io/conan-center-index/blob/2587e89c258640a1d169298aecb85e1b318db37f/recipes/doxygen/all/patches/1.9.4-0002-fix-iconv-linkage.patch

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
