### ISSUE TITLE
dontinclude pattern find itself

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10977]
**Describe the bug**
BUG-1) if @dontinclude parse the **own** file than @skip, @line etc find the **own** pattern instead the wanted pattern **if**
the wanted pattern is *behind* the @dontinclude definition.

BUG-2) if the pattern in @skip, @line etc becomes invalid (because of code changed or moved) than there is **no** warning returned
→ this is serious because the *silent documentation bug* is **not** detected

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/27886664/06a3c08b-cc76-412e-9b82-612897e212ae)

**To Reproduce**
use attachment: 
[doxygen_bug__dontinclude.tar.gz](https://github.com/user-attachments/files/16081688/doxygen_bug__dontinclude.tar.gz)

**Expected behavior**
BUG-1 should SKIP the pattern definition itself
BUG-2 should throw a warning if returned text is empty

**Version**
> doxygen -v
1.12.0 (7673d22af1cea4d84bdc00164d9c9a25d693a714)

**Comment by albert-github** [comment]
The documentation says:
> This command searches line by line through the example that was last included using \include or \dontinclude until
it finds a line that contains the specified pattern.

1. "should SKIP the pattern definition itself" I think this is an explicit choice as otherwise it is hard(er) to include its line itself. When the user wants to skip this line it can add the command `\skipline` after the `\skip ...`. So this part is in my opinion usage.
2. "should throw a warning if returned text is empty" Actually I think you say that when a pattern is not found a warning should be given about the not found pattern. I think this should be a marked as a bug.

**Comment by albert-github** [comment]
Regaring the mentioned bug-2 I've just pushed a proposed patch, pull request #10979

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
