### ISSUE TITLE
Doxygen (v1.9.4) in Debian Bookworm fails to find references in markdown files.

### ISSUE THREAD

**Issue by ReenigneArcher** [doxygen/doxygen#11043]
**Describe the bug**
Describe what you see that (you think) is wrong.

Doxygen (v1.9.4) in Debian Bookworm fails to find references in markdown files.

```txt
Generating docs for file src/build/sunshine/docs/source/about/getting_started.md:3: error: unable to resolve reference to 'binaries' for \ref command
/build/sunshine/docs/source/source_code/source_code.md:11: error: unable to resolve reference to 'inline-documentation-blocks' for \ref command
/build/sunshine/docs/source/source_code/source_code.md:17: error: unable to resolve reference to 'documentation-blocks' for \ref command
```

Initially, I thought this may be due to the version being below 1.10, but then noticed that everything works in Ubuntu 22.04 and 24.04. 22.04 ships Doxygen 1.9.1. 24.04 ships Doxygen 1.9.8. I guess this is probably an issue with how Doxygen is compiled, but I am not 100% sure.

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.

[doxygen-issue.zip](https://github.com/user-attachments/files/16460737/doxygen-issue.zip)

**Expected behavior**
Describe what you would have expected or think is correct.

Build docs without error 😎 

**Version**
Mention the version of doxygen used (output of `doxygen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.

1.9.4 in Debian Bookworm

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

I didn't see any related issue mentioned here: https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=stable;package=doxygen

**Comment by albert-github** [comment]
In the doxygen version 1.9.4 I see the warning as reported, in the current doxygen version the warning is gone (actually it is gone since 1.9.7).

I think the problem has been solved in the mean time.

Regarding the debian bugs reports (https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=stable;package=doxygen) they should be reported in the doxygen issue tracker when they are still bugs / enhancement requests.

**Comment by ReenigneArcher** [comment]
@albert-github Was 1.9.1 free of the issue as well? That's the part that confuses me.

**Comment by albert-github** [comment]
I didn't see the warning in the 1.9.1 version, but I very strongly advise against going back to an older version much better would be to go to the current doxygen version (there is a reasonable chance that the version from the release (see https://github.com/doxygen/doxygen/releases/tag/Release_1_11_0) will work on you version as well and otherwise it is not difficult to compile the current doxygen version.

**Comment by ReenigneArcher** [comment]
Thanks, and yea I understand it's better to use newer versions. This is all in CI so don't want to waste time compiling more stuff.

I will close this though as I've decided to make Doxygen 1.10 the minimum allowed due to 1.9.x not supporting `$projecticon` in custom `header.html` files.
