### ISSUE TITLE
Non-reproducible file names in doxygen output

### ISSUE THREAD

**Issue by ellert** [doxygen/doxygen#11138]
**Describe the bug**
The files generated by doxygen whose file names contain the string __unnamedN__ where N is a number are not generated using predictable names.

**To Reproduce**
Se e.g. the xrootd package built for Fedora: https://koji.fedoraproject.org/koji/packageinfo?packageID=10510
The xrootd-doc package that contain doxygen generated documentation should be possible to be declared as a noarch package, but due to the generated files having different names this is not possible.

Here is an example of some files with different names when built from the same source on two different architectures:

$ grep unionXrdXrootdFile /tmp/1
/usr/share/doc/xrootd/html/d9/dbf/unionXrdXrootdFile_8____unnamed163______coll__graph.map
/usr/share/doc/xrootd/html/d9/dbf/unionXrdXrootdFile_8____unnamed163______coll__graph.md5
/usr/share/doc/xrootd/html/d9/dbf/unionXrdXrootdFile_8____unnamed163______coll__graph.svg
/usr/share/doc/xrootd/html/d9/dbf/unionXrdXrootdFile_8____unnamed163______coll__graph_org.svg
/usr/share/doc/xrootd/html/dc/d9d/unionXrdXrootdFile_8____unnamed165______coll__graph.map
/usr/share/doc/xrootd/html/dc/d9d/unionXrdXrootdFile_8____unnamed165______coll__graph.md5
/usr/share/doc/xrootd/html/dc/d9d/unionXrdXrootdFile_8____unnamed165______coll__graph.svg
/usr/share/doc/xrootd/html/dc/d9d/unionXrdXrootdFile_8____unnamed165______coll__graph_org.svg

$ grep unionXrdXrootdFile /tmp/2
/usr/share/doc/xrootd/html/d9/d3b/unionXrdXrootdFile_8____unnamed166______coll__graph.map
/usr/share/doc/xrootd/html/d9/d3b/unionXrdXrootdFile_8____unnamed166______coll__graph.md5
/usr/share/doc/xrootd/html/d9/d3b/unionXrdXrootdFile_8____unnamed166______coll__graph.svg
/usr/share/doc/xrootd/html/d9/d3b/unionXrdXrootdFile_8____unnamed166______coll__graph_org.svg
/usr/share/doc/xrootd/html/dd/ddb/unionXrdXrootdFile_8____unnamed164______coll__graph.map
/usr/share/doc/xrootd/html/dd/ddb/unionXrdXrootdFile_8____unnamed164______coll__graph.md5
/usr/share/doc/xrootd/html/dd/ddb/unionXrdXrootdFile_8____unnamed164______coll__graph.svg
/usr/share/doc/xrootd/html/dd/ddb/unionXrdXrootdFile_8____unnamed164______coll__graph_org.svg

See also the reproduciblebuild check for the xrootd package built for Debian: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/xrootd.html

Here you can see the same unpredictable file names when building the package twice on the same architecture.

**Expected behavior**
Predictable file names - reproducible when building from the same source without changes.

**Version**
1.9.7
1.10.0
1.11.0
1.12.0

**Comment by albert-github** [comment]
I think the problem lies here in the multi-threading. With unnamed entities doxygen needs an identification so that it can distinguish the different unnamed entities and as with multi-threaded applications it is not guaranteed in which order files / entities are processed a different numbering scheme can be the result (and I can imagine that it might even happen when running the output to different directories on the same machine).

So an alternative "numbering scheme" should be created that wouldn't have this problem...

I think that setting `NUM_PROC_THREADS=1` would probably solve the issue, but might be unwanted as it probably would slow down the processing considerably.

**Comment by doxygen** [comment]
@ellert Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by ellert** [comment]
> @ellert Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

This version works for me. Thank you for addressing this issue.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
