### ISSUE TITLE
MACRO_EXPANSION = YES may place other documentation into the body

### ISSUE THREAD

**Issue by sebhub** [doxygen/doxygen#11158]
**Describe the bug**
The following file
```c
/**
 * @file
 *
 * File.
 */

#define D0 0 /**< Define 0. */

/**
 * Define 1.
 */
#define D1 1

/**
 * Function.
 */
int f(void)
{
  return D0 + D1;
}
```
produces the following in-body description for f():
```xml
    <sectiondef kind="func">
      <memberdef kind="function" id="f_8c_1a470bef4e681b2849d922b05ec7d44e47" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>int</type>
        <definition>int f</definition>
        <argsstring>(void)</argsstring>
        <name>f</name>
        <param>
          <type>void</type>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para>Function. </para>
        </detaileddescription>
        <inbodydescription>
<para>&lt; Define 0.</para>
        </inbodydescription>
        <location file="f.c" line="17" column="5" bodyfile="f.c" bodystart="17" bodyend="20"/>
      </memberdef>
    </sectiondef>
```
with
```
MACRO_EXPANSION = YES
```
The `&lt; Define 0.` seems to be a result of the macro expansion which includes the comment. The D1 expansion causes no issues.

**To Reproduce**
Run doxygen with `MACRO_EXPANSION = YES` for the file above.

**Expected behavior**
Macro expansion should remove comments.

**Version**
1.13.0

**Comment by albert-github** [comment]
Please, especially when using the doxygen master version as that is a moving target, so
- always specify the **full** doxygen version used (`doxygen -v`).

Furthermore (makes live a bit easier):
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

I tested with doxygen 1.13.0 (8b36fe8273d5fb88fc57e661747a0f4faa319038) and saw the same (in XML and also for HTML):
![image](https://github.com/user-attachments/assets/6d1176fa-2161-4229-af63-b23a7dc5d28e)

I did some experiments and wit inline comments like `///<` or `//!<` it looks like it is working OK.
I extended the example slightly to :
```
/**
 * @file
 *
 * File.
 */

#define D0 0 /**< Define 0. */

#define D2 2 //!< Define 2.

#define D3 3 ///< Define 3.


/**
 * Define 1.
 */
#define D1 1

/**
 * Function.
 */
int f(void)
{
  double Y = D2 + D3 + D1 + D0;

  return D0 + D1 + D3 + D2;
}
```
which results in:
![image](https://github.com/user-attachments/assets/6402ed2b-6c7e-4ba7-adbd-35434a035fa3)

so just the `D0` giving problems.

When looking at the doxygen preprocessor output (`doxygen -d preprocesssor`) we see:
```
00001 /**
00002  * @file
00003  *
00004  * File.
00005  */
00006
00007 #define D0   /**< Define 0. */
00008
00009 #define D2   //!< Define 2.
00010
00011 #define D3   ///< Define 3.
00012
00013
00014 /**
00015  * Define 1.
00016  */
00017 #define D1
00018
00019 /**
00020  * Function.
00021  */
00022 int f(void)
00023 {
00024   double Y = 2 + 3 + 1 + 0 /**< Define 0. */ ;
00025
00026   return 0 /**< Define 0. */ + 1 + 3 + 2 ;
00027 }
00028
```

When I remember correctly the `/**<` comment is left in the preprocessed output for things like enum values, is here `//...` type comments might have negative effects like removing everything from the define line after the comment, like:
```
/// \file

#define X(x) \
   /** the comment for x */ \
   x,


#define Y(x) \
   x, /**< the comment for x */


enum class tst
{
   X(elem1)
   X(elem2)
   Y(elem3)
   Y(elem4)
   X(elem5)
   X(elem6)
};
```
which gives:
![image](https://github.com/user-attachments/assets/1dfdc2ea-f5ed-43a4-b8b8-0d949216f2b3)

and preprocessor output:
```
00001 /// \file
00002
00003 #define X(x) \
00004     \
00005
00006
00007
00008 #define Y(x) \
00009       /**< the comment for x */
00010
00011
00012 enum class tst
00013 {
00014     /** the comment for elem1 */   elem1,
00015     /** the comment for elem2 */   elem2,
00016     elem3, /**< the comment for elem3 */
00017     elem4, /**< the comment for elem4 */
00018     /** the comment for elem5 */   elem5,
00019     /** the comment for elem6 */   elem6,
00020 };
```

Extended original example: [example.tar.gz](https://github.com/user-attachments/files/17145457/example.tar.gz)

Simple enum example: [example_enum.tar.gz](https://github.com/user-attachments/files/17145461/example_enum.tar.gz)

So all in all I think this is by design and thus usage.

**Comment by sebhub** [comment]
Thanks a lot for your detailed analysis. I did read the documentation again, and it has even a red warning box mentioning this behaviour.

Unfortunately, this style is used in 1000s of register bit field defines in the Xilinx Embedded Software library, for example:

https://github.com/Xilinx/embeddedsw/blob/master/XilinxProcessorIPLib/drivers/iicps/src/xiicps_hw.h

I will try to convince them to use the `//!<` style instead.
