### ISSUE TITLE
Building docs for the llvm-project with doxygen takes more than 20 hours

### ISSUE THREAD

**Issue by L00pZBreak3r** [doxygen/doxygen#11205]
**Describe the bug**
Have you ever tried to build docs for the [llvm-project](https://github.com/llvm/llvm-project)? It uses doxygen for this and the building takes more than 20 hours! My workstation is not the most powerful in the world, of course, so it has something to do with the issue, but I don't think that using the latest Threadripper would help much.

Has anyone ever investigated the issue?

**To Reproduce**
Build docs for the [llvm-project](https://github.com/llvm/llvm-project).

**Expected behavior**
20 hours is way too long.

**Version**
The latest release 1.12.0 and the latest doxygen available built from the sources both work 20 hours.

**Comment by albert-github** [comment]
Indeed the processing power is of great influence. 
The question is what settings  are used for:
- `NUM_PROC_THREADS`
- `DOT_NUM_THREADS`

Also useful to know are the processing times of the individual parts, so in the settings `QUIET=NO` and use `doxygen -d time`

**Comment by albert-github** [comment]
The mentioned part is not threaded (as far as I know) and is is also not (really) possible to do this.
I think the problem lies more in the underlying LLVM project that consists in a number of independent parts and an part that is used by multiple part. A, possible, solution might be to build the part used by the multiple other parts and generate from this also the TAG file and build the other parts separately (using the generated tag file). This procedure is also mentioned in the manual.

**Comment by doxygen** [comment]
> All 20 hours are spent for part "Building full member lists recursively...".

That is useful input. As Albert indicated, this part is currently running in a single thread. Parallelizing this part may not be easy indeed, but worth investigating. At least there is clearly some non-linear scaling in that step.

**Comment by albert-github** [comment]
@paule32  I don't think this applies here as the time is not spend during the output / cleanup phase but in an  earlier stage.

**Comment by doxygen** [comment]
@L00pZBreak3r Looks like the problem was for a large part triggered when there were many using/typedefs with the same name in different contexts, and these type names were used in method arguments. For instance, `size_type` already had more than 2500 definitions for the subset of `llvm` I tried. I've now added a cache to prevent re-computing the same results multiple times.

Please verify by how much the running time is now reduced, preferably run Doxygen with `QUIET=NO` option in the config and the `-d time` command line option and share the summary part after the `--------`.

**Comment by L00pZBreak3r** [comment]
@doxygen 
Wow!
You patch seems to fix the issue. Now the building tooks around 6 hours. It looks like an appropriate time for this task.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
