### ISSUE TITLE
Customize example page (Origin: bugzilla #149253)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1196]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-08-04 08:24:50 +0000, Philipp Frauenfelder wrote:

    I do have a few examples in our project. Actually they are more tutorials
    than
    examples. They have descriptive names and should be looked at in a specific
    order. However, this specific order is not the same as the alphabetic order
    of
    the example names.
    
    I have created a tutorials index with the @page command which appears in the
    'related pages' section (the index contains some more description on the
    examples). Now, there are two pages referencing the same examples: one with
    the
    good ordering and one with the alphabetical ordering.
    
    I would like to either turn off the examples index alltogether or have a
    possibility to customize it / replace it with my own @page.
    
    You can have a look at what I mean here:
    - Tutorials overview (the 'better' examples index):
      http://www.concepts.math.ethz.ch/doxygen/html/tutorials.html
    - Doxygen generate examples index (with 'wrong' alphabetical ordering):
      http://www.concepts.math.ethz.ch/doxygen/html/examples.html

On 2010-08-11 12:48:55 +0000, Anne wrote:

    What nice pages you have Philipp! I'm glad they're still up to view; 2004 is
    a long time ago now :).
    
    I like your ability to see both orderings of the examples. Since they both
    have links, why not add either straight html or <see cref=""/> links to the
    other pages on each one? So tutorials.html can say "for an alphabetical
    list, go to [examples]" and examples.html say "for descriptions and the
    proper sequence, go to tutorials."
    
    On Tutorials you already have text you've written.
    On Examples, if none of the text is handwritten, then maybe adding a
    description blurb would be an easy enhancement. Otherwise, you could perhaps
    [a bit annoyingly] add the blurb to the top of each tutorial itself.

On 2010-08-11 12:55:40 +0000, Anne wrote:

    Philipp or anyone else, if you happen to read this, I'd be curious how you
    constructed your pages. I would like to have similar writeups. Thank you!

On 2016-04-04 12:49:56 +0000, ferrishu3886@gmail.com wrote:

    Hello, I'm up with Anne. It would be really nice if anyone can offer some
    pointers on how to construct those pages. Thanks!

**Comment by albert-github** [comment]
Unfortunately the tutorials page is not visible anymore, the examples page still is visible.
From what I understand from the discussion for a tutorial the pages should not be automatically ordered but have the order of the flow of the tutorial (which is natural).

I think that with the current possibilities in doxygen like the handling op pages and sections, the `\subpage` command, the support of markdown and the possibilities of the `\ref` command and the possibilities to change the layout of pages and defining user pages I think it should be possible to generate a tutorial.
Note that the doxygen manual is also generated by means of doxygen.

Seen the time elapsed and especially the fact that there is no example project to show the wishes I think the issue is incomplete.
