### ISSUE TITLE
Add external documents to HTML tree (Origin: bugzilla #163924)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1408]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-01-13 11:41:44 +0000, Chuck Bass wrote:

    I have PDF documentation that needs to be integrated into the doxygen output
    tree and can't find a way to do it without a global reference for the
    location
    of the PDF.  
    
    Ideally I'd like to be able to say:
    
    \extdoc  <file>  <caption>
    
    This would  create a link to <file> with the given <caption> AND copy the
    file
    into the html folder.  (problems with name collisions?)  This allows a
    standalone doc tree.
    
    The \image command does all of this (and more) but it is expects the file to
    be
    stuck in an <image> tag instead of an <a> tag. 
    
    Application:  I write drivers for IC's and each driver has 1 or more PDF
    data
    sheets.  I am always saying "see datasheet xxx for more details" It would
    really
    be nice If I didn't have kludge this to get it to work.

**Comment by albert-github** [comment]
Since doxygen version 1.5.7 doxygen has the possibility to define a layout file (see setting `LAYOUT_FILE` and the paragraph in the documentation about customiziong the output i.e. https://www.doxygen.nl/manual/customize.html) and with the user of the 
"tabs" "user" and "usergroup" it is possible to add external documents in the generated HTML tree.

I think this enhancement request has been solved in the mean time,
