### ISSUE TITLE
Spurious warnings from documented functions in unnamed namespace (Origin: bugzilla #168813)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1475]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-02-28 20:15:04 +0000, Braden wrote:

    Please describe the problem:
    I have lots of code in unnamed namespaces, much of which has doc-comments.
    With
    current CVS doxygen, I'm seeing lots of warnings like this:
    
    /home/braden/src/openvrml/openvrml/src/libopenvrml/openvrml/browser.cpp:136:
    Warning: documented function `proto_node_class::route::route' was not
    defined.
    
    That function *is* defined; it's the constructor for the inner class
    proto_node_class::route. proto_node_class is in an unnamed namespace.
    
    Steps to reproduce:
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

**Comment by albert-github** [comment]
Checked with the repository as found with https://github.com/doxygen/doxygen/issues/1521 and the content at the date of the issue together with doxygen 1.4.1 but could not find the indicated warning in the resulting warnings.
With the 1.9.5 version there are til quite a few warnings but I think (analogous to the problem with the issue #1521)  that they are mostly coming from the inconsistent namespace names.

I think the issue is incomplete.
