### ISSUE TITLE
out-of-line variable doc mistaken for function (Origin: bugzilla #171921)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1521]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-03-28 23:01:48 +0000, Braden wrote:

    Version details: 1.4.2
    
    I have the following doc-comment:
    
    namespace openvrml {
    /**
     * @var const double pi
     *
     * @brief pi
     */
    }
    
    openvrml::pi is a constant defined in a header file. I get the following
    warning
    from doxygen 1.4.2, suggesting that it mistakes this for documentation for a
    function:
    
     Warning: no matching file member found for
    const double openvrml::pi()
    Possible candidates:
      const double pi
      const double pi

**Comment by albert-github** [comment]
When using a normal definition of `pi`
```
namespace openvrml {
  const double pi = 3.141592;
}
```
there are no problems with the 1.4.2 version.

After some searching I found the repository https://github.com/bradenmcd/openvrml and went back here to the time of the issue and found (shortened):

```
/// \file

/**
 * @namespace openvrml
 *
 * @brief The OpenVRML Runtime Library
 */
namespace openvrml {
/**
 * @var const double pi
 *
 * @brief pi
 */
}
```

```
/// \file

namespace {
    namespace openvrml_ {

        const double pi     = 3.14159265358979323846;
}
}
```

```
/// \file

namespace {

    const double pi     = 3.14159265358979323846;
}
```

running this with the 1.4.2 version it gives:
```
.../aa.cpp:10: Warning: no matching file member found for
const double openvrml::pi()
Possible candidates:
  const double pi
  const double pi
.../bb.h:6: Warning: Member pi of namespace openvrml_ is not documented.
```

In the 1.9.5 version it gives:
```
aa.cpp:10: warning: documented symbol 'const double openvrml::pi' was not declared or defined.
```

I think the problem is that the namespace names are not matching and that the original problem (about the functions) has been solved in the mean time.


Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10112661/example.tar.gz)
