### ISSUE TITLE
Documented elements in unnamed namespace produce warnings (Origin: bugzilla #319458)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1880]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-22 03:57:43 +0000, Braden wrote:

    I have a number of documented members of unnamed namespaces. With current
    doxygen CVS, these produce warnings that look like this:
    
    Warning: no matching class member found for
      void transform_node::update_transform() const
    Possible candidates:
      void @1::transform_node::update_transform() const

**Comment by albert-github** [comment]
With the 1.5.3 and 1.5.4 I could not reproduce the exact error message (due to missing information) but I got:
```
aa.cpp:5: Warning: no matching class member found for
  anonymous_namespace{aa.cpp}::transform_node::update_transform()
Possible candidates:
  anonymous_namespace{aa.h}::transform_node::update_transform()
```
for the problem with:
**aa.h**
```
/// \file


namespace {
  /// the class
  class transform_node
  {
    public:
      /// the fie
      update_transform();
  };
}
```
**aa.cpp**
```
/// \file


namespace {
  transform_node::update_transform(){}
}

```
and **Doxyfile**
```
QUIET = YES
EXTRACT_ANON_NSPACES = YES
```

with the 1.9.5 version of doxygen these warnings are gone.

I think the problem has been solved in the mean time

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10098408/example.tar.gz)
