### ISSUE TITLE
doxygen mishandles backslash continuations in C preprocessor statements (Origin: bugzilla #325619)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1980]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-01-03 13:19:16 +0000, Thomas Dickey wrote:

    Please describe the problem:
    When doxygen encounters a backslash in a C preprocessor
    statement, it gets confused.  In some cases (see 320975
    and 134216), the remainder of the file is unusable.
    
    Steps to reproduce:
    1. run doxygen 1.4.6 on vile (I tested with vile 9.5 using patches 9.5a-9.5d
    from ftp://invisible-island.net/vile/patches).
    2. This was on Windows/XP (I used the wizard to setup a doxyfile).
    3. 
    
    
    Actual results:
    viewing the source for estruct.h, it loses track around line 1390, and
    is unusable after that.  The view for mktbls.c is unusable at line 730,
    since
    it no longer knows where functions are.
    
    Expected results:
    parser doesn't get confused.
    
    Does this happen every time?
    yes
    
    Other information:
    can provide a copy of the doxyfile, of course.

**Comment by albert-github** [comment]
It is hard to guess what is the problem here due to missing Doxyfile and also a clear indication what is wrong.

I found a vile 9.5 and after line 730 of mktbls.c there are some static functions that are not shown in version 1.4.6 but are shown in version 1.9.1 when using the Doxyfile:
```
RECURSIVE=YES
EXTRACT_ALL=YES
EXTRACT_STATIC=YES
SOURCE_BROWSER = YES
STRIP_CODE_COMMENTS= NO
```

When removing the code around line 730 the version 1.4.6 shows also the static functions.

I think the problem has been solved in the mean time as 1.9.1 always shows the right information.
