### ISSUE TITLE
C structures should be able to use typedeffed name in output (Origin: bugzilla #326786)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1993]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-01-13 04:02:15 +0000, Eric Anholt wrote:

    The traditional way of defining a structure in C (afaik) that's going to
    always be used by its typedeffed name is:
    
    typedef struct _foo foo;
    
    /**
     * The glorious foo structure
     */
    struct _foo {
        int dummy;   /**< Some dummy variable */
    };
    
    In the documentation, this shows up in the class list/data structures as
    "_foo" when really I want "foo".  If I use "@struct foo" in the comment
    header, it shows up like I want in the class list, only it just contains the
    description and lacks the information about "dummy".
    
    It would be nice if there was a way to say that the preferred name of
    "struct _foo" is "foo" so that it would show up in the documentation that
    way.  Bonus points if it would also catch references to "struct _foo" and
    silently point them at the real "foo" page.
    
    (Version 1.4.1 in use here, though I couldn't find anything in the docs
    pointing to this being fixed.  I've got a similar issue with enums as well
    as structs.)

**Comment by albert-github** [comment]
In the doxygen 1.4.1. version we see the output as indicated:
![image](https://github.com/user-attachments/assets/09a9479d-b336-403b-b0ae-d45d1d568f1e)


Since doxygen version 1.5.4 the setting `TYPEDEF_HIDES_STRUCT` exists. From the changelog:
> Added config option TYPEDEF_HIDES_STRUCT which when enabled treats a typedef of a struct as a struct with the name of the typedef.

When using this setting in the current doxygen 1.12.0 version we get:
![image](https://github.com/user-attachments/assets/b8933d59-a304-492c-82fd-da675c975336)


I think this enhancement request has been solved in the mean time.
