### ISSUE TITLE
Incorrect parsing of //!< blocks (Origin: bugzilla #328398)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2010]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-01-24 09:54:53 +0000, Paul Fotheringham wrote:

    Please describe the problem:
    One of the examples mentioned in the manual fails to work ie.
    
    class A
    {
    	int i;	//!< detailed 1
    		//!< detailed 2
    };
    
    produces incorrect documentation with "detailed 2" as the brief and
    "detailed 1"
    as the detailed description.
    
    Furthermore the following example also produces incorrect documentation
    
    class A
    {
    	int i;	//!< brief i
    	//! brief j
    	int j;
    };
    
    where "brief i" is used as the detailed description for i.
    
    
    Steps to reproduce:
    1. Insert the code above into a source file.
    2. Run Doxygen 1.4.6 on Windows.
    
    
    Actual results:
    Incorrect documentation produced.
    
    Expected results:
    The first code snippet should produce only a detailed description for i
    whereas
    the second should produce two brief descriptions, one for i and one for j.
    
    Does this happen every time?
    Yes.
    
    Other information:
    In the second code snippet inserting a blank line after the declaration of i
    fixes the problem.

**Comment by albert-github** [comment]
When using the following source code:
```
/// \file

/// docu class A
/// \include bb.h
class A
{
    int i;    //!< detailed 1
              //!< detailed 2
};


/// docu class B
/// \include bb.h
class B
{
    int i;    //!< brief i
    //! brief j
    int j;
};
```
and settings file:
```
QUIET=YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXAMPLE_PATH = .
STRIP_CODE_COMMENTS = NO
```
we get in the doxygen 1.4.6 version as output:
![image](https://github.com/user-attachments/assets/d6ef1c72-219d-4c8d-b3dc-f1d77ca40133)

![image](https://github.com/user-attachments/assets/42c8369f-ccc9-437d-a728-28f48dde6129)

and

![image](https://github.com/user-attachments/assets/219b2451-e409-4b73-bc65-d7d9c846c068)

![image](https://github.com/user-attachments/assets/0bffeab1-5a3c-4d3c-a5c3-5c4eb2f2ce60)

So I don't see the splitting of the "Detailed" parts .

When I use the setting `JAVADOC_AUTOBRIEF=YES` I get:
![image](https://github.com/user-attachments/assets/0982f2fc-5acc-4083-88ee-e86bc6331c94)

![image](https://github.com/user-attachments/assets/af6587dd-d3c0-44f0-b9c3-b97364d26578)

and
![image](https://github.com/user-attachments/assets/2426017f-b065-40de-8a7f-916f3b22c3dc)

![image](https://github.com/user-attachments/assets/e3547e86-6583-4315-a421-91854b85528a)


This looks like the intended output. 
An interesting setting in this context is also `REPEAT_BRIEF` (with default `YES`).
Also interesting might be `QT_AUTOBRIEF` introduced with doxygen version 1.5.3)

I think the problem is usage
