### ISSUE TITLE
Anonymous namespace + \file warns on local class typedef (Origin: bugzilla #330297)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2034]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-02-07 18:29:32 +0000, Kevin J Bluck wrote:

    Given a config with EXTRACT_LOCAL_CLASSES set to NO, when Doxygen parses a
    file with these contents:
    
    *************************
    /// \file Doxytest.cpp
    
    namespace
    {
      class TestTypedef
      {
        public:
          typedef wchar_t  char_type;
      };
    }
    *************************
    
    it throws the warning: 
    
    doxytest.cpp(8): Warning: Member char_type of file doxytest.cpp is not
    documented.
    
    The essential elements to reproducing this are:
    
    1. Local class in a .cpp declared inside an anonymous namespace.
    2. Local class declares a public typedef member.
    3. \file command referring to the file in question, which doesn't actually
    have to be located in the same file.
    
    If any of these 3 elements are eliminated, the warning goes away.
    
    Using Doxygen 1.46 on Win2000.

**Comment by albert-github** [comment]
With the doxygen version 1.4.6 we h\get the warning:
```
Doxytest.cpp:8: Warning: Member char_type of file Doxytest.cpp is not documented.
```
and the output looks like:
![image](https://github.com/doxygen/doxygen/assets/5223533/dd2c446b-c756-4507-a096-024443b9a7be)


With the current, 1.9.8 version the warning is gone and the output looks like (due to the `\file` command the file is still present):
![image](https://github.com/doxygen/doxygen/assets/5223533/3c0d2766-c39a-4bd0-b592-ee51949d343a)


I think the problem has been solved in the mean time.
