### ISSUE TITLE
INCLUDE_PATH does not work as expected (Origin: bugzilla #330540)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2037]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-02-09 17:24:05 +0000, Stephen Brennan wrote:

    Please describe the problem:
    The setting of the INCLUDE_PATH configuration option does not seem have any 
    impact on doxygen's XML or HTML output.
    
    Steps to reproduce:
    Create a C program that calls printf
    set INCLUDE_PATH to point to the directory containing stdio.h
    run doxygen
    
    
    Actual results:
    the HTML output does not link printf to stdio.h
    
    Expected results:
    I would expect files included through the INCLUDE_PATH to be treated as
    source
    files.
    
    Does this happen every time?
    yes
    
    Other information:

On 2006-06-28 04:27:13 +0000, Ned wrote:

    Version 1.4.6 and 1.4.7 of Win32 binary has this problem, can not comment on
    ealier versions.
    
    Following the steps in prior post is repeatable.

**Comment by albert-github** [comment]
Problem here is an interpretation problem.
Looking at the documentation we see:
> `INCLUDE_PATH `
> The `INCLUDE_PATH` tag can be used to specify one or more directories that contain include
files that are not input files but should be processed by the preprocessor.

This indicates that the code is not added to the documented code but only certain aspects (`define`s are set).
There is no documentation, not even with `EXTRACT_ALL=YES`), where could be pointed to.
The link to e.g. `printf` cab be established either by:
- add in the file where `printf` resides to the `INPUT`
- add a `TAGFILES` which contains the tag to `printf` and the reference to the appropriate documentation

I think the problem is usage
