### ISSUE TITLE
Display warning for undocummented function (Origin: bugzilla #346854)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2195]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-07-07 09:11:05 +0000, JÃ©rÃ´me Martin wrote:

    public functions/methods/... which are not docummented should be consider as
    a pb, display a warning message

**Comment by albert-github** [comment]
It is unclear in to which situation OP refers to.
When having a default Doxyfile and a source file like:
```
/// \file

void undoc();

```
in version 1.4.* we get the warning:
```
aa.h:3: Warning: Member undoc() of file aa.h is not documented.
```

Also with the current version (1.9.1) we get a warning:
```
aa.h:3: warning: Member undoc() (function) of file aa.h is not documented.
```

So I think that there is no bug here, only I situation I can think of is when `EXTRACT_ALL` is set but in that case warnings are suppressed by design.
