### ISSUE TITLE
\section, \subsection, \paragraph - support in other doxygen blocks (Origin: bugzilla #441185)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2496]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-25 12:57:02 +0000, Jonathan Lynch wrote:

    New feature request: 
    Support \section, \subsection, \paragraph commands inside doxygen comment
    blocks with the file tag, or defgroup tag, so that I can have sections under
    the detailed description section. Currently these are supported inside
    blocks with the \page tag.

On 2007-10-15 19:41:05 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

On 2013-03-06 13:08:51 +0000, Alexey Sergeev wrote:

    I also vote for this and an extension of this. I would like to see sections,
    subsections and table of content in \class.
    This is the way it works in qdoc and it is very useful when documenting
    complicated classes.

**Comment by albert-github** [comment]
With the version that was valid at the moment that the issue was written (doxygen 1.5.2) , the simple file:
```
/** \file
  * \section sect0 First file section
  *
  * \subsection subsect0 First file subsection
  *
  * \subsubsection subsubsect0 First file subsubsection
  */
*/


/**
  * \section sect1 First section
  *
  * \subsection subsect1 First subsection
  *
  * \subsubsection subsubsect1 First subsubsection
  */
class myclass
{
  public:
/**
  * \defgroup mgrp My Group
  * \{
  * \section sect3 First group function section
  *
  * \subsection subsect3 First group function subsection
  *
  * \subsubsection subsubsect3 First group function subsubsection
  */

  /**
   * The function documenttaion
   */
  void myfiegrp(void);
/**
  * \}
  */
/**
  * \section sect2 First function section
  *
  * \subsection subsect2 First function subsection
  *
  * \subsubsection subsubsect2 First function subsubsection
  */
  void myfie(void);
}
```
and settings
```
QUIET = YES
```

I see for e.g. the file part:

![image](https://user-images.githubusercontent.com/5223533/177575320-ab63bfae-e4c1-4b9b-be4c-25706b9426d5.png)

similar I see for the current version 1.9.4 and also for the other mentioned parts (`\class`, `\defgroup`).

So it is unclear what is missing as no example is provided, I think the issue, description, is incomplete.

Example: 
[example.tar.gz](https://github.com/doxygen/doxygen/files/9055709/example.tar.gz)
