### ISSUE TITLE
HTML-Help does not open pages containing subpages when selected through the tree. (Origin: bugzilla #485371)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2652]
status NEW severity *minor* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-10 12:22:35 +0000, Johann Stampler wrote:

    When I open index.html in the browser, I get a page for every item clicked
    in the navigation tree. This could also be possible in HTML Help by adding
    the link information to the corresponding entry in index.hhc
    
    Other information:

**Comment by albert-github** [comment]
It is unclear what is meant with "I get a page for every item clicked
in the navigation tree." and its relation to HTML Help, i.e. where the problem lies.
I do see e.g.g. in the doxygen manual that in the 1.5.3. version there was only 1 level in the HTML Help tree and in the 1.9.3 version there are multiple levels.

Seen the is is unclear what is exactly the problem this issue is not complete, though seen the results of the 1.9.3. version the problem might have been solved in the mean time.
