### ISSUE TITLE
REPEAT_BRIEF does nothing in XML output (Origin: bugzilla #488523)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2673]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-20 07:36:31 +0000, Lisa wrote:

    Please describe the problem:
    Setting the REPEAT_BRIEF option in the configuration file has no effect when
    the output mode is set to XML. This is contrary to the documentation, which
    suggests that REPEAT_BRIEF will cause the brief description to be prepended
    to the detailed description.
    
    Steps to reproduce:
    1. Enable REPEAT_BRIEF
    2. Set output type to XML
    3. Build the documentation
    
    
    Actual results:
    The brief description appears ONLY in the brief description node. It is not
    prepended to the detaileddescription node as the documentation says.
    
    Expected results:
    The brief description should be prepended to the detailed description inside
    of the detaileddescription node.
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2007-10-22 18:22:49 +0000, Dimitri van Heesch wrote:

    *** Bug 488524 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
I think the problem here is the interpretation of the goal of the XML output. Contrary to the output formats like HTML. LaTeX, RTF, Docbook it is intended as an intermediate output format that further can be processed by the user. To give the user all flexibility doxygen does not impose all the restrictions laid out by the doxygen settings and as a result e.g. brief descriptions are nor repeated in the detailed description in the XML output even when `REPEAT_BRIEF=YES.

An interesting proposed pull request in this matter is #8463

So I don't think the problem is a bug but usage.
