### ISSUE TITLE
c# public property with private accessor (Origin: bugzilla #508258)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2779]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-01-09 10:37:12 +0000, Mad Martin wrote:

    A property marked as public, but containing a private set accessor shows up
    as follows:
    
    Example:
    /// <summary>
    /// gets the value of A
    /// </summary>
    public static string A
    {
        get { return _A; }
        private set { _A = value;  }
    }
    
    produces:
    
    static string A [get, set] 
      gets the value of A
    
    and in Detail:
    string A [static, get, set]  
    
    gets the value of A
    
    the private modifier on the set accessor is never mentioned

**Comment by albert-github** [comment]
It is a bit unclear which settings are required to get the output as show.
With the current, 1.9.8, version of doxygen and the settings
```
QUIET = YES
EXTRACT_ALL = YES
EXTRACT_STATIC = YES
```
we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/5aa1939e-90b0-448e-9067-68447cb5a082)

When we enable `EXTRACT_PRIVATE = YES` we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/cb41058a-e51a-4db9-8dfe-f255076de1ba)


This all looks OK to me, so I think that either the issue was incomplete or has been solved in the mean time.
