### ISSUE TITLE
VERBATIM_HEADERS - only works with header files with file type (Origin: bugzilla #549438)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3058]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-08-26 14:27:01 +0000, Ernst wrote:

    Although VERBATIM_HEADERS is set to YES there is no link âGo to the source
    code of this file.â for header files without a file extions such as .h.
    
    ----------------------------------------
    
    Example 1 - good:
    
    include Â» osgShadow
    
    mainpage.h File Reference
    
    Go to the source code of this file.
    
    Detailed Description
       ...
       ...
    
    ----------------------------------------
    
    Example 2 - missing link:
    
    include Â» osgShadow
    
    Version File Reference
    
    #include <osgShadow/Export>
    
    Defines
    #define 	OSGSHADOW_VERSION   1
    
    Functions
       ...
       ...
    
    ----------------------------------------
    
    This behaviour is reproducible.
    
    If SOURCE_BROWSER is set to YES then the expected link is there - but I
    guess this is because of the linking to source code documentation.
    
    Regards
    Ernst

**Comment by albert-github** [comment]
The problem is still present in the current master version (1.9.7 (8887ee5387624fafa7a46dafa6a4f8183d45d1c6)) and shows as:

![image](https://user-images.githubusercontent.com/5223533/218263041-e51c62d7-f61d-40e4-835d-4cf5a89a851b.png)

in the file the file without extension where we don't see the text "Go to the source code of this file." whilst in a file with extension we see the text:

![image](https://user-images.githubusercontent.com/5223533/218262984-9d6ef798-f01d-44de-b477-6859d8ce480c.png)


Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10713845/example.tar.gz)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9851

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
