### ISSUE TITLE
preprocessor doesn't handle correctly documentation generated by a macro (Origin: bugzilla #556550)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3126]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[pre.l](https://sourceforge.net/projects/doxygen/files/attachments/bug556550_120717_pre.l/download/download)_ (ID 120717)

On 2008-10-16 14:00:03 +0000, Claire Chardiny wrote:

    Please describe the problem:
    the doxygen preprocessor doesn't handle correctly documentation generated by
    a macro.
    For example if you have in a header file :
    
     ILOEXTENSIONHNONINLINE(IloAlgorithm)
    
    and in another :
    
    #define ILOEXTENSIONHNONINLINE(hname) \
    /** \
     * <p>This member function returns a character string specifying \
     * the name of the invoking object (if there is one).</p> \
     *  @@see @0#end() \
     */ \
      const char * getName() const; \
    
    The genetation works fine but the backslashes are not removed and the see
    also section has disappeared:
    
    \
    
    This member function returns a character string specifying \ the name of the
    invoking object (if there is one).
    \ \ 
    
    
    
    Steps to reproduce:
    1. Create a similar sample
    2. launch Doxygen generation
    
    
    
    Actual results:
    backslashes appear
    No see also section
    
    Expected results:
    no backslashes
    a see also section
    
    Does this happen every time?
    Yes
    
    Other information:

On 2008-10-16 14:29:13 +0000, Claire Chardiny wrote:

    There is a mistake in my description.
    The generated documentation is :
    
     \
    
    This member function returns a character string specifying \ the name of the
    invoking object (if there is one).
    \ @
    
    See Also:
    
    @0#end() \ 

On 2008-10-16 14:38:42 +0000, Claire Chardiny wrote:

    See in attachement a pre.l file from an old Doxygen release
    (1.2.11-20011021)
    updated to accept documentation generated by a macro.
    Unfortunatly the pre.l file has chnaged a lot since. And I fail to report
    these changes in the pre.l of Doxyegn 1.5.6
    
    Thanks again fro your help!

On 2008-10-16 14:42:34 +0000, Claire Chardiny wrote:

    Created attachment 120717
    Updated pre.l file to accept documentation generated by macros (Doxygen
    1.2.11-20011021)
    
    A new variable has been defined:
    static bool g_inMacroDefineText = false; // true if parsing the define text
    of a macro
    Modified parts should be all embedded between @PATCHJPO and @@ENDPATCH

**Comment by albert-github** [comment]
We see 2 problems here in the doxygen 1.5.6 (with `MACRO_EXPANSION ==YES`) we see as output:
![image](https://github.com/user-attachments/assets/31afebee-e359-43cf-a3ca-dab6d5bff2f3)

and with the current 1.12.0 doxygen version:
![image](https://github.com/user-attachments/assets/5aa08b80-0a02-43e3-9863-4d5bf385493e)

so the backslashes are gone but an bug dot and an asterisk remain. 
This is due to the fact that actually the `\` is a line continuation sign and thus the next line is, completely, considered as part of the line.
This can be easily corrected by removing the initial `*` so the code will be:
```
#define ILOEXTENSIONHNONINLINE(hname) \
/** \
   <p>This member function returns a character string specifying \
   the name of the invoking object (if there is one).</p> \
    @@see @0#end() \
 */ \
  const char * getName() const; \
```
and the results are

**1.5.6**
![image](https://github.com/user-attachments/assets/932e3a47-2dc7-4bb1-8e13-97d99d789a88)


**1.12.0**
![image](https://github.com/user-attachments/assets/e46be674-880d-4bd4-8725-89540e58409b)


So I think the problem is a compination of solved in the mean time and usage.
