### ISSUE TITLE
Add multithreading when building documentation (Origin: bugzilla #574796)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3317]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-10 17:40:18 +0000, FranÃ§ois-Xavier ChoiniÃ¨re wrote:

    It takes 2 hours or mode to build our documentation.
    It will be really if we could set a -J option (like make or scons) to set
    how many process can run in doxygen.
    
    You could create a tree with all dependencies for each documentation
    outputs. Like that, all node could be run and build in an individial thread
    to accelerate documentation building.
    
    I know it's a lot of job.
    Thanks

On 2009-07-01 14:57:36 +0000, Andriy Golovnya wrote:

    I can confirm that this feature is needed. I have dual-core workstation on
    my desk and access to quad-core server. Running generation of doxymentation
    only with one thread on one CPU in my case is suboptimal. Doxygen could
    generate his output 2/4 times faster for me. I made some investigation and
    it's clear that HDD shouldn't be a limiting factor here.
    
    With new style of CPU design when chipmakes populate number of CPU
    cores/threads instead of rise number of MHz need of multi-CPU data
    processing is growing.
    
    Thanks!

On 2014-10-08 17:20:05 +0000, milasudril@gmail.com wrote:

    There may be problems with module inter-dependencies. I have an input filter
    for generating figure references and all reference counters are written to
    the same file. Luckily, doxygen is single-threaded so everything works
    without race conditions. Perhaps it is possible to parse more than one
    preprocessed file simultaneously.

**Comment by albert-github** [comment]
There are some features in the current doxygen version (1.9.7) regarding multi threading:
- `NUM_PROC_THREADS`
  > The NUM_PROC_THREADS specifies the number of threads doxygen is allowed to use
during processing. When set to 0 doxygen will based this on the number of cores available in the system.
You can set it explicitly to a value larger than 0 to get more control over the balance between CPU load and
processing speed. At this moment only the input processing can be done using multiple threads. Since this
is still an experimental feature the default is set to 1, which effectively disables parallel processing. Please
report any issues you encounter. Generating dot graphs in parallel is controlled by the DOT_NUM_THREADS
setting.
- `DOT_NUM_THREADS`
  > The DOT_NUM_THREADS specifies the number of dot invocations doxygen is allowed to
run in parallel. When set to 0 doxygen will base this on the number of processors available in the system. You
can set it explicitly to a value larger than 0 to get control over the balance between CPU load and processing
speed.

Furthermore there is also the possibility of the settings:
- GENERATE_TAGFILE
- TAGFILES

Seen the possibilities present I think the problem has been solved in the mean time.
