### ISSUE TITLE
Terms "Group" vs. "Module" (Origin: bugzilla #574911)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3319]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-11 10:00:41 +0000, Christian Treczoks wrote:

    While creating the sourcefile, the "grouping" commands use the term "group"
    for an aggregate of items (e.g. "\defgroup" or "\addtogroup"). In the
    output, these groups are called "modules" instead, which I consider
    unnecessary confusing.
    How about adding aliases for the functions with the term "module" instead of
    "group" (e.g. "\defmodule" as alias for "\defgroup")? I'd even go so far to
    suggest outphasing the "group" commands in the (far) future.
    
    Other information:

**Comment by albert-github** [comment]
In the current 1.9.8 doxygen version the term "Module" has bee replaced by "Topic" to make things more clear, the name of the commands has not changed but as written the user can easily do this by means of an `ALIASES` like `ALIASES += \defmodule=\defgroup` (and now `ALIASES += \deftopic=\defgroup`).

So the name confusion is hopefully solved in the mean time.
The renaming is, also because of consistency between versions of doxygen, not planned.
