### ISSUE TITLE
TYPEDEF_HIDES_STRUCT doesnt hide structs in specific C code (Origin: bugzilla #575259)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3326]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-13 15:18:10 +0000, Alexander wrote:

    I use packed structs with following syntax:
    
    typedef __packed struct _Name
    {
    ...
    } Name;
    
    Enabling TYPEDEF_HIDES_STRUCT doesnt hide such structs. Probably, the
    problem is in compiler-specific attribute format (__packed).

**Comment by albert-github** [comment]
The problem here will indeed be the `__packed` this is an unknown "type" for doxygen and should conditionally be `define`din the code or be listed in the setting `PREDEFINED`, see also the chapter Preprocessing in the manual (https://www.doxygen.nl/manual/preprocessing.html)

I think the problem is usage.
