### ISSUE TITLE
Preprocessor features ("ENABLE_PREPROCESSING", "MACRO_EXPANSION", etc) seem to do nothing (Origin: bugzilla #585696)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3422]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-06-14 00:01:15 +0000, David Kobe wrote:

    Please describe the problem:
    I have not been able to get doxygen's preprocessor to expand macros.
    
    Steps to reproduce:
    1. Configure doxygen with default settings except the following:
    INPUT=the two files listed below
    SOURCE_BROWSER=YES
    MACRO_EXPANSION=YES
    2. Run doxygen
    3. Examine HTML output for "doxygen_test.c" and look for MY_MACRO.
    
    
    Actual results:
    Macro does not appear to be expanded.  Same test can be run with
    PREDEFINED=MY_MACRO= with no difference in output.  Settings for
    EXPAND_ONLY_PREDEF don't seem to have any impact either.
    
    Expected results:
    I would expect MY_MACRO to be replaced with its expansion.
    
    Does this happen every time?
    Yes
    
    Other information:
    use the following for "doxygen_test.h":
    
    #ifndef DOXYGEN_TEST_H_
    #define DOXYGEN_TEST_H_
    
    #define MY_MACRO   10
    
    #endif /*DOXYGEN_TEST_H_*/
    
    
    Use the following for "doxygen_test.c"
    
    #include "doxygen_test.h"
    
    int main()
    {
        int x = MY_MACRO;
        
        x=x+1;
        
        return x;
    }

**Comment by albert-github** [comment]
It is a bit unclear where the replacement of the `MY_MACRO` should be shown.
We see the `MY_MACRO` in the following files:
- html/doxygen__test_8h.html
  The documentation of the macro and here it is (and should be) shown as:
  ![image](https://user-images.githubusercontent.com/5223533/168642921-e7a5bd5d-7aff-4142-8ddf-f2cc13522958.png)
- html/doxygen__test_8h_source.html
  The code of the `.h` file, and here it is (and should be) shown as it is defined:
  ![image](https://user-images.githubusercontent.com/5223533/168643099-6a475305-d319-4789-9611-0a4538383e9f.png)
- html/doxygen__test_8c_source.html
  The code of the `.c` file, here the `MY_MACRO` is used. The source code is shown as it is thus:
  ![image](https://user-images.githubusercontent.com/5223533/168643817-1291b87c-e573-45f5-83e9-4db60cac95bb.png)


Note that when we would define a global variable in the `.c` file like:
```
int g_x = MY_MACRO;
```
This would result in the documentation of `g_x`, file html/doxygen__test_8c.html as:
![image](https://user-images.githubusercontent.com/5223533/168644280-b9028c60-e1ba-4bda-9c3e-8c2ff94cb8f6.png)

but in the source file (html/doxygen__test_8c_source.html) it would still look like:
![image](https://user-images.githubusercontent.com/5223533/168644452-b24469f1-7091-4988-8625-2e39f4c5dc08.png)


I think the problem is usage.
