### ISSUE TITLE
Generic names causes nameconflicts when installing multiple packages (Origin: bugzilla #585991)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3428]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-06-16 14:38:48 +0000, Tom Fredrik Klaussen wrote:

    I am one of the maintainers of the Coin3D visualization library.
    
    We have gotten a report from Debian maintainer Steve M. Robbins, which reads
    
    <quote>
    A Debian user reported the following bug. Basically, the issue is 
    that Coin generates a manpage "deprecated.3", which is also used by 
    another package. 
    
    This name is quite generic; would it be possible to generate 
    something like "CoinDeprecated", or the like?
    </quote>
    
    It would be really nice to be able to have two options available.
    
    1. The option to prefix all manpages generated with some common prefix, eg.
    Coin.
    2. The option to prefix generic pages like "deprecated" with a prefix.

**Comment by albert-github** [comment]
The file naming for man pages always will be a problem with generic names. The problem is also when names are given how will the user remember them.
Doxygen has the possibility to set the `MAN_EXTENSION` which will be used in the directory name and the file name.
E.g. setting `MAN_EXTENSION=.3coin` in the doxygen configuration file would give the directory: `man/man3coin`  and the file `deprecated.3coin`.

With the setting of the `MANPATH` and, when necessary, the `MANSECT` environment variables the user can steer the pages to look in (see the avaialble help on e.g. the commands `man` and `manpath` on your system).

I think the problem is usage.


Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/7713750/example.tar.gz)
