### ISSUE TITLE
Group page: Classes not listed alphabetically (Origin: bugzilla #598074)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3558]
status NEW severity *minor* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-10-11 13:05:46 +0000, Marc Zinnschlag wrote:

    The widget list in the gtkmm documentation is not sorted correctly (assuming
    an alphabetical sorting was intended).
    
    Example:
    
    http://library.gnome.org/devel/gtkmm/unstable/group__Widgets.html
    
    See classes Gtk::VRuler and Gtk::HRuler.

On 2009-10-28 15:45:00 +0000, Johannes Schmid wrote:

    Well, this seems to be on purpose and makes sense to have VRuler and HRuler
    (which are subclasses of Ruler) near their base, same for Scrollbar, etc.
    
    The only thing which is wrong is the sorting of ComboBoxEntryText,
    ComboBoxText and ListViewText at the end of the list. I couldn't find out
    where this order is set.

On 2009-10-28 19:31:04 +0000, Marc Zinnschlag wrote:

    Regarding the VRuler/HRuler: I can see your point, but is that really the
    right decision? I would expect an average user to search under V instead of
    R when looking for VRuler. Placing it under R expresses the underlying class
    structure, but seems rather unintuitive.

On 2009-11-27 13:51:53 +0000, Murray Cumming wrote:

    I don't think any of the current sorting is at all intentional. I too would
    like it to be purely alphabetical.

On 2010-04-07 13:13:29 +0000, Murray Cumming wrote:

    As far as I can tell, there is no way to explicitly state that the classes
    in the groups should be sorted alphabetically. So I'm reassigning this to
    Doxygen.

**Comment by albert-github** [comment]
The mentioned page (http://library.gnome.org/devel/gtkmm/unstable/group__Widgets.html) is still reachable but it is doubtful that it is generated with doxygen and also that it is a recent page (seen the copyright notice: Copyright © 2005‒2014 The GNOME Project). 
On the page there is no reference to VRuler or Hruler.

Due to a missing example it is not possible to say anything sensible about the problem. Note theer exists for groups the setting `SORT_GROUP_NAMES (sin version 1.5.5, February 10 2008).

I think the problem is incomplete.
