### ISSUE TITLE
Doxygen treats C++/CLI keywords as special in normal C++ (Origin: bugzilla #604602)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3611]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-12-15 08:51:30 +0000, Neil Bird wrote:

    Doxygen is treating the C++/CLI keyword 'abstract' (and others, presumably)
    as a keyword in normal C++, even with 'CPP_CLI_SUPPORT' set to 'NO';  this
    can cause fictitious warnings when, e.g., variables and types are defined
    that use this name.
    
    In my case, 'asbtract' is the name of a typedef, but note that it doesn't
    (for me) seem to be causing a noticeable problem with the generated HTML, it
    just gives an odd warning during the run.

On 2012-11-18 11:08:07 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
Based on the description I tried to create a small example
```
/// \file

/// the normal typedef
typedef unsigned long ulong;

/// the special typedef
typedef int abstract;

/// the super-special typedef
typedef unsigned abstract uabs;
```
though with this example I was not able to get a warning (with the 1.6.1 / 1.6.1 version i.e the versins current at the moment of writing the issue).

I did see that the word "abstract" is seen as a keyword in the code (`SOURCE_BROWSER=YES`) though with the current 1.9.6 version the word "abstract" is shown as a link as it should be.

I think the issue is incomplete / solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10372764/example.tar.gz)
