### ISSUE TITLE
WARN_FORMAT tag template body able to handle XML tags (Origin: bugzilla #616937)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3749]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-04-27 11:46:41 +0000, Rob Schofield wrote:

    Similar to bug # 490149, the use of XML tags to coerce warning text output
    into XML output results in odd behaviour (see the reported output in #
    490149).
    
    If WARN_FORMAT was a free-form template with only $delimited substitutions
    embedded in the template string, this would greatly enhance the utility of
    this tag.
    
    Similarly, the ability to insert a header into the output stream to prefix
    the warning output would allow for the use of CSS template tags in HTML
    output, and DTD/XSML schema choice in XML output.

**Comment by albert-github** [comment]
Seen the code in https://github.com/doxygen/doxygen/issues/5069and the report in https://github.com/doxygen/doxygen/issues/2686 doing a small test reveals that in the 1.5.3 version there is a problem with the HTML tags as only the first line is properly fet in teh warning format. This was already fixed in 1.8.7

I think the problem has been solved in the mean time.
