### ISSUE TITLE
syntax error on conditional directive spanning multiple lines (Origin: bugzilla #622737)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3824]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[ttp.zip](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug622737_164627_ttp.zip)_ (ID 164627)

On 2010-06-25 14:48:25 +0000, Timothy Madden wrote:

> Processing conditional directives on multiple lines produces warnings that end with "syntax error". Boost library header files contain many such conditionals.
> 
> Trying to process the following file:
> 
> #if !defined(BOOST_MPL_CFG_NO_TEMPLATE_TEMPLATE_PARAMETERS) \
>     && ( defined(BOOST_NO_TEMPLATE_TEMPLATES) \
>       || BOOST_WORKAROUND( __BORLANDC__, BOOST_TESTED_AT( 0x590) ) \
>        )
> 
> #   define BOOST_MPL_CFG_NO_TEMPLATE_TEMPLATE_PARAMETERS
> 
> #endif
> 
> will output
> 
> "D:/Local/Projects/ss/ttp.hpp(5) : warning: preprocessing issue while doing constant expression evaluation: syntax error"
> 
> 
> Attached are the simple source file, with the Doxyfile and the generated output

On 2010-06-25 14:49:23 +0000, Timothy Madden wrote:

> Created attachment 164627
> Sample source, doxyfile, output

On 2010-07-10 18:48:08 +0000, Dimitri van Heesch wrote:

> Confirmed. Should be fixed in the next subversion update.
> 
> As a workaround you can set the following:
> 
> ENABLE_PREPROCESSING   = YES
> MACRO_EXPANSION        = YES
> EXPAND_ONLY_PREDEF     = YES
> PREDEFINED             = BOOST_WORKAROUND(x,y)=0

On 2010-10-09 08:19:50 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.7.2. Please verify if this is indeed the case. Reopen the
> bug if you think it is not fixed and please include any additional information
> that you think can be relevant.

**Comment by doxyusingmaik** [comment]
With doxygen 1.8.13 the problem is still present. Depending on which build-essential package Version you installed, there can be a preprocessor macro spanning about two lines 
in /usr/include/string.h:164

If it's looking like this, it creates the same error message:
_____________________ cut _______________________
#if (defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8	\
     || __GLIBC_USE (LIB_EXT2))
_____________________ cut _______________________

The "PREDEFINED = __GLIBC_USE (LIB_EXT2))=0" workaround can't help here :-(

Can not see, why this only happens to some computers. All have
doxygen -v
"1.8.13"
"gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)"
and "build-essential/bionic,now 12.4ubuntu1 amd64 [installed]"

all using the same doxy project setup with
ENABLE_PREPROCESSING = YES
PREDEFINED           = DOXYGEN_SHOULD_SKIP_THIS
MACRO_EXPANSION      = YES
EXPAND_ONLY_PREDEF   = YES
EXCLUDE_PATTERNS     = */export/*
