### ISSUE TITLE
The doxygen -u command should not change "+=" to "=" when updating configuration file (Origin: bugzilla #625811)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3884]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-08-02 09:40:47 +0000, Kjell Arne Hvilsten wrote:

    Is it possible for doxygen to NOT replace the "+=" with "="?

**Comment by albert-github** [comment]
This is not possible due to the design of the `doxygen -u`. The old file is read and at that moment the information about whether `+=`  is used or the values are entered by means of a continution line (or even on one line) is lost.

I don't think this is a bug and otherwise something that won't be fixed.
