### ISSUE TITLE
File References do not show to what Module they belong (Origin: bugzilla #635250)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4025]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-11-19 08:37:17 +0000, Frank van Heesch wrote:

    Documentation for classes and namespaces show to what group they belong, but
    Modules don't. Could this be added?

**Comment by albert-github** [comment]
It is a bit unclear what is meant here as at the moment of writing groups where shown as modules (the C++ modules were introduced in C++-20). As a side note nowadays modules are called topics in doxygen.
It is also clear whether we have here an issue for C== or for another language.

I think the issue is incomplete.
