### ISSUE TITLE
SHOW_FILES = NO also disables call graph and caller graph generation. (Origin: bugzilla #636687)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4039]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyfileNO](https://sourceforge.net/projects/doxygen/files/attachments/bug636687_175998_DoxyfileNO/download/download)_ (ID 175998)
- _[DoxyfileYES](https://sourceforge.net/projects/doxygen/files/attachments/bug636687_175999_DoxyfileYES/download/download)_ (ID 175999)

On 2010-12-07 10:48:55 +0000, Bartlomiej Antoni Szymczak wrote:

    Created attachment 175998
    SHOW_FILES = NO
    
    Setting
    
    SHOW_FILES = NO
    
    also disables call graph and caller graph generation.
    Compare the two attached Doxyfiles. They differ only with respect to
    SHOW_FILES, yet one generates call graphs and the other doesn't.
    
    Expected result:
    Clearly one should get call graphs in "class documentation" even without
    "files documentation".

On 2010-12-07 10:50:04 +0000, Bartlomiej Antoni Szymczak wrote:

    Created attachment 175999
    SHOW_FILES = YES

**Comment by albert-github** [comment]
After a number of attempts, due to the missing source code, I've been able to reproduce the problem in the 1.7.2 version. In case a class is defined in a cpp file and `SHOW_FILES=NO` the call / caller graphs are missing.

When running the same problem in version 1.9.1 the call / caller graphs are shown irrespective of the setting of `SHOW_FILES`.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/6902236/example.tar.gz)

I think the problem has been solved in the mean time.
