### ISSUE TITLE
Double title/body closing on server search page (Origin: bugzilla #640925)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4125]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-search-double-title-and-closing.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug640925_179619_doxygen-search-double-title-and-closing.patch/download/download)_ (ID 179619)

On 2011-01-30 01:24:04 +0000, Haffmans wrote:

    Created attachment 179619
    Fix wrong output of server-side search page
    
    The search page for the server-side search (that's search.php) writes the
    default title area also when a custom header file is used. Other pages
    generated by Doxygen do not do so.
    
    Additionally, the same page has body/html closing tags, before the actual
    footer.
    
    Attached patch:
    * Writes the title area only if the default Doxygen header is used
    * Removes the end_page() PHP function from the search.php file

On 2012-11-18 11:07:05 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
This issue is, unfortunately, quite old and since 2011 quite a lot has changed regarding the handling of the HTML output.
The file `seatrch_php.h` doesn't exist anymore and also the function `end_page`  is nowhere present
There haven't been problems reported against recent versions.

I think the problem has been solved in the mean time.
