### ISSUE TITLE
generated html tags for method groups are inconsistent (Origin: bugzilla #652419)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4300]
status NEW severity *minor* in component *documentation* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-06-13 00:47:13 +0000, Jonathan Sand wrote:

    +++ This bug was initially created as a clone of Bug # 652418 +++
    
    I'm using objective-c and create some method groups using the following
    syntax:
    
    
    /// \name methodGroupName
    /// \{
    
    - (void)methodName { ... }
    
    /// \}
    /// \name anotherMethodGroupName
    /// \{
    
    - (void)anotherMethodName { ... }
    
    /// \}
    
    In the generated documentation, when I look at the HTML code,
    methodGroupName is enclosed in a <div class="groupHeader"> tag and
    anotherMethodGroupName is enclosed in an <h3> tag. This happens in many of
    my class' generated documentation, but not all. In the HTML pages, the
    groupHeader items are indented and the h3 are not, so it looks
    unprofessional to my peers.

**Comment by albert-github** [comment]
I tried to reproduce the problem, but with the version 1.7.4 version (and also other older version tried) I see for `methodGroupName` and for `anotherMethodGroupName` always a `<div class="groupHeader">` and never a `<h3>` tag (h3 only appears in the `doxygen.css`).

So the problem is, for me, not reproducible.
