### ISSUE TITLE
Class information is missing in the documentation for some files (Origin: bugzilla #667335)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4523]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[BitInOutKit_Doc.pdf](https://sourceforge.net/projects/doxygen/files/attachments/bug667335_204664_BitInOutKit_Doc.pdf/download/download)_ (ID 204664)
- _[BitInOutKit_Source.pdf](https://sourceforge.net/projects/doxygen/files/attachments/bug667335_204665_BitInOutKit_Source.pdf/download/download)_ (ID 204665)

On 2012-01-05 06:38:26 +0000, Anil Choudhury wrote:

    Created attachment 204664
    Doxygen documentation
    
    Hi,
    
    I have used doxygen to process a big project.
    
    In many files i found that it has not generated the class information even
    if class is present in those files.
    
    
    I have attached the source code of the file shown in doxygen and the
    generated documentation of the same.

On 2012-01-05 06:39:55 +0000, Anil Choudhury wrote:

    Created attachment 204665
    Related source code

**Comment by albert-github** [comment]
The information:
> In many files i found that it has not generated the class information even
if class is present in those files.

is a bit vague. 
After cutting out the source code from the pdf files attached to the issue and running it with 1.7.6.1 or 1.8.20 and a default doxygen configuration file we see no class information.

Looking in the h file we see the guard:
```
#ifdef BIT_IN_OUT_MODULE_USED
```
 and when the file `BitInOutConfig.h` is not included or `BIT_IN_OUT_MODULE_USED` is not defined in another way the information is correct (don't look into the guarded block.
When defining `BIT_IN_OUT_MODULE_USED` the information about the class is shown.

I think the problem is usage

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5736628/example.tar.gz)
