### ISSUE TITLE
Doxygen loads insecure content from http uri (when hosting on https) (Origin: bugzilla #679025)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4775]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-06-28 08:13:10 +0000, Jerry Jacobs wrote:

    Doxygen has a minor issue that google chrome complains about the secureness
    of the website (generated by doxygen). Because it is loading from a https
    site content from a external http site.
    
    It would be nice that doxygen packs all the dependencies and resources. And
    it could be noticed inside the template configuration file that this is a
    "security problem" which can result in XSS.
    
    I think this is in my setup because of the mathjax renderer.
    
    Further reading:
    https://support.google.com/chrome/bin/answer.py?hl=en&answer=1342714

**Comment by albert-github** [comment]
It is a bit unclear which website is meant (doxygen's own or a user generated). 
The doxygen website doesn't use MathJax, so no loading for the formuals
When it is the users own generated site, nowadays doxygen gets by default   Mathjax from either https://cdn.jsdelivr.net/npm/mathjax@2 or https://cdn.jsdelivr.net/npm/mathjax@3

So either the issue is unclear / incomplete or solved in the mean time.
