### ISSUE TITLE
Manual @link inside @param and @throws (Origin: bugzilla #684223)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4889]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-09-17 14:38:57 +0000, Bruno Augusto wrote:

    Hi,
    
    I think there are two different, although related, bugs when manually adding
    hyperlinks in @param and @throws, at least when documenting PHP doc blocks.
    
    This block:
    
    /**
     * @brief Set Request Object
     *
     * Sets the Request Object used by Application
     *
     * @param    @link HTTP::Request @endlink    $request
     *   Request Object
     *
     * @return   @link Application::Application @endlink
     *   Application Instance (Fluent Interface)
     */
    
    Will Produce:
    
    Parameters
      @link	HTTP::Request $request Request Object
    
    Instead of:
    
    Parameters
      $request <a>HTTP::Request</a> Request Object
    
    * Considering <a> as the related link markup.
    
    Also, by doing this, I receive 3 Warnings:
    
    - Argument 'link' of @param is not found
    - Unexpected command endlink
    - The following parameters of CLASS_NAME_HERE are not documented
    
    If I list $request BEFORE @link, works fine. However this work around should
    not be used because $request is not a Type.
    
    Second problem, also related. This block:
    
    /**
     * @throws
     *
     *   @link MyException @endlink
     *
     *   Thrown if:
     *
     *  - Condition # 1
     *
     *  - Condition # 2
     */
    
    Works, but produces a warning: "expected whitespace after throws command",
    which I don't think is correct.

**Comment by albert-github** [comment]
As written there are 2 issues in this report:
- `\param` this command needs a name as first argument and a `@link` is not an argument (of the function). As there is no complete example it is hard to guess what was intended. The fact that one gets multiple warnings is due to the fact that an attempt is made to check `@link` as parameter name, which fails, but afterwards the rest does not make sense either (for doxygen). I think this problem is usage.
- `\throws` this command needs as first argument a so called exception object which is not present but in fact there is a paragraph delimiting (the empty line). I think the problem is usage.
