### ISSUE TITLE
\ref member group support (Origin: bugzilla #691282)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5018]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-01-07 11:35:59 +0000, Domagoj Å ariÄ wrote:

    Please add the ability to create links/references to member groups.

**Comment by albert-github** [comment]
It is not clear what is meant here with "member groups" in the different file pages there are groups like "Classes", "Macros", "Namespaces and they can be reached it that page by means of the local tag like "nested-classes", "define-members", "namespaces" but these are defined for each page as local to the page so quite hard to refer to from the outside.

I think the issue is incomplete.
