### ISSUE TITLE
C: Backslashes inside macro definitions not handled correctly (Origin: bugzilla #695168)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5108]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[mwe.c](https://sourceforge.net/projects/doxygen/files/attachments/bug695168_238062_mwe.c/download/download)_ (ID 238062)

On 2013-03-04 23:47:17 +0000, AmenophisIII@gmx.at wrote:

    I am using doxygen 1.7.6.1 as packaged in ubuntu 12.04.
    
    When backslashes are used inside macro definitions as described in the
    second case in the attached mwe.c doxygen should remove the backslashes (and
    leading asterisks) from its output IMHO.
    There is no way around adding the backslashes in such definitions when one
    wants to break the lines apart because a normal line break ends the macro
    definition. And IMHO the given example is a legit but maybe uncommon use
    case (think of a library that generates a number of similar functions for
    its API that way and wants to provide documentation for it).
    
    You can compile the example with the following command line:
    
    echo 'ENABLE_PREPROCESSING   = YES
    MACRO_EXPANSION        = YES
    EXPAND_AS_DEFINED      = FUNC
    EXCLUDE_SYMBOLS        = FUNC
    GENERATE_LATEX         = NO' | doxygen -

On 2013-03-04 23:47:51 +0000, AmenophisIII@gmx.at wrote:

    Created attachment 238062
    mwe

On 2013-03-05 00:26:14 +0000, Kevin McBride wrote:

    Did you try to use the latest version of doxygen?  1.8.3.1 is the latest
    version, and the latest version is most of the time the only supported
    version of doxygen on this bugzilla.
    
    NOTE: I do not have a second computer to test this bug.  As a result, I am
    not changing this bug's status at this time.

On 2013-03-05 00:49:19 +0000, AmenophisIII@gmx.at wrote:

    No I did not, but that's why I have spent some time creating the MWE for
    testing this easily ;) Even if it is fixed in current HEAD it is a good idea
    to document it in this tracker IMHO (so people know that there was a change
    in behavior and can upgrade without wasting their time).

**Comment by albert-github** [comment]
In version 1.7.6.1 I see that the backslash is present in the output:
`some comments to document the generated code including\ * the parametrized type int but with backslashes that are\ * needed for the C preprocessor. `
in version 1.8.14 these backslashes are gone:
`some comments to document the generated code including * the parametrized type int but with backslashes that are * needed for the C preprocessor. `

Note that there are asterisks (`*`) in the output due to the form of the define:
```
#define FUNC(arg_type)\
/** some comments to document the generated code including\
 * the parametrized type arg_type but with backslashes that are\
 * needed for the C preprocessor. */\
arg_type funcname(arg_type arg) {\
        return arg;\
}
```

but this is normal preprocessor behavior as the define is converted to 1 line without interpretation, so a better formulation, in this case, would be:
```
#define FUNC(arg_type)\
/** some comments to document the generated code including\
   the parametrized type arg_type but with backslashes that are\
   needed for the C preprocessor. */\
arg_type funcname(arg_type arg) {\
        return arg;\
}
```

I think the problem has been solved in the mean time.
