### ISSUE TITLE
Not a HASH reference at perlmod/doxylatex.pl line 19. (Origin: bugzilla #695490)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5120]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-03-09 12:25:33 +0000, anonymouspass wrote:

    Not a HASH reference at perlmod/doxylatex.pl line 19.
    
    the fix is to add this before line 19
    
            if( 'ARRAY' eq ref $item ){
                generate_doc( $item );
                next;
            }

**Comment by albert-github** [comment]
I checked with the example from #4723 and the 1.8.3.1 version and here we see that the `make pdf` in the perlmod direcvory gives an error at the mentioned place.
In the 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) this problem does not occur anymore although the `doxylatex.pl` and this is due to the fact that the structure of the `DoxyDocs.pm` has been improved.

I think the underlying problem has been solved in the mean time and this fix should not be applied.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/8059845/example.tar.gz)
