### ISSUE TITLE
(C++) Class names in different namespaces not distinguished when generating class diagram (Origin: bugzilla #706968)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5276]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-08-28 12:10:27 +0000, MikoÅaj MaÅecki wrote:

    I happen to have two classes, that have exactly the same names, although in
    different namespaces. Let's say something like:
    
    namespace gen {
    namespace first { class MyClass: public Something { ... }; }
    namespace second { class MyClass: public gen::first::MyClass { ... }; }
    }
    
    In the "class" list I can see two items mentioning two identical class
    names, although they properly lead to these two separate classes.
    
    However the diagram of gen::second::MyClass shows as if MyClass "derived
    itself" (impossible in C++). That is, it doesn't show the base class being
    gen::first::MyClass, as it should, with a link leading to this base class.
    
    Moreover, the diagram for gen::first::MyClass ALSO shows as if it "derived
    itself", not even showing that this class derives "Something".

**Comment by albert-github** [comment]
We have 2 problems mentioned here:
>However the diagram of gen::second::MyClass shows as if MyClass "derived
itself" (impossible in C++). That is, it doesn't show the base class being
gen::first::MyClass, as it should, with a link leading to this base class.

It is a bit unclear what the problem is as with a simple `Doxyfile:
```
QUIET=YES
EXTRACT_ALL=YES
```
everything is OK in the 1.7.6.1 version as well as in the current version (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)).
The only thing to see this "recursive" relation is when using:
```
HIDE_SCOPE_NAMES=YES
```
but due to a missing settings file this is not clear.

>Moreover, the diagram for gen::first::MyClass ALSO shows as if it "derived
itself", not even showing that this class derives "Something".

In the 1.7.6.1 version the reference to "Something" is missing, in the current version (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) this reference is present.

I think the problems are a mix of usage and solved in the mean time.
