### ISSUE TITLE
Different values for CREATE_SUBDIRS breaks TAGFILES generated links (Origin: bugzilla #721832)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5395]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-01-08 22:00:37 +0000, John Bendig wrote:

    If I have two projects which I cross-link through tagfiles, and have the one
    project configured with CREATE_SUBDIRS=NO, and the other configured with
    CREATE_SUBDIRS=YES, the links between the projects are broken.
    
    Hereâs a more detailed description:
    
    The âtargetâ project is configured with CREATE_SUBDIRS=YES and
    GENERATE_TAGFILE to a filename.  It defines several pages.  The tagfile
    generated looks great, with all the subdirectories in the <filename> and
    <docanchor> tags.  I build this project first.
    
    The âsourceâ project is configured with CREATE_SUBDIRS=NO and TAGFILES
    pointing to the target tagfile.  It has @subpage links to the pages defined
    in the target.  When doxygen builds the source project, it strips all the
    subdirectories out of the URL to the target pages.  If I have both projects
    set to CREATE_SUBDIRS=YES, or both set to CREATE_SUBDIRS=NO, then it all
    works fine.  It even fails if I have the target set to NO and the source set
    to YES.  In that case doxygen adds subdirectories to the target URLs.

**Comment by sawatts** [comment]
I don't know if this is related - but we have a set of projects which build and publish their docs and their tag files, while cross-linking using the existing published tag files.

Just noticed that when a project is rebuilt, links from dependant projects are broken.  I do not see why this should be the case where the target symbol has not changed.

For example, the link from **Project-B** to an external class is `../../../project-a/dc/d50/a53053.html`, while the page in Project-A is now at `../../../project-a/d8/d12/a52781.html`.  The symbol has not changed its fully-qualified name.  I would have expected some strategy for consistent URLs for API elements - unless I have missed some configuration option?

This is **Doxygen** 1.8.15 on x86_64 linux (RHEL).  We have a large number of build nodes on our Jenkins configuration where the documentation could be generated.

**Comment by albert-github** [comment]
@sawatts I only looked at your description, not yet to the original case.

It kooks like you are using the so called `SHORT_NAMES=YES` and they don't look like static between builds with a different number of files.
In the file `util.cpp` I see:
```
    static QDict<int> usedNames(10007);
    usedNames.setAutoDelete(TRUE);
    static int count=1;

    int *value=usedNames.find(name);
    int num;
    if (value==0)
    {
      usedNames.insert(name,new int(count));
      num = count++;
    }
    else
    {
      num = *value;
    }
    result.sprintf("a%05d",num);
```

So when you first build Project-B (with the old tag file of Project-A) and afterwards rebuild Project-A you might run into problems.

Maybe you can do some tests to see what happens:
- don't use `SHORT_NAMES` i.e. use `SHORT_NAMES=NO`
or
- first build Project-A and afterwards Project-B

**Comment by sawatts** [comment]
@albert-github Yes! We indeed have `SHORT_NAMES=YES` in the build framework.  I will change it immediately and see how it goes as things get rebuilt.  Thanks.

**Comment by sawatts** [comment]
With `SHORT_NAMES=YES` we are now seeing cross-links persisting after the target doc-set is rebuilt.

Interestingly, and unexpectedly, we also see derived classes shown in class diagrams when the doc-set for the base class is rebuilt.  This is probably because we pass the tags for all published docs to doxygen when building, not filtering for known dependencies.  However we rather like this and probably won't change unless there is a problem (possibly when the doc set collection gets much larger?).

**Comment by albert-github** [comment]
I could reproduce the original problem with doxygen 1.8.3.1, with 1.9.2 the problem was gone.
Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/7670247/example.tar.gz)


The problem regarding `SHORT_NAMES` I was not able t reproduce, when this is still a problem please submit a new issue for this.

Seen the original problem I think the problem has been solved in the mean time
