### ISSUE TITLE
'sealed' c++ classes are misnamed (Origin: bugzilla #725183)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5429]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[testdoxy.h](https://sourceforge.net/projects/doxygen/files/attachments/bug725183_270340_testdoxy.h/download/download)_ (ID 270340)

On 2014-02-26 00:18:49 +0000, Mike Lanzetta wrote:

    Created attachment 270340
    Header containing class that generates incorrect name.
    
    Classes marked 'sealed' have the name 'sealed' instead of their actual name
    used.  This is odd, since sealed methods don't have the same issue.
    
    For instance:
    
    public ref class MySealed sealed
    {
    public:
    	MySealed()
    	{
    	}
    
    	virtual void SealedMethod() sealed {}
    };
    
    Generates the "class" 'sealed' instead of MySealed, but that class has the
    SealedMethod method.

**Comment by albert-github** [comment]
The given code looks like "C++/CLI" code and in the settings we see:
> CPP_CLI_SUPPORT If you use Microsoft's C++/CLI language, you should set this option to YES to enable parsing support.
> The default value is: NO.

Without this setting we see indeed "sealed" as classname, using `CPP_CLI_SUPPORT=YES` we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/1bad8844-5873-4d5c-967c-c45ebc7a0f82)

tested with doxygen 1.8.6 (and the current doxygen version 1.9.7)

I think the problem was usage.
