### ISSUE TITLE
Different Static Functions With Same Name Confusion. (Origin: bugzilla #728026)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5448]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-04-11 09:58:17 +0000, jctout wrote:

    Hello,
    In C language, different static functions with same name seems to be
    identified as same function by Doxygen and so, cannot handle them in
    call/caller graphs (truncated).
    Many thanks for coop.
    Best regards,
    JC

On 2014-04-12 11:47:21 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

**Comment by albert-github** [comment]
I tried to reproduce the problem with the following example:

File `aa.cpp`:
```
/// \file


/// First fie
/// \details Some details
void fie1()
{
   st_fie();
}


/// static first fie
/// \details Some details
static void st_fie()
{
}
```
and file `aa2.cpp`:
```
/// \file


/// second fie
/// \details Some details
void fie2()
{
   st_fie();
}


/// static second fie
/// \details Some details
static void st_fie()
{
}
```
and settings:
```
EXTRACT_STATIC=YES
QUIET=YES
CALL_GRAPH=YES
CALLER_GRAPH=YES
HAVE_DOT=YES
SOURCE_BROWSER=YES
STRIP_CODE_COMMENTS=YES
```

but with version 1.8.2 as well as with version 1.9.1 it looks to me that links are all correct.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5867227/example.tar.gz)

Seen the fact that it is not reproducible and no example has been provided I think the problem is incomplete.
