### ISSUE TITLE
Ordered groups in collaboration diagram (Origin: bugzilla #733294)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5519]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-07-17 05:55:30 +0000, christophe.jaillet@wanadoo.fr wrote:

    Hi,
    
    when SORT_GROUP_NAMES is set to YES, group names are alphabetical ordered in
    the left navigation tree.
    
    However, I would also have expected them to be ordered in the collaboration
    diagram. (i.e GROUP_GRAPHS).
    I didn't find any option for it, but it would be usefull, especially when
    big graphs are generated.
    
    
    Best regards.

**Comment by albert-github** [comment]
Unfortunately there is no example with the issue.

A small test ([example.tar.gz](https://github.com/user-attachments/files/16910799/example.tar.gz)) shows that the groups are sorted in the Collaboration graph independent of the setting of `SORT_GROUP_NAMES`.
It is possible that with larger graphs the sorting looks like to be "unsorted" but this might also be due to the fact the the `dot` tool has its own rules about placing the elements.

Without an example isn't is not possible to reproduce the problem and the problem has to be set to incomplete.
