### ISSUE TITLE
Navigation incorrect with escaped symbols (Origin: bugzilla #748927)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5783]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygenbug_nav.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug748927_302912_doxygenbug_nav.zip/download/download)_ (ID 302912)

On 2015-05-05 07:15:58 +0000, Jeroen Van Antwerpen wrote:

    Created attachment 302912
    Reproduction scenario
    
    When using special symbols (escaped) in page titles, the generated
    navigation of subpages does not convert these characters to their correct
    HTML Entities.
    As a result, these pages are no valid xhtml.
    
    In the example (see attachement), I've created a page with the title
    '\<my\>-tag' (bug_pagetitle.dox),
    which results in the following code of the navigation for bug_valid.dox:
    <li class="navelem"><a class="el"
    href="_i_n_v_a_l_i_d__t_i_t_l_e.xhtml">\<my\>-tag</a></li>
    
    Tested on: Windows 7
    Workaround: Replaced <my> by &lt;my&gt; in the source.

**Comment by albert-github** [comment]
This is a bit of a special situation. The problem is shown in the "doxygen bars" on top of the page of 'html/_v_a_l_i_d__t_i_t_l_e.xhtml' (independent of html or xhtml).
![image](https://user-images.githubusercontent.com/5223533/43972776-d414a2b8-9cd5-11e8-889e-3045d214b21d.png)

The problem is that the title of a page isn't processed (as "nothing" can be, generically, handled in the title of a page)

I've just pushed a proposed patch, pull request #6439

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
