### ISSUE TITLE
The @ character from a section title disappear when including a reference of said title (Origin: bugzilla #753496)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5838]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-08-11 08:55:39 +0000, Alexis Wilke wrote:

    I have documentation which defines a large number of sections. Very
    practical for having a table of content.
    
    The table of content properly displays the section names.
    
    However, references remove the introducer in that one page because the names
    include / start with the '@' (at, ampersand) character.
    
    /** \brief Some doc...
     *
     * \section at_mixin @mixin \<identifer> { ... }
     *
     * some info here...
     *
     * \section at_return @return \<expression>
     *
     * some info here... \ref at_mixin
     *
     */
    
    The result of the \ref at_mixin is just:
    
    \<identifier> { ... }
    
    The '@mixin' itself gets removed (wrongly interpreted).
    
    Just in case I tried to add ONE backslash. That did not help in any way. The
    title appears as expected, but the reference is still broken.
    
     * \section at_mixin \@mixin \<identifer> { ... } -- no difference
    
    I also tried with TWO backslashes in front of the @ in the section title.
    That worked as expected for the reference, but broke the normal title and
    table of contents.
    
     * \section at_mixin \\@mixin \<identifer> { ... } -- breaks title & TOC
    
    One way I was able to circumvent the issue is by specifying the text of the
    reference as in:
    
     * See also: \ref at_include "\@include"
    
    I still think that '\ref at_include' should work as is.
    
    The full page concerned can be found in a GIT on SourceForge.net here:
    
    https://sourceforge.net/p/snapcpp/code/ci/master/tree/csspp/doc/pages/
    
    The file is:
    
    compiler-at-keywords.cpp
    
    Other pages do not include the @ in their title.
    
    The current public version of the page is visible here:
    
    http://csspp.org/documentation/csspp-doc-1.0/at_keywords.html

**Comment by albert-github** [comment]
I don't completely get the problem here.
Some of the links are dead but I found the GitHub repository at https://github.com/m2osw/csspp. I tried to build the documentation here but due to the fact that I don't have have all prerequisites the `cmake ..` does not complete so I took the files from the `doc` directory and with some small modifications I was able to  build the documentation with a number of warnings.

In respect to the mentioned problem, with the current version 1.8.15 I do see the  `@` sign, but we still get 2 messages regarding:
```
csspp/doc/pages/compiler-at-keywords.cpp:244: warning: Found unknown command `\mixin'
csspp/doc/pages/compiler-at-keywords.cpp:244: warning: Unsupported xml/html tag <identifer> found
```

I think these can be overcome by means of replacing the `@` by `&At;` and replacing the `\<` by `&lt;`. 
(Note:
 - maybe you should also change `identifer` by `identifier`
 - replace usages like `\@mixin` by `` `@minxin` `` 

)

Does this solve the problem?

**Comment by AlexisWilke** [comment]
Well! It does look good indeed. I wonder whether I had an extra processor in between which converted the `&lt;` and `&gt;` to `<` and `>` respectively.

I still had a problem with one `@` sign, though. Using the `&At;` instead of the direct character fixed the problem as you suggested. So at this point I'm all good!

Thank you for taking the time and underlining the spelling error.

P.S. I don't recall having support for markdown at the time I was actively working on this library, so the backticks may not have worked... But I do use that a lot in my newer documentation.
