### ISSUE TITLE
would be nice to be able to zoom with the mouse (Origin: bugzilla #754474)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5857]
status NEEDINFO severity *enhancement* in component *build* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-09-02 15:32:54 +0000, Adrian wrote:

    Having to move the mouse to the top left corner and press the small buttons
    is annoying.  It would be nice to be able to use the mouse roller knob to
    zoom, and if required, use a keyboard modifier if it will cause scrolling
    issues.

On 2015-09-02 15:37:37 +0000, Dimitri van Heesch wrote:

    Zooming with the scroll wheel should work if you press the shift key as
    well.
    
    Please let me know if that fixes the problem.

On 2015-09-02 15:41:20 +0000, Adrian wrote:

    Ahh, that works on FF on the caller/calls diagrams, but not on the
    collaboration diagram.  It doesn't work at all on Chrome.

**Comment by albert-github** [comment]
I checked with the current version of doxygen (1.9.6) an as far as I can see the collaboration / inheritance / include / call / caller graph all work on FireFox, Chrome, Edge on windows in the way as indicated (shift + wheel)
(we of course have to enable the output format svg and the INTERACTIVE_SVG setting).

I think this problem is solved in the mean time
