### ISSUE TITLE
How to add additional documentation files (Origin: bugzilla #765334)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5987]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-04-20 17:44:53 +0000, Jonathan Cameron wrote:

    Currently doxygen supports 5 file extensions as additional documentation
    files:
      .doc, .txt, .dox, .md, .markdown  (as defined in
    FileDef::isDocumentationFile()
    
    It is not clear from the documentation how to add custom extensions for
    other additional documenation files.  After some experimentation, I realized
    that the current .dox files (for example) are simply C files with comments
    containing doxygen documentation.  Therefore, if I want to add a custom
    extension such as .xyz for additional documentation, I need to do three
    things:
       (1) Make the .xyz files contain C-style comments with doxygen docs
       (2) Add .xyz to the FILE_PATTERNS configuration variable
       (3) add a mapping for the custom extension:
    
          EXTENSION_MAPPING = xyz=c
    
    Adding some comments to this effect to the documentation for
    EXTENSION_MAPPING and to the "My file with a custom extension is not parsed
    (properly) (anymore)" FAQ item.

**Comment by rosshamish** [comment]
Original bugzilla is about documentation. Requesting an enhancement to the documentation to describe how to configure things so that a custom file extension can be parsed.

Checking on the latest version of the FAQ, this is addressed now: https://github.com/doxygen/doxygen/blob/8b2342099979279670478918aa3febe3cba1508b/doc/faq.doc#L80
> Doxygen only parses files that are specified as input (via the \ref cfg_input "INPUT" tag)
and that match a specified extension (mentioned in \ref cfg_file_patterns "FILE_PATTERNS")
The list of files is then reduced by excluding files listed as \ref cfg_exclude "EXCLUDE" or
files that match the patterns set by \ref cfg_exclude_patterns "EXCLUDE_PATTERNS".
> 
> In the past doxygen parsed all files with an unknown extension as C files which could lead to
undesired results. Since version 1.8.8, doxygen requires that you specify a mapping that tells
for a certain file extension, which parser to use.
This mapping is specified using the \ref cfg_extension_mapping "EXTENSION_MAPPING" tag.
If no mapping is specified the file's contents will be ignored.

This text seems to have been around since 1.8.10 at least. Here's the commit that added it: https://github.com/doxygen/doxygen/commit/f63d9ed958d2c06717434e1a90e6417cf2d60f6b

This seems sufficient to me. Proposing to close!

**Comment by albert-github** [comment]
Setting, as suggested, to solved in the mean time.
(Note: will automatically be closed with the next release because of this tag).
