### ISSUE TITLE
Upgrade jQuery to latest 1.x release (Origin: bugzilla #768492)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6027]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.12-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-07-06 16:11:42 +0000, dkmcnulty@gmail.com wrote:

    The latest version of Doxygen (at time of writing) uses jQuery 1.7.1. 
    
    This version will be flagged by various JS library vulnerability scanning
    tools as vulnerable. An example tool is the RetireJS plugin for the Burp
    suite.
    
    Please update the jQuery version packaged with Doxygen to the latest 1.x
    release. At the time of writing, 1.12.4 was the latest
    (http://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released/).

**Comment by lewijw** [comment]
I have submitted a pull request that uses jQuery 1.7.2 which shows up clean on our security scans.

https://github.com/doxygen/doxygen/pull/6683

**Comment by lewijw** [comment]
According to the jQuery home page, “The 1.x and 2.x branches no longer receive patches”, so moving to the latest jQuery release may be best.
Unfortunately, I tried building 1.8.0 into Doxygen, and I saw rendering problems, so I expect changes will be necessary to do any upgrade of jQuery.

**Comment by Croydon** [comment]
> According to the jQuery home page, “The 1.x and 2.x branches no longer receive patches”, so moving to the latest jQuery release may be best.

The main question which @doxygen should answer is: Does Doxygen still care about Internet Explorer versions 6-8? Because those aren't support anymore in jQuery 2 & jQuery 3. For details see https://jquery.com/browser-support/

I believe, however, that at it's very minimum Doxygen should update to the latest 1.x version.

In order to do that and since Doxygen is successfully using 1.7 someone needs to go through the following pages and refactor the used code, if these functions are used within jQuery:

https://api.jquery.com/category/deprecated/deprecated-1.8/
https://api.jquery.com/category/deprecated/deprecated-1.9/
https://api.jquery.com/category/deprecated/deprecated-1.10/

In order to help working on this the jQuery migrate plugin can be used:
https://github.com/jquery/jquery-migrate/tree/1.x-stable#readme
However, jQuery migrate should only be used locally to get notices what still needs refactoring, it shouldn't be pushed to production.

**Comment by Croydon** [comment]
Further resources:

Section "What has been removed", https://blog.jquery.com/2012/08/09/jquery-1-8-released/

https://jquery.com/upgrade-guide/1.9/

**Comment by doxygen** [comment]
I would like to modernize the HTML output produced by doxygen (including the javascripts used).

The main reason why we are now stuck with an old jquery is because of the addons that depend on it. Not all of them work with newer jquery versions or have updates (see https://github.com/doxygen/doxygen/blob/master/jquery/README for the list).

I would like support recent versions of Chrome, Firefox, and Safari (on Mac). 
IE 11 (still the default browser for Windows 7) and higher would also be nice if it is not too much in the way of progress. Older IE versions are no longer relevant, so I don't mind dropping support for them (they for sure are a pain to support). 

I like what the YARD tool produces for Ruby code, see for instance https://www.rubydoc.info/gems/liquid/Liquid/Tag so that could be a source of inspiration. Although this particular page also still uses jquery 1.7.1 😟. I for sure also like what @mosra has done with m.css.

I originally planned to freeze the hard coded HTML output and let all HTML be produced by the new django like template engine I have been working on (see the `.tpl` files here https://github.com/doxygen/doxygen/tree/master/templates/html. Note that you can try it out using the undocumented `-T` option of doxygen; add the `-g` option to generate the default templates once). Given the slow progress it may be better to already improve the hard coded HTML output. Alternatively we could completely go for the template engine route (at least for HTML output), but I'm still a bit worried about the potential performance impact.

**Comment by mosra** [comment]
Oh, wow, templates :heart_eyes:

I was always thinking it would be great to somehow unify the XML and HTML output so it's both generated by the same code. That would mean less maintenance work and features exposed in one automatically being exposed in the other. But now, with the templates you're working on I think it could actually be quite straightforward to produce also the XML output using the same template engine. And this could ultimately result in the orignal XML output generator being dropped/freezed in favor of everything being generated via a template. What do you think?

Thing is, in m.css I have to do a lot of fixups on the XML output, the main problem being "everything is a paragraph", As far as I'm aware, the current HTML output generator has this solved (because nesting block-level elements in paragraphs is not valid HTML), but the XML not. So redoing the XML output using this new templating system would result in the HTML-specific fixes being available for XML as well, along with other accidental disparities being fixed.

Regarding performance: right now, with m.css, the Doxygen run over the relatively large magnum docs (generating just XML) is < 50% of the total runtime, so the perf might be a valid concern (though I'm wasting *excessive* amount of time with a very naive way of building the search data, it's all just Python and also I'm not multithreading anything). But overall I think the massive advantages of having a template engine will outweigh any (potential) performance issues.

**Comment by doxygen** [comment]
With this commit https://github.com/doxygen/doxygen/commit/c141d67332ce9e6875d4c03c4652a88da29a6f78 all scripts have been update to the latest versions available, which also improves the performance and responsiveness of the tree view navigation panel (probably due to the better use of async). 

Next topic is to further improve the HTML structure and better use of CSS.

**Comment by lewijw** [comment]
Thank you very much!  My tests indicate that it is working nicely, and our security scans are clean.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
