### ISSUE TITLE
Support snippet command in Markdown (Origin: bugzilla #769560)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6045]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.12-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-08-05 14:33:16 +0000, dustyn@blasig.us wrote:

    We have transitioned much of our documentation to Markdown. We are sorely
    missing the snippet functionality! If you can point me to right place to
    help fix this issue, I can try to help.

**Comment by albert-github** [comment]
It is a bit unclear what is requested.
The doxygen `\snippet` command does work in the doxygen 1.8.12 version (as it does in the current 1.9.6 doxygen version).
In case it as about native support of the snippet functionality in markdown I think this is the wrong place and it should be posed at one of the "standardization" sites (like https://spec.commonmark.org/).

So this issue is either usage or incomplete or not a doxygen problem.
