### ISSUE TITLE
Feature Request: doxygen command to expand an environment variable (Origin: bugzilla #769679)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6047]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-08-09 17:22:07 +0000, Marc Alff wrote:

    Currently, my @mainpage looks like:
    
    ...
    Document generated on: ${DOXYGEN_GENERATION_DATE},
    branch: ${DOXYGEN_GENERATION_BRANCH},
    revision: ${DOXYGEN_GENERATION_REVISION}
    ...
    
    Now, of course, doxygen does not know anything about
    DOXYGEN_GENERATION_DATE,
    so my options are:
    - use sed to substitute values in the source, before using doxygen (which is
    what is done currently),
    - use sed in the generated output (ok for html, harder to do for pdf etc) to
    change values post generation.
    
    The feature request is to have a new command, say @environment,
    so the documentation can be written instead as:
    
    ...
    Document generated on: @environment DOXYGEN_GENERATION_DATE,
    branch: @environment DOXYGEN_GENERATION_BRANCH,
    revision: @environment DOXYGEN_GENERATION_REVISION
    ...
    
    Before invoking doxygen, the user build script is to export values, for
    example:
    export MY_CUSTOM_THING=<my custom value here>
    
    Doxygen, upon finding the tag @environment MY_CUSTOM_THING, is to execute a
    getenv("MY_CUSTOM_THING") and expand the result in the generated
    documentation.
    
    Thanks for considering this request.

**Comment by albert-github** [comment]
In the given example we see `${DOXYGEN_GENERATION_DATE}` and even when setting this value for `DOXYGEN_GENERATION_DATE` in the environment we don't see it appear in the output (doxygen version 1.8.11 and the current 1.9.6 version).
When replacing the curly brackets to round brackets (se `$(DOXYGEN_GENERATION_DATE)` we see in both mentioned versions the value of the environment variable.

I think the problem is usage.
