### ISSUE TITLE
Doxygen generates volatile (hash-containing) names despite SHORT_NAMES=NO (Origin: bugzilla #772473)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6082]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-10-05 19:50:23 +0000, Yuri wrote:

    This happens on RapidJSON project: https://github.com/miloyip/rapidjson
    
    Such volatile names can't be packaged on FreeBSD, which is a problem.

On 2016-10-05 20:28:55 +0000, Dimitri van Heesch wrote:

    Can you please be more precise? What is you definition of "volatile" and
    where do you see such output?

On 2016-10-05 20:45:47 +0000, Yuri wrote:

    It generates files with hashes in names:
    > share/doc/RapidJSON/html/closed.png
    > share/doc/RapidJSON/html/dir_32fb88e4d38e67d524aa70efbc36f66b.html
    > share/doc/RapidJSON/html/dir_32fb88e4d38e67d524aa70efbc36f66b.js
    > share/doc/RapidJSON/html/dir_5937892b65cdaf02cc4201f920170bd1.html
    > share/doc/RapidJSON/html/dir_5937892b65cdaf02cc4201f920170bd1.js
    > share/doc/RapidJSON/html/dir_8d7584a8244d286291cd37b99676a43b.html
    > share/doc/RapidJSON/html/dir_8d7584a8244d286291cd37b99676a43b.js
    > share/doc/RapidJSON/html/dir_d44c64559bbebec7f509842c48db8b23.html
    > share/doc/RapidJSON/html/dir_d44c64559bbebec7f509842c48db8b23.js
    > share/doc/RapidJSON/html/diyfp_8h_source.html
    
    Hashes depend on the location of build, therefore they are volatile.

**Comment by albert-github** [comment]
There is no reason given why the "volatile" names cannot be packaged. 
The "volatile" names are (normally) only used inside doxygen and should not influence any external program.
The hash values contain the directory names (which are stripped from common prefixes as mentioned in `STRIP_FROM_PATH` and `STRIP_FROM_INC_PATH `. When the user leaves "build dependent paths" in these the hashes change and the user should (re-)consider the used name / settings of `STRIP_FROM_PATH` and `STRIP_FROM_INC_PATH `.

I think the problem is usage and when there full paths encoded the are solved in the mean time.
