### ISSUE TITLE
General documentation wrongly associated with namespace (Origin: bugzilla #773160)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6090]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug_report.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug773160_337943_bug_report.zip/download/download)_ (ID 337943)

On 2016-10-18 13:47:00 +0000, Gennaro Prota wrote:

    Created attachment 337943
    Minimal example
    
    - Unzip the attached file to a directory of your choice; let's call it <B>
    
    - cd to <B>/doc/source
    
    - issue the command <doxygen path>/doxygen doxygen.cfg
    
    - open the file <B>/doc/html/eof__value_8hpp.html
    
    Problem: the documentation at the beginning of the file is attributed to
    namespace breath

On 2016-10-24 18:22:48 +0000, Dimitri van Heesch wrote:

    *** Bug 773161 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
We see here at the to the documentation:
```
//!     \file
//!     \brief A replacement for \c EOF and \c char_traits<>::eof().
// -------------------------------------------------------------------------
//
//!     A convenience source file to separate out the crazy \#includes
//!     required for using \c EOF or \c char_traits<...>::eof():
... more documentation and comment

#include <string>

namespace breath {
```
the result is that the part starting with `A convenience ...` is attributed to ` namespace breath ` due to the fact that the description of the file the `\file` part ends with the first line of normal cpp comment and the next comment block belongs to the first namespace / class / function in the file.
The solution for this is either:
  - remove the 2 lines with normal cpp comment
  - replace the 2 normal cpp comment lines with 2 lines with just `//!`
  - replace the 2 normal cpp comment lines with 
```
//! <!-- ------------------------------------------------------------------------- -->
//
```
  - place `\file` in front of the `A convenience ...` part.

I think this is an usage problem.
