### ISSUE TITLE
Word overrides generated Title, Author, and Created Date when fields are updated (Origin: bugzilla #774628)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6119]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-11-17 16:01:36 +0000, Dan wrote:

    If you update all fields in the rtf document (Select all and F9) some values
    that were specified in the doxyfile or extensionFile are overridden by Word
    (Title, Author, CreateDate, etc).
    
    This is most obvious with the Title, as it will cause it to be blank since
    there is no default for title in a new word document.

**Comment by albert-github** [comment]
Unfortunately no example present so a bit hard to check.
With the 18.12 version I see problems (BOOKMARK not defined) with the title when updating the rtf file, with the 1.9.6 version this problem is gone. For other fields I don't see a problem.

I think the problem is solved in the mean time / incomplete.
