### ISSUE TITLE
Opening and ending tag mismatch in index.qhp (Origin: bugzilla #787292)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6254]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-09-05 04:48:19 +0000, levi.armstrong@gmail.com wrote:

    When generating the documentation for the following repository after
    updating the following parameter in the doxygen.config file I get and
    mismatch error.
    
    Recreate Error:
      Repository: https://github.com/ros-industrial/industrial_moveit
    
      Update Variables:
        GENERATE_QHP = YES
        QCH_FILE = industrial_moveit.qch
        QHP_NAMESPACE = org.rosindustrial.industrial_moveit
    
    Error:
      Error in line 2905: Opening and ending tag mismatch
      error: failed to run qhelpergenerator on index.qhp

**Comment by albert-github** [comment]
When checking out the version of September 5, 2017 I could reproduce the problem with version 1.8.11 and with the current version (1.8.15).
With the current head the problem is gone as the 'stomp' part has been "outsourced" to another repository.
When looking at the warnings we see a lot of messages about multiple use of section labels (and also multiple use of the `\mainpage` command).
When changing the section label `stomp_plugins` in the file `stomp_moveit/example_pages.dox`  into e.g. `stomp_plugins_m` the problem is gone.

So the problem looks like to be dependent on one label, though it is advised also to look at the other reported label problems and the multiple use of the mainpage commands (and of course all other warnings).

I think the problem is Usage.

(@Levi-Armstrong to get the message also at the issuer of the issue).
