### ISSUE TITLE
Illegal command n as part of a title section (Origin: bugzilla #792012)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6304]
status NEW severity *critical* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-12-28 13:49:17 +0000, Ronan.LeGallic@nagra.com wrote:

    From documentation: Simple aliases
    
    > For example defining the following alias: 
    >
    >  ALIASES += sideeffect="\par Side Effects:\n" 
    >
    > will allow you to put the command \sideeffect (or @sideeffect) in the
    documentation, which will result in a user-defined paragraph with heading
    Side Effects:.
    >
    > Note that you can put \n's in the value part of an alias to insert
    newlines.
    
    
    Code:
      \sideeffect description
    
    Doxygen:
      warning: Illegal command n as part of a title section
    
    Result:
      Side Effects: description
    
    Instead of:
      Side Effects: 
        description

On 2017-12-28 18:45:34 +0000, albert wrote:

    The documentation for sideeffect is indeed not up to to date.
    The \n has been replaced by ^^

On 2018-01-31 15:06:41 +0000, mark.shackman@cirrus.com wrote:

    (In reply to albert from comment # 1)
    > The documentation for sideeffect is indeed not up to to date.
    > The \n has been replaced by ^^
    
    If the only change is "\n has been replaced by ^^" then what is the point of
    this patch?
    
    This change has broken backwards compatibility, and it is not documented as
    having this effect. [It's bad practice for a minor release such as this
    (X.XX.14) to break existing documentation, even if trying to solve another
    issue.]
    
    Please revert the change, and solve any issues without breaking existing,
    documented practice.

**Comment by albert-github** [comment]
The `\n` had some side effects in `ALIASES`, see a.o. https://stackoverflow.com/questions/46050789/doxygen-alias-with-multiple-commandsand the description in the commit message (see #602).

There have been some initial problem with the replacement to `^^` but these have been solved in the mean time.
In the changelog of the 1.8.14 doxygen release there was a message about the change "Physical newlines in ALIASES configuration tags. [[view](https://github.com/doxygen/doxygen/commit/d6801c4c5eaeebc5e14f5d1cd7c312ad82c1dbbd)]" but maybe it should have been a bit clearer as it indeed constituted a breaking change.

Seen the positive effects of the change and the use since 1.8.14 the change won't be reverted.
