### ISSUE TITLE
error: Could not open file .../doc/html/functions_ .html for writing (Origin: bugzilla #792935)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6323]
status ASSIGNED severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cyrillic_error_1.8.14.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug792935_367486_cyrillic_error_1.8.14.zip/download/download)_ (ID 367486)

On 2018-01-26 15:52:06 +0000, Nikolai wrote:

    Created attachment 367486
    error_cyrillic_utf_8_java_style
    
    Overview:
    
    There is error when generating documentation in java-style from russian-
    language files.
    Error looks like this:
    
    Generating member index...
    error: Could not open file
    C:/1C/documentators/doxygen/doc/html/functions_.html for writing
    Exiting...
    
    And there is no such error when I replace cyrillic symbols with latin symbol
    (transliteration).
    
    Steps to Reproduce:
    	run "doxygen.exe config.dox" with attached files
    	
    Actual Results: 
    	Documentation contains not all functions from class.
    	
    Expected Results:
    	No errors were encountered and documentation contains all functions.
    
    Build Date & Hardware:
    	Build 2018-01-26 on Windows 10 (Eng)
    	Doxygen version 1.8.14 x32
    
    Additional Information:
    	Source files have UTF-8 encoding.
        The symbol DC2 ater "_" in "/function_DC2.html" is from non-printables
    of ASCII table.

On 2018-02-02 13:15:02 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 646)

On 2018-02-10 14:00:11 +0000, albert wrote:

    Patch has been integrated into main development branch on github.

**Comment by aliha** [comment]
I have a similar problem. Any idea when will this fix be released? 
```
Generating member index...
Generating file index...
Generating file member index...
error: Could not open file E:/*****/html/globals_".html for writing
Exiting...
```

**Comment by albert-github** [comment]
In a recent comment Dimitri van Heesch wrote: 

> I have plans to make a new release somewhere between Christmas and the New Year.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by basmevissen** [comment]
Unfortunately, the problem still seems to exist with Doxygen 1.8.20:

Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating graphical class hierarchy...
Generating member index...
Generating file index...
Generating file member index...
error: Could not open file X:/Doxygen/html/globals_".html for writing
Exiting...

C:\Git\SR640\Workspace>doxygen --version
1.8.20 (f246dd2f1c58eea39ea3f50c108019e4d4137bd5)

System is Windows 10 Enterprise 64-bit with Sophos virus scanner.

I would love to give a small test case, but this is the (repeatable) result of a very large software tree. So I have no idea what might have triggered the issue. I had a few other runs on the same tree that finished, albeit not generating a valid doxygen output (missing most files...). So some influence of the platform itself cannot be excluded... Notice that the run was done on a "subst" drive of a local directory (e.g c:\git\project -> x:).

Hope you can double check whether there is still a rough case in the Doxygen source code.

**Comment by albert-github** [comment]
- best would be to open a new issue and refer there also to this issue
- a weird thing is the `X:/Doxygen/html/globals_".html` looks like a double quote `"` in the filename, this should never be possible / generated. can you redirect the output to a file and attach that (as zip or compressed tar file) to the (new) issue. The idea is to eliminate the influence of cut and paste as well as the formatting from github. Best is also to share the doxygen configuration file.
- it would be good to know what happens, as a test, when you don't use the "subst drive" but straight on the directory `c:\git\project`
- it would be good to know whether it worked for you with the 1.8.15 version on the "subst drive"

**Comment by basmevissen** [comment]
- I reopened the issue as that was suggested to do so by Dimitri when he closed it.
- The output on the console was exactly what I copied into the bug report. It really tries to create a file with such a name. See https://github.com/doxygen/doxygen/issues/6323#issuecomment-430642606 for the same issue.
- I'll try again without any substituted paths in the Doxyfile.
- Only used 1.8.20.

**Comment by albert-github** [comment]
in the original message we see that 
> The symbol DC2 ater "_" in "/function_DC2.html" is from non-printables of ASCII table.

seen the mentioning of the non-printables I requested the redirected output, so I can check with (e.g. `od`) what is really in the file.

I see the reopen message more like to be valid for the next release and not for a release a number of versions further on.

I had also a go at the example as attached to the original message and with 1.8.14 this didn't complete, but with versions 1.8.15. 1.8.20 and the current master (55e15c86717f38c9b510e4287cb0b4f165b8cb10) it did complete. I didn't use a "subst drive" but I don't think the problem is from the "subst drive". 

- do you have any non-ASCII characters in your file names of function / variable names (in the files)?
- which `INPUT_ENCODING` are you using and are all the file encoded according to this `INPUT_ENCODING`? (most likely they are as otherwise I would expect an earlier crash).

**Comment by basmevissen** [comment]
* I tried the attached example and it completed with some messages. Generated output seems ok.
* The input encoding is UTF8 and I would expect files to be ASCII or UTF8. File and directory names should only be using English or maybe western European characters.
* The offending character is really a " (I piped the error output to a file and checked with both and ASCII and UTF8 encoding in an editor)

Anyway, Doxygen should, independent of whatever inputs it gets, never try to create files with names that are not valid on the underlying file system (NTFS) or platform (Win10). Or, even better, only use a common subset that applies to modern file systems on various platforms.

**Comment by albert-github** [comment]
- I compared (a.o.) the code of the functions:
  - static void writeClassMemberIndexFiltered(OutputList &ol, ClassMemberHighlight hl)
  - static void writeFileMemberIndexFiltered(OutputList &ol, FileMemberHighlight hl)

  as well as the code for the variables:
  - g_memberIndexLetterUsed
  - g_fileIndexLetterUsed

  but could not see a difference.
- 'The offending character is really a " (I piped the error output to a file and checked with both and ASCII and UTF8 encoding in an editor)', in my opinion an editor is no really suitable for this task. Just redirect the output to a file and attach it to this issue so I can inspect it as well.
- Indeed doxygen should not try to create a file like this, but without knowing exactly what is causing the problem it is not possible to solve the issue (the original issue contained a nice small example, so it was relatively easy to fix the problem). You wrote: "this is the (repeatable) result of a very large software tree. So I have no idea what might have triggered the issue.", the best starting point is to remove some directories from the `INPUT` configuration tag and get a smaller tree to process by doxygen and repeat this to see the results which might give a clue where the problem lies.
  - Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
  - When not a proprietary project you could also attach the entire source project or when available on e.g. github give a pointer to it (the later is not persistent as the content changes, but probably would do for the time being).

**Comment by basmevissen** [comment]
Thanks for spending time on this already. I'll try to pinpoint the issue.
