### ISSUE TITLE
Segmentation fault when generating graphical class hierarchy (Origin: bugzilla #793076)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6325]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[reproduce.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug793076_367730_reproduce.tgz/download/download)_ (ID 367730)

On 2018-01-31 18:45:59 +0000, Luc wrote:

    Created attachment 367730
    Minimal set of files to reproduce the bug. Just run "doxygen Doxyfile"
    
    When running doxygen with HAVE_DOT = YES it ends in the following way:
    
        Generating graphical class hierarchy...
        make: *** [Makefile:470: doxygen] Segmentation fault (core dumped)
    
    This worked fine for the same project, last time that I tried. From the non-
    updated Doxyfile it seems to be with doxygen 1.8.2.
    
    It seems to be a function calling itself inside the constructor of
    DotGfxHierarchyTable, and running out of stack. With the debuginfos
    installed, the beginning and end of the stack frames look like:
    
    
        [Current thread is 1 (Thread 0x7f1aabdde6c0 (LWP 9464))]
        (gdb) bt 10
        # 0  _int_malloc (av=0x7f1aab0e9c20 <main_arena>, bytes=24) at
    malloc.c:3622
        # 1  0x00007f1aaadb999e in __GI___libc_malloc (bytes=24) at
    malloc.c:3074
        # 2  0x00007f1aab6e8718 in operator new(unsigned long) () from
    /usr/lib64/libstdc++.so.6
        # 3  0x000055be425f96ea in QGList::append (this=0x55be4684e1a0,
    d=<optimized out>) at /usr/src/debug/doxygen-1.8.14/qtools/qglist.cpp:366
        # 4  0x000055be4255d017 in QListIterator<DotNode>::QListIterator (l=...,
    this=0x7fff189c20d0) at /usr/src/debug/doxygen-1.8.14/qtools/qlist.h:129
        # 5  DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fff191bee1c: 130869) at
    /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2195
        # 6  0x000055be4255d039 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        # 7  0x000055be4255d039 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        # 8  0x000055be4255d039 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        # 9  0x000055be4255d039 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        (More stack frames follow...)
        (gdb) bt -10
        # 130871 0x000055be4255d039 in DotNode::renumberNodes (this=<optimized
    out>, number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        # 130872 0x000055be4255d039 in DotNode::renumberNodes (this=<optimized
    out>, number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        # 130873 0x000055be4255d039 in DotNode::renumberNodes (this=<optimized
    out>, number=@0x7fff191bee1c: 130869)
            at /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2199
        # 130874 0x000055be4255df28 in
    DotGfxHierarchyTable::DotGfxHierarchyTable (this=0x7fff191bef00) at
    /usr/src/debug/doxygen-1.8.14/src/dot.cpp:2535
        # 130875 0x000055be421f5b8b in writeGraphicalClassHierarchy (ol=...) at
    /usr/src/debug/doxygen-1.8.14/src/index.cpp:1055
        # 130876 writeIndexHierarchyEntries (ol=..., entries=...) at
    /usr/src/debug/doxygen-1.8.14/src/index.cpp:4178
        # 130877 0x000055be421f4834 in writeIndexHierarchyEntries (ol=...,
    entries=...) at /usr/src/debug/doxygen-1.8.14/src/index.cpp:4271
        # 130878 0x000055be421f6f4b in writeIndexHierarchy (ol=...) at
    /usr/src/debug/doxygen-1.8.14/src/index.cpp:4469
        # 130879 0x000055be42176518 in generateOutput () at
    /usr/src/debug/doxygen-1.8.14/src/doxygen.cpp:11575
        # 130880 0x000055be4212ed8e in main (argc=2, argv=0x7fff191bf588) at
    /usr/src/debug/doxygen-1.8.14/src/main.cpp:38
    
    
    You can see that the `number` passed to DotNode::renumberNodes is 130869,
    which is the number of times that the DotNode::renumberNodes is called, so
    it is correctly incremented every time.
    
    If I make the stack 4 times bigger it becomes 524116, which is about 4 times
    more recursions. I don't know if the function calls itself infinitely or if
    I just have an insane amount of dot files to renumber.
    
    I'm attaching 2 header files and one Doxyfile which reproduce the problem.
    The full project compiles and runs fine, as a side note, even though the
    remaining contents in the headers maybe don't make much sense anymore.
    
    
    The doxygen_objdb_$PID.tmp file is empty.
    The versions of the software are:
    
        > doxygen --version
        1.8.14
        > dot -V
        dot - graphviz version 2.40.1 (20161225.0304)
    
    Running openSUSE Tumbleweed (version 20180129, it's a rolling release OS) on
    x86_64 with Gkernel 4.14.15-1-default, glibc version 2.26-9.1.
    
    
    I can reproduce this bug with only the following non-default values in the
    configuration:
    
        INPUT = minset/TraceReader.h minset/specialized/Trace.h
        RECURSIVE = YES
        HAVE_DOT = YES

On 2018-02-01 15:19:35 +0000, Luc wrote:

    Sorry RECURSIVE = YES is not needed, and the number of dot files does not
    seem to matter. I think it's some .map files that point to each other
    circularly somehow.

**Comment by lucjaulmes** [comment]
I can still reproduce this.

**Comment by albert-github** [comment]
@lucjaulmes Which version did you try? current master?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6680

**Comment by lucjaulmes** [comment]
Sorry for the delay. Thanks, I can confirm the current master now does *not segfault* both on the provided attachments and full project. There are indeed cyclic inheritances detected by doxygen, but I believe they are wrong. (I'm not sure cyclic inheritances make any sense in the absolute?)

### About this example

The graph you show seems to have only 3 classes, while there should be 4:
1. `trace::Trace`
2. `trace::TraceReader`
3. `trace::specialized::Trace`
4. `trace::specialized::FileTrace`

Inheritances (`<--`) are:

 `trace::Trace (1) <-- trace::TraceReader (2)`
 `trace::TraceReader (2) <-- trace::specialized::Trace (3)`
 `trace::specialized::Trace (3) <-- trace::specialized::FileTrace (4)`

In the cache hierarchy, the following relation is depicted correctly:
 `trace::Trace (1) <-- trace::TraceReader (2) <-- trace::specialized::Trace (3)`

However I see the following incorrect arrows in the drawing you provided (and that master generates from this minimal example):
`trace::TraceReader (2) <-- trace::Trace (1)` (should not exist)
 `trace::Trace (1) <-- trace::specialized::FileTrace (4)` (should be  `trace::specialized::Trace (3) <-- trace::specialized::FileTrace (4)`)

That is, doxygen mistakes the parent of `trace::specialized::FileTrace (4)` to be `trace::Trace (1)` instead of `trace::Trace(3)`. That seems to be because doxygen is trying to do some best-effort/heuristics to find which parent class to use?

### An even smaller example

I've managed to reduce the minimal example even further, in a single file (with doxygen current master 43e67dce):

    template<typename T>
    class ns1::A {
    };

    template<typename T>
    class ns2::A : public ns1::A<T> {
    };

    template<typename U>
    class ns2::C : public ns2::A<U> {
    };

This generates the following graph:

![self-inheritance graph](https://i.imgur.com/C7zmXSx.png)

Note that renaming the template parameter `U` to `T` is sufficient to fix the bug and generate the correct graph:
![correct graph](https://i.imgur.com/YktIJbd.png)


Interestingly, removing the namespace `ns1` breaks discovering `A<T>` as a parent for `ns2::A`, but i'm not sure that it is related.

**Comment by albert-github** [comment]
Thanks for the extensive report.

To have the possibility to close this issue with the next release could you create a new issue out of your comment?

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
