### ISSUE TITLE
Doxygen 1.8.14 breaks Windows XP compatibility (Origin: bugzilla #793589)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6336]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-02-19 09:48:34 +0000, Michael Waeber wrote:

    According to the download site [1] doxygen should run on all Windows
    platforms since Windows XP. It runs on XP up to 1.8.13. Version 1.8.14
    breaks the compatibility with Windows XP because it uses the windows API
    SHGetKnownFolderPath which is not available on Windows XP [2]:
    
    -------------------------------------------
    dumpbin /IMPORTS:SHELL32.dll doxygen.exe
    ...
    Section contains the following imports:
    
    SHELL32.dll
                    8771F4 Import Address Table
                   1009A04 Import Name Table
                         0 time date stamp
                         0 Index of first forwarder reference
    
                       DE SHGetKnownFolderPath
                      136 ShellExecuteExW
    ...
    ------------------------------------------- 
    
    
    [1] http://www.stack.nl/~dimitri/doxygen/download.html 
    [2] https://msdn.microsoft.com/en-
    us/library/windows/desktop/bb762188(v=vs.85).aspx

**Comment by twelve12pm** [comment]
Yes.

The doxygen download page states "A binary distribution for Windows. All versions of Windows since XP are supported."

Yet on Windows XP, doxygen 1.8.14 and 1.8.15 produce the error message: "The procedure entry point SHGetKnownFolderPath could not be located in the dynamic link library SHELL32.dll."

That API was introduced in Windows Vista.

Either it should be handled somehow, or (the more likely possibility) the installer should be updated to refuse installation on XP and the download page should be updated to say that all versions of Windows since Vista are supported.

**Comment by doxygen** [comment]
I'll make more clear that XP is no longer supported.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
