### ISSUE TITLE
CSS for Markdown tables do not use HTML_COLORSTYLE_HUE, HTML_COLORSTYLE_SAT config variables

### ISSUE THREAD

**Issue by dangthill** [doxygen/doxygen#6411]
HTML_COLORSTYLE_HUE, HTML_COLORSTYLE_SAT, and HTML_COLORSTYLE_GAMMA aren't used when calculating the background colors for Markdown tables (eg: th.markdownTableHeadLeft
th.markdownTableHeadRight th.markdownTableHeadCenter, th.markdownTableHeadNone).  Instead, the default colors are used.

Obviously, this can be worked around by using HTML_EXTRA_STYLESHEET, but specifying the HUE, SAT, and GAMMA have previously been sufficient for my meager styling needs.

**Comment by albert-github** [comment]
Looks like the colors are changed at an estimated 77 places in the doxygen.css file out of an estimated 129 places.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6413

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
