### ISSUE TITLE
Add possibility to debug/more verbosity on demand

### ISSUE THREAD

**Issue by BrainStone** [doxygen/doxygen#6427]
On my windows machine when I run doxygen, it produces loads of "The system cannot find the specified path." ("Das System kann den angegebenen Pfad nicht finden.") errors. However I cannot figure out which path it cannot find. Therefore a more verbose mode would be much apprechiated, so that people can more easily debug that kind of issue.

(My log: https://gist.github.com/BrainStone/43fc5250ac2006e902a292509123d5c9)

**Comment by albert-github** [comment]
Looks a bit like you are using a filter and the filter cannot be started try to run with `-d extcmd`, when this does not show the problems attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem.

**Comment by BrainStone** [comment]
Would a repository work too? Because if so, this repository https://github.com/BrainStone/TruncateablePrimes works fine on my Linux VM but not on my Windows machine.

New log: https://gist.github.com/BrainStone/26f68666083586e88862e6d09ae18f67

But generally speaking it would be very nice to be able to know what paths/files it's having issues with.

**Comment by albert-github** [comment]
- a repository is not the best way as it can be / is a moving target and one likes to have a fixed example.
- the problem with windows output redirection to a file of standard input and standard output, as it are different streams, gives unpredictable results, better is to cut and paste it from the terminal and place it in a file.
- is `sed` installed on Windows? and when it is installed what "sort" of sed is it (native or cygwin or ...). In case of Windows version it might be that it has some problems with the forward  (`\`) slashes, in case of cygwin it might have problems with the `C:` part. In both cases create a script `sed.bat` (see to it that this file is in the `PATH` before the `sed.exe` that does some conversion on the file argument and subsequently calls `sed.exe` (with `.exe` otherwise you can get an infinite loop).

**Comment by BrainStone** [comment]
Ok. I was just asking, because my time is limited.

I do have sed installed. It looks like it is the cygwin version.  
And how exactly would I create these conversions?

**Comment by albert-github** [comment]
Looks like the solution is even easier (in this case) than expected.
We have now the line:

```
INPUT_FILTER           = "sed -e 's/\/\/ *\(TODO\|FIXME\)/\/\/\/ \\todo/'"
```
When changing this to:

```
INPUT_FILTER           = "sed -e \"s/\/\/ *\(TODO\|FIXME\)/\/\/\/ \\todo/\""
```
everything looks like to function.
Note: I personally prefer the syntax with `'` too but apparently  this gives some problems.

**Comment by BrainStone** [comment]
Incredible! That did fix it.

Sometimes it's the small things...
