### ISSUE TITLE
markdown tables utf8 header

### ISSUE THREAD

**Issue by deep125** [doxygen/doxygen#6454]
Version 1.8.14 windows

The text in the table header is truncated. If the text is not ANCII
[doxugen_bag.zip](https://github.com/doxygen/doxygen/files/2306226/doxugen_bag.zip)

**Comment by albert-github** [comment]
Not sure which pull request did solve it but in the current master version of doxygen the problem has been solved.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
