### ISSUE TITLE
Underlying type of C style enum.

### ISSUE THREAD

**Issue by p-groarke** [doxygen/doxygen#6476]
Using older "anonymous" typed enum doesn't expose the type in xml. Was this patch only for enum classes? https://github.com/doxygen/doxygen/commit/17bceb8f4580535de52d19e8cadf0d088f972bef
Is there an xml option to enable this behavior?

```
enum : int {
    blee = -1,
    blou = 0
};
```

**Comment by albert-github** [comment]
I assume you used version 1.8.14 (doxygen -v).
I tried with 1.8.14 and I think the values are present, at least when setting `EXTRACT_...=YES` (and `GENERATE_XML=YES`).

Please check, otherwise please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
