### ISSUE TITLE
INHERIT_DOCS not working for python

### ISSUE THREAD

**Issue by pierralex** [doxygen/doxygen#6566]
Please find attached sample for which the INHERIT_DOCS parameter is not working for python. If the value is set to yes (default), i get a warning for undocumented method in ChildClass (and it is not documented in the final documentation)
[inherit_docs.zip](https://github.com/doxygen/doxygen/files/2498994/inherit_docs.zip)
Edit: update the zip

**Comment by albert-github** [comment]
I ran the problem with version 1.8.14 (retrieved zip file after the message "update the zip appeared"):
- I  get a warning (in doxygen.log)
- I see the documentation in the inherited part of the ChildClass

Please retry and show where you don't see the documentation picture ?).

**Comment by pierralex** [comment]
Sorry I did not recheck the documentation after modifying my sample (which contained an error). The documentation is good indeed. But the warning remains. Is it possible to remove it? Overriding the doc is not always necessary.

**Comment by albert-github** [comment]
Comment is clear, so the only problem is that the warning is given although it gets the documentation from another command. This has to be checked.

**Comment by albert-github** [comment]
I'm wondering whether or not the code / output is correct.
We have a routine `my_method` in the `ParentClass` and this is inherited to the `ChildClass`, but in the `ChildClass` we have also a `my_method`. Both routines look to me, but this might be a small knowledge deficiency about Python, to have the same signature and are in the documentation of `ChildClass` they are mentioned both(!), when renaming the `my_method` in the `ChildClass` to `my_method_child` you can see this more clearly and the warning is also about `my_method_child`.
So it looks like the warning is correct.
When this is not the case, please make a small complete example, that calls both `my_method`s from a `main` program so that it can be run as well.

**Comment by albert-github** [comment]
Based on the given example I created a full example in Python and a similar program in Cpp. I also ran both programs. For the code and the output see the attachment.

When running the doxygen I see in the Cpp documentation:
- in case the function is declared `virtual` in the `C_ParentClass` and it is not overloaded it is shown in `C_ChildClass` as inherited, same when not declared `virtual`. 
- in case the function is declared `virtual` in the `C_ParentClass` and it is overloaded it is shown in `C_ChildClass` as normal function and not as inherited. I case not declared `virtual` it is shown as normal and as inherited.

Looks like Python follows the no virtual approach of Cpp.

@doxygen is the 'non-virtual' approach from Cpp correct or should here also the inheritance disappear?

Example (source and output): [my_example.zip](https://github.com/doxygen/doxygen/files/2499373/my_example.zip)

**Comment by pierralex** [comment]
The c++ behavior is what i would expect. But according to python documentation (https://docs.python.org/3/tutorial/classes.html#inheritance), all methods are c++ virtual equivalent (there is no virtual keyword in python).
So the child class in python should inherit its parents method documentation unless a documentation is provided for the overriden methods.
Undocumented method warning is wrong too.
Like you say, Doxygen Python doc follows no virtual approach but should follow virtual approach.

**Comment by albert-github** [comment]
For the Python "virtual" problem I've just pushed a proposed patch, pull request #6570

**Comment by albert-github** [comment]
Code has been integrated in master.

**Comment by pierralex** [comment]
Thank you
Best regards
Pierre

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
