### ISSUE TITLE
Unexpected anchor tags in tag-files

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#6585]
Tag files will contain wrong entries for structs or unions with unnamed members, and INLINE_SIMPLE_STRUCT is set to "YES". This results in a warning message "Unexpected tag `anchor' found" when using this tag file in another project.

Steps to reproduce (see attached zip-file):

- create 2 projects
- project 1 contains a source file with an struct/union with unnamed members; source file should also contain special command \file
- doxygen config file for project 1 with INLINE_SIMPLE_STRUCT = YES and GENERATE_TAGFILE
- project 2 which uses this TAGFILE

Running doxygen on project 2 will produce this warning message

[Test1.zip](https://github.com/doxygen/doxygen/files/2531844/Test1.zip)

Regards
Thomas Schneider

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6586

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
