### ISSUE TITLE
Add link to useful article by hostilefork

### ISSUE THREAD

**Issue by KantarBruceAdams** [doxygen/doxygen#6703]
Add a link to http://blog.hostilefork.com/low-commitment-doxygen-markup-cpp/ here
http://www.doxygen.nl/articles.html

The author points out several useful features of Doxygen which even long time users might not know about.

**Comment by doxygen** [comment]
I'll add a link to it.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
