### ISSUE TITLE
The INSTALL file contains a dead link to install.html

### ISSUE THREAD

**Issue by jschleus** [doxygen/doxygen#6707]
The INSTALL file of the new release 1.8.15 (congratulations!) contains a dead link
   
 http://www.doxygen.org/install.html

The correct link may be

 http://www.doxygen.nl/manual/install.html.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6711

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
