### ISSUE TITLE
mainpage notitle causes notitle to appear in index bar

### ISSUE THREAD

**Issue by modersohn** [doxygen/doxygen#6716]
When using mainpage with the notitle option, notitle will appear in the index bar at the top for sub pages.

[TestCase6716.zip](https://github.com/doxygen/doxygen/files/2717139/TestCase6716.zip)

1. Compile the attached testcase
2. Open index.html
3. Click on Tasks

actual: "notitle" appears at the second row of the index bar at the top
expected: either Main Page or the project name should appear

Interestingly the changelog for the very old release 1.3.6 claims this had been fixed previously?

**Comment by albert-github** [comment]
The problem has been visible as soon as the `\supage` worked, 
- till version  1.8.6 we get the warning:
  `TitlePage.dox:14: warning: unable to resolve reference to `tasks' for \ref command`
- from version 1.8.7 we don't get the warning but the "notitle" in the index bar

As a workaround (?) it is possible (according to my small test; got the idea from the warning in the 1.8.6 version) to use `\ref` instead of `\subpage`.

Small technicality, the 1.3.6 speaks of "Using "\mainpage notitle" caused the "notitle" to appear in the treeview." and not about the index bar at top (the command subpage didn't even exist in 1.3.6, it was introduced in 1.4.2).

**Comment by modersohn** [comment]
Thanks for the clarification and the workaround - that does indeed solve the problem for me!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6717

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
