### ISSUE TITLE
Typo in Doxygen 1.8.15 warning message

### ISSUE THREAD

**Issue by pkl97** [doxygen/doxygen#6721]
diff --git a/src/docparser.cpp b/src/docparser.cpp
    index a5c0cc77..68e2e1f8 100644
    --- a/src/docparser.cpp
    +++ b/src/docparser.cpp
    @@ -509,7 +509,7 @@ static void checkUnOrMultipleDocumentedParams()
                            "argument '" + aName +
                            "' from the argument list of " +
                            QCString(g_memberDef->qualifiedName()) +
    -                         " has muliple @param documentation sections");
    +                         " has multiple @param documentation sections");
            }
        }
        if (found)

**Comment by albert-github** [comment]
Can you make a pull request out of it (easier to integrate).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
