### ISSUE TITLE
SHOW_NAMESPACES = NO breaks latex PDF

### ISSUE THREAD

**Issue by modersohn** [doxygen/doxygen#6727]
When switching off SHOW_NAMESPACES, I can no longer build a PDF from the latex output. It fails with

! LaTeX Error: File `namespaces.tex' not found.

Here's a testcase: [TestCase6726.zip](https://github.com/doxygen/doxygen/files/2721259/TestCase6726.zip)

1. Build the testcase
2. Run make.bat from the Doc\latex subdirectory

expected: should run fine and produce refman.pdf
actual: Error about missing namespaces.tex file

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6740

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
