### ISSUE TITLE
Broken latex output with <h1> inside <table>

### ISSUE THREAD

**Issue by modersohn** [doxygen/doxygen#6728]
In a bigger project I now have a broken latex output after upgrading from 1.8.12 to 1.8.15.

I've nailed it down to a minimal testcase (though I couldn't verify that the testcase works with 1.8.12).

[BrokenLatexMainPage.zip](https://github.com/doxygen/doxygen/files/2721351/BrokenLatexMainPage.zip)

1. Build with doxygene
2. Run make.bat from Doc\latex

expected: should run fine and create refman.pdf
actual: fails with 

```
(index.tex
! Missing \endgroup inserted.
<inserted text>
                \endgroup
l.8 \end{longtabu}

?

```

Using MiKTeX 2.9 FWIW.

**Comment by albert-github** [comment]
The test problem runs in 1.8.12 (and also in 1.8.14).
The problem is here the `<h1>` command that in LaTeX translates into `\section*`, i.e. an unnumbered section. It is a bit strange to have such a command inside a table (in my opinion).
In case this is to mimic a header the `<th>` command is more appropriate.

The background of that it is not working anymore (and in my opinion should not have worked in older versions either) is the fact that the alignment (Left, Right, Center) in the tables is now honored (git checksum: d984f7dd2, pul request #751).

In my opinion this is usage.

**Comment by modersohn** [comment]
Thanks for the clarification on why this happens. The file in question is a html main page which uses a table for the layout. I know, this doesn't sound like a good idea nowadays, but that's the way it has been done. I'll see how I can achieve something similar without a table layout.

BTW: thanks a lot for your commitment and help to this valuable project! And I really do appreciate your professional tone. It makes quite a difference.
