### ISSUE TITLE
align environment for formula (\f{align}) no longer working

### ISSUE THREAD

**Issue by svigerske** [doxygen/doxygen#6732]
With Doxygen 1.8.15, code like `\f{align} x & = y \f}` is no longer handled correctly, but gives a found unknown command warning.

[falign.zip](https://github.com/doxygen/doxygen/files/2723137/falign.zip) has a Doxyfile and main.md file to reproduce this.

This used to work fine with Doxygen 1.8.13.

**Comment by svigerske** [comment]
Thanks, then that's easy to workaround.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6735

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
