### ISSUE TITLE
invalid cite anchor id when using crossref

### ISSUE THREAD

**Issue by svigerske** [doxygen/doxygen#6733]
When I have two citations that crossref a third one, which is not cited on its own, then I get an invalid cite anchor id warning.
Files in [crossref.zip](https://github.com/doxygen/doxygen/files/2723358/crossref.zip) should reproduce this issue with Doxygen 1.8.15. Versions 1.8.13 and 1.8.14 seem to be ok.

**Comment by albert-github** [comment]
Looks to me like an incorrect warning, result looks OK though.

**Comment by albert-github** [comment]
It looked like an incorrect warning, but in fact the cross references weren't taken into account.

I've just pushed a proposed patch, pull request #6738

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by svigerske** [comment]
Looks good. Thank you!
