### ISSUE TITLE
Build fail in Windows with build_parse turn ON (unistd.h does not exist in Windows)

### ISSUE THREAD

**Issue by tan-wei** [doxygen/doxygen#6939]
In the source file [doxyparse.cpp](https://github.com/doxygen/doxygen/blob/master/addon/doxyparse/doxyparse.cpp), it includes `unistd.h`. However, it is not contained in the Windows. I find that the descriptions about `doxyparse` including building in the Windows with MSVC, is anything going wrong?

Thanks very much!

**Comment by albert-github** [comment]
Although doxyparse is just a demo program it should compile.

I've just pushed a proposed patch, pull request #6940

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
