### ISSUE TITLE
Syntax highlighting doesn't work when calling \dontinclude from Markdown files

### ISSUE THREAD

**Issue by fakenmc** [doxygen/doxygen#7033]
Syntax highlighting doesn't work when calling \dontinclude from Markdown files. This worked at least until Doxygen 1.8.7.

Find attached a simple example: [example.zip](https://github.com/doxygen/doxygen/files/3258985/example.zip)

Problem exists (at least) in Doxygen 1.8.13 and 1.8.15.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7034

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by fakenmc** [comment]
Thanks!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
