### ISSUE TITLE
Doxysearch.cgi: enable wildcard search, partial matches and phrase search

### ISSUE THREAD

**Issue by tirolerstefan** [doxygen/doxygen#7074]
I would like to improve the doxygen full text search (which is using Xapian) by extending the parser with following flags:
Xapian::QueryParser::FLAG_WILDCARD
Xapian::QueryParser::FLAG_PHRASE
Xapian::QueryParser::FLAG_PARTIAL

I adapted the code in doxysearch.cpp, code snippet taken from following page:
https://sourceforge.net/p/doxygen/mailman/message/35830262/

Attached Pull Request will show the diffs.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
