### ISSUE TITLE
Doxygen does not link to C# snippets - regression

### ISSUE THREAD

**Issue by lmorsino** [doxygen/doxygen#7119]
Doxygen 1.8.15 does not create links on C# code when the code is imported from an external source such as a code snippet. I've attached a test case which shows the problem. Same error as #5199 which was fixed, so this is a regression. It appears to work fine in 1.8.14 but not 1.8.15.

[doxygen bug.zip](https://github.com/doxygen/doxygen/files/3385591/doxygen.bug.zip)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7353

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
