### ISSUE TITLE
No warning when same page created

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7147]
I have joined an example

A test page creates duplicated subpages, sections and subsections, mixed with non-duplicated ones.

Doxygen warns about the section and subsection duplicates, but there is no such warning for the page duplicates (i.e. subpage 1.1 and subpage 1.2), why?

I believe a warning should also be issued since the result is not the one one would expect (page 1.2 is merged within 1.1).
[Doxygen Bug XXX2.zip](https://github.com/doxygen/doxygen/files/3451676/Doxygen.Bug.XXX2.zip)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7169

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
