### ISSUE TITLE
Inconsistent handling of verbatim block within list

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7148]
I have joined an example.

Normally, an empty line is tolerated within markdown lists. However, if there is an empty line before a verbatim block within a list, the list seems to be prematurely ended.

If the list has several levels, Doxygen prints a warning because the items after the verbatimn blocks are not a valid list (in the example this is for list 2). However, if the list has only one level, no warning is generated (e.g. list 4).

See the "cases" directory
[Doxygen Bug XXXX.zip](https://github.com/doxygen/doxygen/files/3451737/Doxygen.Bug.XXXX.zip)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
