### ISSUE TITLE
Doxygen 1.8.15 TOC_INCLUDE_HEADINGS >0 stops html links being generated in markdown

### ISSUE THREAD

**Issue by gkim-at** [doxygen/doxygen#7151]
[issue7151.zip](https://github.com/doxygen/doxygen/files/3455746/issue7151.zip)

Edit: please disregard the description below, it's incomplete and won't reproduce the issue. Instead, refer to the attached .zip for a self-contained example reproducing it. Contains a symbolic link (MAIN_README.md -> README.md).

---------

Given a config including:

    FILE_PATTERNS = *.md
    RECURSIVE = YES
    USE_MDFILE_AS_MAINPAGE = MAIN.md
    TOC_INCLUDE_HEADINGS = 0

The following MAIN.md gets links generated for html output:

```markdown
The Main Page {#mainpage}
===

Some text

# Title 1

## Title 1.1

# Title 2

- [page1](folder1/SUB.md)
- [page2](folder2/SUB.md)
- [page3](folder3/SUB.md)
```

Setting TOC_INCLUDE_HEADINGS to e.g. 3 causes `unable to resolve reference to 'folder#/SUB.md' for \ref command` warnings to be output and the links don't get generated in the html.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent. At the moment only the `MAIN.md` and `Doxyfile are present.

**Comment by gkim-at** [comment]
Curious, the issue needed a somewhat more specific situation than I thought. I've edited the original post with the requested self-contained example which uses different filenames. It includes a symbolic link (`MAIN_README.md -> README.md`) as a workaround for `USE_MDFILE_AS_MAINPAGE = README.md` complaining `warning: found more than one \mainpage comment block!`

**Comment by albert-github** [comment]
The problem regarding the `warning: found more than one \mainpage comment block!` when `README.md` is set as `USE_MDFILE_AS_MAINPAGE` can easily be overcome by means of:
`USE_MDFILE_AS_MAINPAGE=./README.md` 
otherwise all `README.md` are seen as 'mainpage'. When one has one's uniquely named mainpage in a sub-directory it is not necessary to specify the path, by specifying the path it is unique. In this case, without the path specified, doxygen finds multiple mainpages and cannot decide which one is the right one.
Another possibility is just to leave the `USE_MDFILE_AS_MAINPAGE` empty as yo already indicate in the file that `README.md` on the main directory is the 'mainpage'.

This all in case `TOC_INCLUDE_HEADINGS   = 0`, the case `TOC_INCLUDE_HEADINGS   = 3` with the `unable to resolve reference to` is outstanding.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7153 for the `\ref` problem.
The mainpage problem is in my opinion, see my previous comment, usage

**Comment by gkim-at** [comment]
I confirm the mainpage problem was a matter of usage. Thank you for showing me the proper usage and for the proposed patch.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by gkim-at** [comment]
Thank you for the fast turnaround.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by qknight** [comment]
I'm using doxygen 1.8.17 and I still get this error with this setup:

`DOXYGEN: /home/joschie/Projects/multicontrol/README1.md:10: error: unable to resolve reference to 'lib/spdlog/README.md' for \ref command (warning treated as error, aborting now)`

# Doxyfile

```
MARKDOWN_SUPPORT       = YES
FILE_PATTERNS = *.cpp *.md *.h *.hpp
USE_MDFILE_AS_MAINPAGE = README1.md
TOC_INCLUDE_HEADINGS=0

```
# README1.md
```
hello world
============

* foo
* bar

## SPDLOG based logging

[lib/spdlog/README.md](lib/spdlog/README.md)
```

I also tried:

 USE_MDFILE_AS_MAINPAGE=./README1.md

But it did not work either. Also there is only one README1.md in the whole repository so not sure if it is actually required.

**Comment by albert-github** [comment]
@qknight 
In your issue you specify the `Doxyfile` and `README1.md` but I don't see the `lib/spdlog/README.md`.
When I define `lib/spdlog/README.md` and add the file to the `INPUT` setting I don't get an error anymore and the output looks OK.

When the above doesn't hold for you:
- please create a new issue with:
   - attached a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
   - for completeness mention there also the doxygen version you used.

**Comment by qknight** [comment]
@albert-github I've created a new issue at https://github.com/doxygen/doxygen/issues/8182 as you asked! Thanks!
