### ISSUE TITLE
warning: documented symbol was not declared or defined (triggered by \internal)

### ISSUE THREAD

**Issue by marcolaz** [doxygen/doxygen#7173]
Havin a documented member function marked as internal in the header file triggers the warning
'documented symbol `...' was not declared or defined

This is a minimal source file that triggers the wrong warning:
[documented_symbol_not_declared.zip](https://github.com/doxygen/doxygen/files/3482150/documented_symbol_not_declared.zip)

**Comment by albert-github** [comment]
When we look at the code we see that in the class part the method `someInternalFunction` is in a `\cond ... \endcond` block. The mentioned code is "removed" from the code in a early stage what can be seen when using: `doxygen -d preprocessor` which results in:
```
Preprocessor output (size: 199 bytes):
---------
00001
00002 //! \brief Just a class
00003 class someClass
00004 {
00005 public:
00006   //! \brief Documented constructor
00007   someClass();
00008
00009   /** */
00010
00011
00012
00013
00014
00015 /**  */
00016 };
00017
00018
00019 someClass::someClass()
00020 {
00021 }
00022
00023 void someClass::someInternalFunction()
00024 {
00025 }
00026
---------
```

When also placing the implementation in a `\cond ... \endcond` block (so lines 23 .. 25 we again have a symmetric situation.

I think this problem is usage.

**Comment by marcolaz** [comment]
I agree on misuse, but the word 'documented' in the message '*documented* symbol was not declared or defined' is somewhat misleading.
The message is the same, if we add a method like
`void someClass::notDefinedFunction()
{
}`
without any prior declaration.
Writing 'documented' in the warning message only if there is doxygen documentation before the function definition would help finding the problem.
