### ISSUE TITLE
Incorrect year in About window

### ISSUE THREAD

**Issue by kinnder** [doxygen/doxygen#7182]
It is 2019 but the "Help->About" window stills shows 2015

Should it be updated to current release year?

![png](https://user-images.githubusercontent.com/18032398/62863135-9d6fff80-bd10-11e9-8924-9f5bb0a66d4c.png)

**Comment by doxygen** [comment]
@kinnder good point. I've fixed it with [this commit](https://github.com/doxygen/doxygen/commit/80bbd1796e410d1822e16833bcf6002692ff54df).

**Comment by albert-github** [comment]
Please don't close the issue as this will be done at the moment of a release

**Comment by albert-github** [comment]
@doxygen why only the source files in the doxywizard directory and not also in e.g. src, libversion, other addon directories?

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
