### ISSUE TITLE
C++ alignment attributes cause "documented symbol was not declared or defined" warnings

### ISSUE THREAD

**Issue by nomis** [doxygen/doxygen#7249]
If I have an alignment attribute on a C++ static variable, doxygen generates a spurious warning.

test1.cpp:
```
static constexpr const char *a __attribute__((__aligned__(sizeof(int)))) = "42";

static constexpr const char *b[1] __attribute__((__aligned__(sizeof(int)))) = {
	a
};
```

test2.cpp:
```
static constexpr const char *c = "42";

static constexpr const char *d[1] = {
	c
};
```

The warning only occurs for file 1:
```
$ doxygen --version
1.8.13
$ doxygen -g - | doxygen - >/dev/null
test1.cpp:3: warning: documented symbol `static constexpr const char * b' was not declared or defined.
```

**Comment by albert-github** [comment]
The problem here is the unknown `__attribute__` which is not a standard. To be able to process it the `__attribute__`  has to be defined as: 
 `PREDEFINED             = __attribute__(x)=`
 further the setting
`MACRO_EXPANSION        = YES`
is required.

In the example `__aligned__` is unknown as well but doesn't need to be defined as it is part of the `__attribute__` (and thus filtered by means of the `__attribute__` setting)..

See also the preprocessing chapter in the documentation: http://www.doxygen.nl/manual/preprocessing.html

Note to see the static variables / functions the following setting is required:
`EXTRACT_STATIC         = YES`

I think the problem is usage.

**Comment by nomis** [comment]
> Note to see the static variables / functions the following setting is required:
> `EXTRACT_STATIC = YES`

The default is `NO` and doesn't stop the warning occurring.

The error message isn't very helpful because it claims the symbol is documented (when it isn't) and that it's not declared or defined. If a symbol isn't declared or defined then it doesn't exist.

If it thinks that there's an `__attribute__(...)` function that it should be able to state that in the error message, but the syntax is wrong for that interpretation too.

Defining those macros in the configuration file stops the warning but the warning itself is nonsensical.
