### ISSUE TITLE
Doxygen documentation of C++17 nested namespace erroneous

### ISSUE THREAD

**Issue by craffael** [doxygen/doxygen#7295]
Consider the following [code snippet](https://github.com/doxygen/doxygen/files/3694354/Example.zip) with a C++17 nested namespace:
```
/** @brief second desc */
namespace First::Second {

}
```

The generated namespace page using doxygen 1.8.16, respectively current master:
![grafik](https://user-images.githubusercontent.com/15138672/66269318-623d0900-e847-11e9-99d6-fa70466de159.png) 
This is incorrect: The comment that was applied to namespace second is now shown for namespace first!

Note that this used to work in 1.8.14:
![grafik](https://user-images.githubusercontent.com/15138672/66269343-9dd7d300-e847-11e9-8486-25ad8f120830.png)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7296

**Comment by craffael** [comment]
That was fast, thanks!

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
