### ISSUE TITLE
Process @copybrief without adding extra formatting

### ISSUE THREAD

**Issue by ibytergj** [doxygen/doxygen#7298]
Please have a look at my stackoverflow post here - 

https://stackoverflow.com/questions/58194000/supress-formatting-after-copybrief?noredirect=1#comment102783334_58194000

Using doxygen version 1.8.16

**Comment by albert-github** [comment]
Please do not use a reference to an outside source (as it may not be persistence). Present your problem here:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
I took the example from the linked stackoverflow issue:
**foo.cs**
```
public class foo
{
   /// <summary>
   /// This is my comment. I do not want the space above it
   /// </summary>
   public void foobar()
   {
       Debug.Log("Foo");
   }
}
```
**foo.md**
```
foo.foobar() @copybrief foo.foobar()  
```

With the 1.8.16 version this gives:

![image](https://user-images.githubusercontent.com/5223533/221580415-b45a8a9c-7667-439c-a8dc-10e447ef5ec1.png)

and with the current 1.9.6 version:

![image](https://user-images.githubusercontent.com/5223533/221580492-88c78034-2991-455c-8767-6256caf13020.png)


So I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10840231/example.tar.gz)
