### ISSUE TITLE
How do I link to an example file

### ISSUE THREAD

**Issue by NeilZhy** [doxygen/doxygen#7317]
I generated a example file using the EXAMPLE_PATH tag, like this:
`EXAMPLE_PATH           = usecase/hello_world.cpp`.
It generates a web page which named "hello_world_8cpp-example.html".
How can i link to the hello_world_8cpp-example.html.
Thanks!

**Comment by albert-github** [comment]
Note that we are speaking here about a path so `EXAMPLE_PATH` should probably read `EXAMPLE_PATH = usecase`. Also have a look at the `\example` command in the documentation.

To be able to answer your question:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by NeilZhy** [comment]
The following is part of the file "Doxyfile":

`# Doxyfile 1.8.11

DOXYFILE_ENCODING      = UTF-8
PROJECT_NAME           = "HELLO"
PROJECT_NUMBER         = $(SDK_VERSION)
PROJECT_BRIEF          = "HELLO SDK"
PROJECT_LOGO           = $(SDK_DOC_PATH)/logo.png
OUTPUT_DIRECTORY       = $(SDK_DOC_INSTALL_PATH)
INPUT                  = $(SDK_API_PATH)/hello.h \
                                $(SDK_DOC_PATH) \
                                $(SDK_SAMPLE_PATH)/usecase/hello_world.cpp \
......
EXAMPLE_PATH           = $(SDK_SAMPLE_PATH)/usecase/hello_world.cpp`

And I want to link this file named "dms_example.cpp" in the Markdown.
The following is part of the file "Doxyfile":

`# Use cases
Here is a list of all samples:
- <a href="">dms_example.cpp</a> `

**Comment by NeilZhy** [comment]
The following is part of the file "Doxyfile":

`# Doxyfile 1.8.11

DOXYFILE_ENCODING = UTF-8
PROJECT_NAME = "HELLO"
PROJECT_NUMBER = $(SDK_VERSION)
PROJECT_BRIEF = "HELLO SDK"
PROJECT_LOGO = $(SDK_DOC_PATH)/logo.png
OUTPUT_DIRECTORY = $(SDK_DOC_INSTALL_PATH)
INPUT = $(SDK_API_PATH)/hello.h
$(SDK_DOC_PATH)
$(SDK_SAMPLE_PATH)/usecase/hello_world.cpp
......
EXAMPLE_PATH = $(SDK_SAMPLE_PATH)/usecase/hello_world.cpp`

And I want to link this file named "dms_example.cpp" in the Markdown with "href".

**Comment by albert-github** [comment]
Version 1.8.11 is a bit old (December 2015), the current version is 1.8.16, but this is probably of no influence to your question.

In your Doxyfie it looks like that you have:
```
INPUT = $(SDK_API_PATH)/hello.h
$(SDK_DOC_PATH)
$(SDK_SAMPLE_PATH)/usecase/hello_world.cpp
```
or is this one line, otherwise either make 1 line of it or place a backslash (`\`) at the end of the lines `INPUT = $(SDK_API_PATH)/hello.h` and `$(SDK_DOC_PATH) `.

Do you get any warnings from doxygen when you run it?

Please show some code (!):
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used (`doxygen -v`), probablu 1.8.11 but to be sure.

**Comment by NeilZhy** [comment]
The doxygen version is 1.8.11( `doxygen -v` ).
There is no warning from doxygen when I run it.
I want to link the `hello_world.cpp` in `Markdown` file, and the following is part of the `Markdown` file :

`
<a href="XXX">hello_world.cpp</a>
`
What should  fill in `XXX`.

**Comment by albert-github** [comment]
To answer your question read my requests for a small complete example. Maybe you can just us `\example hello_world.cpp` in your code,
 **BUT SHOW A SMALL COMPLETE EXAMPLE**.

**Comment by NeilZhy** [comment]
Doxyfie:

`
INPUT = $(SDK_API_PATH)/hello.h
               $(SDK_DOC_PATH)/README.md
               $(SDK_SAMPLE_PATH)/usecase/hello_world.cpp
`

README.md:

`
<a href="XXX">hello_world.cpp</a>
`

What should fill in `XXX` to link example hello_world.cpp?

**Comment by NeilZhy** [comment]
Doxyfie:

`
INPUT = $(SDK_API_PATH)/hello.h 
`
`
$(SDK_DOC_PATH)/README.md 
`
`
$(SDK_SAMPLE_PATH)/usecase/hello_world.cpp
`

README.md:

`
<a href="XXX">hello_world.cpp</a>
`

What should fill in `XXX` to link example hello_world.cpp?

**Comment by albert-github** [comment]
So multiple lines in your Doxyfile, but probably just 1 line but due to copy and paste  not shown properly here.

The best I can do with the limited information is:
- `<a href="hello__world_8cpp.html">hello_world.cpp</a>` look in the html directory 
- better would be to use: 
   - `\ref hello_world.cpp "hello_world.cpp"`.
   or
   -  `\ref usecase/hello_world.cpp "usecase/hello_world.cpp"`.
  the later will probably be a bit problematic due to the `$(SDK_SAMPLE_PATH)`

But please follow my advise about the small complete example, and **attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem** otherwise we cannot help you any further.

**Comment by NeilZhy** [comment]
`
<a href="hello__world_8cpp.html">hello_world.cpp</a>
`
That's the way I use it.

Why Doxygen uses `8cpp`?
Will `8cpp` change in future releases?

**Comment by albert-github** [comment]
It might change in the future but it is not likely. It is used so that there are no characters in at that are not possible in some type of links or on other places, in this case the `.` is replaced by the `_8` and the `_` in `__`, therefore it is advised to use `\ref` construct where doxygen makes the effort to create a correct link. Also when using `CREATE_SUBDIRS` the file will land on a subdirectory and one has to search for it and when using other output formats, like LaTeX, RTF, ..., it will give problems.

**Comment by NeilZhy** [comment]
`
EXAMPLE_PATH           = $(SDK_SAMPLE_PATH)/usecase/example.cpp
`
If I want to link to the EXAMPLE file, how should I use it in Markdown?

**Comment by NeilZhy** [comment]
> Doxyfile:
> 
> `INPUT = $(SDK_API_PATH)/hello.h `
> `$(SDK_DOC_PATH)/README.md `
> `$(SDK_SAMPLE_PATH)/usecase/hello_world.cpp`
> 
> README.md:
> 
> `<a href="XXX">hello_world.cpp</a>`
> 
> What should fill in `XXX` to link example hello_world.cpp?

The above is modified as follows:

`INPUT = $(SDK_DOC_PATH)/README.md `
`EXAMPLE_PATH = $(SDK_SAMPLE_PATH)/usecase/hello_world.cpp`

**Comment by albert-github** [comment]
I have an idea (`\include` or `\snippet`) but please reformulate your question to make it more clear to show what you want, also actually issues are for problems in doxygen not for usage question, this is more suitable on https://stackexchange.com/

**Comment by NeilZhy** [comment]
Thank you for your help. This problem has been solved successfully.
