### ISSUE TITLE
AUTOBRIEF not picking up first line of include{doc} file

### ISSUE THREAD

**Issue by skierkit** [doxygen/doxygen#7336]
I use include{doc} to add auto-generated TCL proc help text and arguments. I'd like the first line to be used as brief whenever the @include{doc} is called first.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by skierkit** [comment]
I am using Doxygen 1.8.15. Let me put together a small example.

**Comment by skierkit** [comment]
[github_7336_testcase.tar.gz](https://github.com/doxygen/doxygen/files/3744512/github_7336_testcase.tar.gz)

**Comment by albert-github** [comment]
In the documentation of the `\include` command there is already the warning:

> Note
> Some that when using the {doc} option, commands like \cond and \if don't work with this command due to the moment of parsing.

Looks like that `@brief` is another one.

**Comment by albert-github** [comment]
Some separate remarks regarding the code form / configuration file:
- In the Doxyfile tou specified as FILE_PATTERN also `*`, this has some nasty effects as this means that (in combination with `RECURSIVE`) all files are evaluated.
- you use `## #################` as start of comment, due to the markdown support the `#################` this leads to a dummy `<h6></h6>` entry in the conversion and the output.

**Comment by albert-github** [comment]
• By means of commit 58ea5cf320f08ae2ec3e5fbd02d82ca0ba4477a7  the support has been removed from doxygen.
