### ISSUE TITLE
Doxyfile, worked on 1.8.5 , does not work on 1.8.16.

### ISSUE THREAD

**Issue by smavridis** [doxygen/doxygen#7354]
Hello, i have been using Doxygen in a C/C++ project for a few years.

Recently after an update i tried generating my documentation.
I noticed that the generated documentation was as if no files were found/parsed.
No files/classes/index tabs were generated, and the html folder only contained 2 html files (graph_legend.html  index.html).

This behavior happens with version 1.8.16 on ArchLinux.

Running an older version/setup ( doxygen 1.8.5 , CentOS ) on the same files, creates the full documentation as expected ( ~1800 html files generated ).

A version of the project that exhibits the problem can be found here:

https://github.com/vineyard2020/vine_talk

To build the documentation, go to the 'docs' sub-folder an type make.

I hope i have provided enough information, if not let me know.

**Comment by albert-github** [comment]
The problem is caused by an empty FILE_PATTERNS setting, this should automatically be filled by all doxygen known extensions but is in 1.8.16 not the case.
The problem has been noted as #7190 and been fixed in master by #7193
Workaround for 1.8.16 is to list the required / all extensions.

So it think the problem is a duplicate and fixed but not released.

**Comment by smavridis** [comment]
@albert-github  Yep your workaround works. Thank you for your (very) fast response.
