### ISSUE TITLE
1.8.16: function-like macros generate warnings

### ISSUE THREAD

**Issue by skypjack** [doxygen/doxygen#7456]
`doxygen` version 1.8.16 started to generate random (wrong) warnings for function-like macros.
The previous version (1.8.15) worked as expected instead.

Here is the code required to reproduce the error:
```
namespace bar {

/**
 * @brief macro   
 * @param clazz class
 * @param type type
 */
#define MY_ENUM(clazz, type) enum clazz: type {}

/*! @brief desc */
MY_ENUM(quux, int);

}

/**
 * @namespace bar
 * @brief my namespace
 */
```

Put it in a `foo.hpp` file, generate a config file with `doxygen -g` and set `WARN_NO_PARAMDOC` to `YES`. Then `doxygen Doxyfile` and this is what you obtain:

>foo.hpp:11: warning: return type of member bar::MY_ENUM is not documented

Note that the error disappears if you remove the documentation for the namespace.
I put it after everything else rather than inline on the namespace declaration to simulate the fact that I've it in a separate file.

---

This may be but isn't necessarily related to #7451 since the two errors appeared in the same version of `doxygen` and the error messages are very similar.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
