### ISSUE TITLE
Perlmod does not generate "kind" information to discriminate ANSI-C struct/union

### ISSUE THREAD

**Issue by DGA45** [doxygen/doxygen#7547]
When using PerlMod with ANSI-C code, the struct/union are generated as "classes".
However, they are missing the "kind" attribute which can be used to discriminate if this is a "struct" or a "union" (as it is correctly done in the XML output).

**Comment by albert-github** [comment]
Even though you already provided a proposed path and perlmod is not used often / hardly maintained it would be useful to give a small example:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by DGA45** [comment]
Here are an example
[Doxy issue 7547 and 7556 examples.zip](https://github.com/doxygen/doxygen/files/4147430/Doxy.issue.7547.and.7556.examples.zip)

**Comment by albert-github** [comment]
In the current version of doxyfen (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) the mentioned `kind` fields are present whilst in the version 1.8.20 (f246dd2f1c58eea39ea3f50c108019e4d4137bd5) they were missing.

I think this issue was not set to solved when the pull request #8145 was merged.

I think the problem has been solved in the mean time.
