### ISSUE TITLE
Doxygen command ignored if spaces after a leading # character

### ISSUE THREAD

**Issue by hemberger** [doxygen/doxygen#7581]
A change occurred in the parser in version 1.8.16 (which persists in 1.8.17) where doxygen commands behind a leading comment character `#` are no longer registered.

Here is an example snippet. Note that this is a custom file type, but the C++ parser is used because it gave the expected output prior to 1.8.16, and there did not seem to be a better alternative.

```
# /**
# \verbatim

Some custom formatted code

# \endverbatim
# */
```

In 1.8.16, this snippet can still be made to work, but _only_ if there are no spaces between the `#` characters and the doxygen commands, i.e.:
```
#/**
#\verbatim

Some custom formatted code

#\endverbatim
#*/
```
This leads me to a couple questions:
1. Is this an intentional change or a bug? I can understand if this snippet was relying on an implementation detail of the C++ parser.
2. Is there a better (or "proper") way to doxygenize a file like this with a custom language that uses `#` for comment characters, or can I rely on the C++ parser to continue to behave as it does in 1.8.16+? I tried the tcl parser, but that did not correctly include the verbatim section.

Thanks!

**Comment by albert-github** [comment]
As you have a special use here as you wrote: "Note that this is a custom file type, but the C++ parser is used because it gave the expected output prior to 1.8.16, and there did not seem to be a better alternative."

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by hemberger** [comment]
[doxygen-issue7581.zip](https://github.com/doxygen/doxygen/files/4194574/doxygen-issue7581.zip)

@albert-github Thanks for the quick response!

I'm attaching a minimal example that reproduces this issue. Just run `doxygen Doxyfile`.

With doxygen 1.8.15 or lower, I get a file `html/group__ExampleTree.html`. With doxygen 1.8.16 or higher, I don't get this output file (unless I remove the spaces between all `#` and `\<doxygen command>` as specified in the original report).

**Comment by albert-github** [comment]
I think we have to do even one step further back to version 1.8.14.
I used the `example.tree` from your example and created another file with similar content, just removing the space between the `#` and the `\`.
In all versions as shown below the version without the space gives some, reasonable, result.

- in version 1.8.14 we see that both files give the same results
- in version 1.8.15 we see that the file with the space gives some very strange output and we get the warnings:
  ```
  .../doxygen-issue7581/example.tree:3: warning: Illegal command @verbatim as part of a <h1>tag
  .../doxygen-issue7581/example.tree:23: warning: Illegal command \endverbatim as part of a <h1>tag
  .../doxygen-issue7581/example.tree:26: warning: Unexpected end of comment while inside <h1> tag
  ```
- in version 1.8.16 / 1.8.17 we don't get any output (as you indicated) from the version with the spaces.

Since version 1.8.14 the handling of the markdown information has changed. Disabling the markdown support (`MARKDOWN_SUPPORT=NO`) results in the same results (for all mentioned versions) between the version with and without the space.
I don't think it is advisable the disable the markdown support, but it is much better to have a look at the  `FILTER_PATTERNS` (and `INPUT_FILTER`) configuration possibilities to remove the leading `#`.

**Comment by hemberger** [comment]
Hi @albert-github, I very much appreciate the quick response. I went the route of using `FILTER_PATTERNS` and writing a short script to strip the leading `#` on specific lines. It's not a perfect solution, but it is workable.

For my purposes, this issue is resolved. Thank you!
