### ISSUE TITLE
Add Markdown todo list

### ISSUE THREAD

**Issue by dolibarr95** [doxygen/doxygen#7589]
Hello !
The markdown checkboxes are not supported in doxygen, could it be?
http://www.doxygen.nl/manual/markdown.html
example

- [ ] todo
- [x] done

Tks for reading

**Comment by albert-github** [comment]
Checkboxes are not part of the original definition of MarkDown (https://daringfireball.net/projects/markdown/syntax), but (as far as I know an extension on e.g. github).
In doxygen they are just shown as `[ ]` / `[x]`.

As far as I can see the checkboxes are only supported as a special case of the list items (i.e `- [ ]` or `- [x]`).

In case I'm mistaken please correct me with an authoritative reference.

**Comment by dolibarr95** [comment]
Hello
Tks for this quick answer.
You're right checkboxes are not in the official Markdown def:
https://www.markdownguide.org/basic-syntax/

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7602

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
