### ISSUE TITLE
Map .f18 filetype to Fortran

### ISSUE THREAD

**Issue by thenlich** [doxygen/doxygen#7590]
Besides others, the .f95, .f03 and .f08 file types (Fortran 95, Fortran 2003 and Fortran 2008, respectively) are mapped to Fortran.

There is a newer standard: Fortran 2018. Programmers can now use the .f18 suffix, if the compiler supports it. Reference: https://pubs.cray.com/content/S-3901/9.1/cray-fortran-reference-manual/invoke-the-cray-fortran-compiler

The .f18 should also be mapped to Fortran.

**Comment by albert-github** [comment]
By means of the configuration setting `EXTENSION_MAPPING` the `f18` extension is, of course, already supported.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7591

**Comment by thenlich** [comment]
doc/starting.doc needs to be updated as well.

**Comment by albert-github** [comment]
Done as well.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
