### ISSUE TITLE
Some special commands do not work with Python source code when OPTIMIZE_OUTPUT_JAVA is YES

### ISSUE THREAD

**Issue by safakoner** [doxygen/doxygen#7597]
Hi, 

The following commands do not work in Python source code when `OPTIMIZE_OUTPUT_JAVA = YES` in version `1.8.17`.

- `@package`
- `@dir`
- `@file`

Rest of the commands seem to work, such as `@brief`, etc.

They work in version `1.8.14` when I use `OPTIMIZE_OUTPUT_JAVA = YES` as usual though.

[Screenshot with `1.8.17`](https://drive.google.com/open?id=1Bvux-wQUDF0EjKCiEIVX6doS3V578R3d)

[Screenshot with `1.8.14`](https://drive.google.com/file/d/1MJEepInmWB4p_pNdI2vIGmhdnIfWImF2/view)

Thanks

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by safakoner** [comment]
Please see the attached archive. 

Config file is under `/doc/developer/pythonAPIReference` folder.

Generated files are in `/doc/developer/pythonAPIReference/html` folder.

1.8.14 result:

![Screen Shot 2020-02-15 at 9 05 12 AM](https://user-images.githubusercontent.com/19718469/75833185-1ac29680-5d6d-11ea-9ce4-71996e1018f0.png)

1.8.17 result:

![Screen Shot 2020-02-15 at 9 04 41 AM](https://user-images.githubusercontent.com/19718469/75833195-231ad180-5d6d-11ea-9689-08e68067125d.png)

Thanks!

[sFileSystem.zip](https://github.com/doxygen/doxygen/files/4284367/sFileSystem.zip)

**Comment by albert-github** [comment]
As a side note.
You have a number of warnings:
```
.../sFileSystem/python/sFileSystem/directoryLib.py:137: warning: unbalanced grouping commands
.../sFileSystem/python/sFileSystem/fileLib.py:187: warning: unbalanced grouping commands
.../sFileSystem/python/sFileSystem/jsonFileLib.py:82: warning: unbalanced grouping commands
.../sFileSystem/python/sFileSystem/templateFileLib.py:96: warning: unbalanced grouping commands
```
this is due to the fact that the handling of the  `@{` and `@}` has been corrected. In the past `# @{` as start comment block was accepted as well, but these are only normal comments and thus should have been skipped by doxygen, changing the `# @{` to `## @{` solves this issue.

**Comment by albert-github** [comment]
The problem is caused by:
```
Commit: f643a0e4701e9d44cddd8d2f59ec6830d52c74d4 [f643a0e]
Parents: 80bcb70004
Author: albert-github <albert.tests@gmail.com>
Date: Wednesday, May 8, 2019 12:16:59 PM
Committer: albert-github
issue #6945 \class after \brief doesn't count as a new line - resulting docs show merged descriptions

Set  "ends brief description" for the different for the commands mentioned in issue (as well as addtogroup)
```

where the handling of different commands has been adjusted. The purpose was that a command like `\package` doesn't have any meaning in a brief description (same accounts for `\file`  and other mentioned commands). It looks like here the brief description of the current item is not shown anymore instead of termination a possible previous brief description.

A workaround is to place explicitly `\brief` before the `[ MODULE ]` etc., but this is not really intended.

**Comment by safakoner** [comment]
Hi Albert, 

Sorry for replying late. Thank you very much for your time and comments. Indeed it works properly after I made the changes you referred to.

Cheers!
