### ISSUE TITLE
EXPAND_MACRO does not work as expected

### ISSUE THREAD

**Issue by disa6302** [doxygen/doxygen#7695]
I have this definition: 

`#define FIRST_ARG                         0x1000`
`#define SECOND_ARG                      FIRST_ARG + 0x01`

I have set the following in Doxyfile:

`ENABLE_PREPROCESSING   = YES`
`MACRO_EXPANSION        = YES`
`EXPAND_ONLY_PREDEF     = NO`
`SEARCH_INCLUDES        = YES`

I would like to see `SECOND_ARG` to be expanded as 0x1001. But the HTML document still shows `SECOND_ARG FIRST_ARG + 0x01`. 

I am not sure why the expansion does not work.
`doxygen` -v
`1.8.17`

**Comment by doxygen** [comment]
It works but you probably have different expectations.

Consider the following example
```c
#define FIRST_ARG 0x1000
#define SECOND_ARG FIRST_ARG + 0x01

/** @file */
#if SECOND_ARG==0x1001
/** yes */
void yes_it_works(int first=FIRST_ARG,int second=SECOND_ARG);
#else
/** This should be ignored */
void i_need_to_be_ignored();
#endif
```

If `ENABLE_PREPROCESSING` is set to `YES` the `i_need_to_be_ignored` function does not appear. If it is set to `NO` it will appear because no preprocessing is done.

If `MACRO_EXPANSION` is set to `YES`, the parameter defaults will be replaced by the value of the macro (for `SECOND_ARG` this will be `0x1000+0x01`, not `0x1001`!). If it is set to `NO`, the macro name will appear.

The macro expansion will only happen where the macro is used, not for the macro definition itself.

**Comment by disa6302** [comment]
Thank you for the response @doxygen ! 

Is there any way the macro definition could be expanded using Doxygen?
I have a use case where I would like the macro definition to be expanded recursively so that the value is visible directly to the reader of the doxygen html page.
