### ISSUE TITLE
warning: documented symbol `static bool (long-winded C++ type)' was not declared or defined.

### ISSUE THREAD

**Issue by svarshavchik** [doxygen/doxygen#7727]
No complaints from gcc 9 for the attached code, with -std=c++17, but doxygen emits the following warning:

/tmp/doxygen/test.cpp:19: warning: documented symbol `static bool sfinae< T, std::enable_if_t<(sizeof(T)+0 *sizeof(decltype(std::to_chars(nullptr, nullptr, std::declval< T && >()))) >1)> sfinae >::yes' was not declared or defined.

I started incrementally dropping some of the C++ goo, until the point where doxygen stopped complaining.

At this point the warning still exists:

`template<typename T> struct sfinae<T,std::enable_if_t<(sizeof(T) > 1)>> {
`

But at this point, the warning goes away:

`template<typename T> struct sfinae<T,std::enable_if_t<true>>
`
I think it's the `>` in the template parameter value expression, that's causing this confusion.
[doxybug.tar.gz](https://github.com/doxygen/doxygen/files/4534338/doxybug.tar.gz)

**Comment by albert-github** [comment]
Fixed by means of aa89f8773a50887ad20fbf683ff3c9af38c8fc5e  (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
