### ISSUE TITLE
Need an example that generate `js` API.

### ISSUE THREAD

**Issue by 625781186** [doxygen/doxygen#7780]
I found a js demo use doxygen , 
but I can't generate document.

https://github.com/schteppe/ammo.js-demos

ZIP  FILE  :
[ammo.js-demos-masterV1.zip](https://github.com/doxygen/doxygen/files/4639737/ammo.js-demos-masterV1.zip)

## js file
![image](https://user-images.githubusercontent.com/30521429/82137031-ab762200-9846-11ea-88bd-40a95262d13f.png)

## doxy config
![image](https://user-images.githubusercontent.com/30521429/82137058-027bf700-9847-11ea-8710-6c651b2d7391.png)

## cmd
Manually use the `js2doxy.pl` input_filter conversion.

![image](https://user-images.githubusercontent.com/30521429/82137073-453dcf00-9847-11ea-9184-8959c0b91698.png)

## result
It's empty.
doxygen version : 1.8.17

![image](https://user-images.githubusercontent.com/30521429/82137109-96e65980-9847-11ea-8dbe-2a92f48468a8.png)

**Comment by albert-github** [comment]
Looking at the mentioned project (ammo.js-demo / the attached zip file) it doesn't look like the `js2doxy.pl` is used. You will probably need this file as a FILTER setting and not as a standalone file  (and don't forget to set EXTENSION_MAPPING).
In case there is no output from the script it might be that there is no recognized construct / that the script contains omissions.  

The jsdoxy.pl script is not something that is maintained by doxygen and as such I don't think this is a doxygen problem.

**Comment by 625781186** [comment]
> Looking at the mentioned project (ammo.js-demo / the attached zip file) it doesn't look like the `js2doxy.pl` is used. You will probably need this file as a FILTER setting and not as a standalone file (and don't forget to set EXTENSION_MAPPING).
> In case there is no output from the script it might be that there is no recognized construct / that the script contains omissions.
> 
> The jsdoxy.pl script is not something that is maintained by doxygen and as such I don't think this is a doxygen problem.

Can you directly provide a ready-made example?
 I have been looking for a long time, but I couldn't find it.

**Comment by albert-github** [comment]
I had a bit of a look at the mentioned project with the input file (in the `temp` directory): `DemoApplication.js` and I used the doxygen version 1.9.1
This doesn't look like a `.js` file at all, but more a `cpp` file. To obtain documentation from for this file it is sufficient to set the EXTENSION mapping correctly:
```
EXTENSION_MAPPING      = js=C++
```

When we want to run real `js` code the following, extra, settings have to be done:
```
EXTENSION_MAPPING      = js=C++
FILTER_PATTERNS        = *.js=./doxygen-js-filter
```

We assume that the file `doxygen-js-filter` is in the mentioned directory and has as content
```
/usr/bin/perl ./js2doxy.pl $*
```
(can, of course, also be a full qualified path and when using on windows it might be a little bit different with a bat file)

Note:
- the file `js2doxy.pl ` is not provided by doxygen and errors etc. in it will not be fixed by doxygen.
- the mentioned project seems a bit dead as there hasn't been any activity for a long time.


So the mentioned problem is usage.
