### ISSUE TITLE
How to write special symbols in doxygen code special comment blocks

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#7835]
I have tried all ways to write a symbol °C in my source code annotations for doxygen feed 

i am getting errors please help me how to write the °C symbol 

/** The temperature in °C */
to create a pdf document

please help me how i can write that

**Comment by albert-github** [comment]
In your previous issues we already wrote:
-    Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
-    Please also specify the doxygen version used.

Furthermore questions like these are more suitable to be posted at https://stackexchange.com 

Please have a look in the documentation Chapter "HTML Commands" (https://www.doxygen.nl/manual/htmlcmds.html), part "The special HTML4 character entities".
Here you will also find a possibility for the degrees symbol.

I think this problem is usage.

**Comment by KITTUKRISHNA5** [comment]
My Sincere apologies , Thank you for the replies and  I admire your patience  

As you suggested I have gone through HTML commands but as I am working to generated a .pdf files from Latex file created by doxygen parsing I don't think it will work for me

and posting my questions in stack exchange will not come back with answers so I believe you are the right place to get good and quick suggestions


Here I am sharing the requested info:
doxygen version=1.8.11

**Comment by KITTUKRISHNA5** [comment]
Please find attached file i have only kept one function definition for which doxygen parsing is not behaving correctly with special symbols
[zip.zip](https://github.com/doxygen/doxygen/files/4743940/zip.zip)

**Comment by albert-github** [comment]
- the given example has again the problems regarding the configuration file as mentioned earlier issues (missing included file and extra files in `INPUT` settings tag) 
- 1.8.11 is old (December 2015)
- My experience with stackoverflow is very positive, provided the right questions and understandable questions are asked.

With version 1.8.11 I also have problems when using the degree symbol (which is still in your code) but also when using the replacement `&deg; with version 1.8.18 I don't have any problem.

So the advise is to upgrade to a newer version of doxygen (at least 1.8.16)
