### ISSUE TITLE
Typo in xmlcmds.doc XML tags moved to Appendix D of Ecma-334

### ISSUE THREAD

**Issue by d-c-d** [doxygen/doxygen#7855]
**Describe the bug**
docs/xmlcmds.doc indicates that XML tags are in Appendix E

Need to reflect new location of XML docs in "latest" 5th Edition / December 2017
"latest" is https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf

**Expected behavior**
Expect to see
 The XML tags are defined in Appendix D of the ECMA-334 standard, which defines the C# language. 

**To Reproduce**
Observe incorrect information (appendix 5) in doc/xmlcmds.doc 

**Version**
See source 47fee38 on Oct 1, 2018

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
