### ISSUE TITLE
Update documentation of USE_PDFLATEX option

### ISSUE THREAD

**Issue by septatrix** [doxygen/doxygen#7865]
Currently it is only possible to specify if a custom latex command should be run or pdflatex. However it is not possible to have `USE_PDFLATEX` set to `YES` and specify `LuaLaTeX` or `XeLaTeX` as the engine.

**Comment by albert-github** [comment]
Which version of doxygen are you using?

With the current version of doxygen it is possible to specify in `LATEX_CMD_NAME` the name of the LaTeX engine like `xelatex` and this will set the variable `LATEX_CMD` to e.g. `xelatex` in the file `Makefile` / `make.bat`.

This behavior is present since version 1.8.15 (current version is 1.8.18).

Did I understand the issue correctly or are you using a version that is old?

**Comment by septatrix** [comment]
As far as I can tell from looking at the [Makefile template](https://github.com/doxygen/doxygen/blob/master/templates/latex/latexmakefile.tpl) specifying `LATEX_CMD_NAME` is only relevant when generating the pdf file with an intermediate ps and dvi file. When directly producing the pdf file pdflatex seems to be hardcoded.

**Comment by albert-github** [comment]
The `latexmakefile.tpl` is currently not used in the doxygen code, so the `Makefile` nor the `make.bat` is derived from it. The `Makefile` and `make.bat` are completely generated in `latexgen.cpp`.

Please specify the version of doxygen you are using (`doxygen -v`).

**Comment by septatrix** [comment]
The version is `1.8.13` (Debian buster server). I did not knew it changed in newer versions as I generated a new config file on my local computer `1.8.17` (Ubuntu 20.04 LTS) and the explanation text was not very clear. Maybe care to update the generated config file so it states that the custom latex cmd ist also used when enabling pdflatex mode?

**Comment by albert-github** [comment]
Indeed the documentation (which is the same text as generated both times from `config.xml`) is not clear about this:
> USE_PDFLATEX
>If the USE_PDFLATEX tag is set to YES, doxygen will use pdflatex to generate the PDF file directly from the LATEX files. Set this option to YES, to get a higher quality PDF documentation.
>The default value is: YES.
>This tag requires that the tag GENERATE_LATEX is set to YES.

**Comment by septatrix** [comment]
I guess the name also does not exactly reflect what the option does anymore though anything but adding a new alias would be backwards incompatible.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7869

**Comment by septatrix** [comment]
The updated text seems good. Adding an alias and deprecating the current option name may be a point for a future release but with this change I am satisfied so far :D

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
