### ISSUE TITLE
Internal search engine produce ".html" pages instead of using HTML_FILE_EXTENSION

### ISSUE THREAD

**Issue by luca-aep** [doxygen/doxygen#7898]
While generating the built-in client side search engine (SEARCHENGINE = YES ; SERVER_BASED_SEARCH = NO ; EXTERNAL_SEARCH = NO) doxygen generates files with extension fixed to ".html" instead of using the one specified by HTML_FILE_EXTENSION.

Looking at doxygen-1.8.18 source code, affected code should be:
- line 959 of src\searchindex.cpp
- line 1271 of src\searchindex.cpp
- line 350 and 356 of templates\html\search.js

**Comment by luca-aep** [comment]
I propose this patch (done starting from tag Release_1_8_20).

[patch.zip](https://github.com/doxygen/doxygen/files/5209049/patch.zip)

**Comment by albert-github** [comment]
Can you convert your patch into a pull request here on github?

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
