### ISSUE TITLE
Help for CLANG_DATABASE_PATH is misleading

### ISSUE THREAD

**Issue by Bagira80** [doxygen/doxygen#7921]
Currently, the help for `CLANG_DATABASE_PATH` says that this setting must be 
> *"the path to the compilation database used when the files were built."*

However, that is not correct. It must be 
> *"the path to the  **directory** which contains the compilation database used when the files were built."*

Actually, it would be even more correct to say that it must be
> *"the path to the **directory** which contains **a file called `compile_commands.json`, which is** the compilation database  used when the files were built."*

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
