### ISSUE TITLE
Doxygen doesn't stop on errors

### ISSUE THREAD

**Issue by JanDorniak99** [doxygen/doxygen#7970]
Doxygen (1.8.17) doesn't stop when error occurs (e.g. `EXAMPLE_PATH=<wrong_path>`). I think it should be possible to choose if it crashes or not after error. Interestingly it works fine with warnings treated as errors. With `WARN_AS_ERROR` flag it crashes when any warning occurs, but never crashes with normal errors.

COMMAND:
`${DOXYGEN_EXECUTABLE} " ${CMAKE_CURRENT_BINARY_DIR}/libpmemobj++.Doxyfile"`
LOG:
`error: source /home/nvms/Work/libpmemobj-cpp/examples/doc_snippets is not a readable file or directory... skipping.`

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7972

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.20.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
