### ISSUE TITLE
FILE_PATTERNS ignored

### ISSUE THREAD

**Issue by FoxOneReal** [doxygen/doxygen#7974]
**Describe the bug**
Doxygen is completely ignore FILE_PATTERNS settings. 

**Expected behavior**
Read files matching FILE_PATTERNS setting, do not read others

**Screenshots**
Output:
```
Doxygen version used: 1.8.19 (21742756bdcc961f1542d168e64e17ee30694b62)
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Searching for files in directory E:/Projects/doxygen
Reading and parsing tag files
Parsing files
Reading E:/Projects/doxygen/test2.md...
Building macro definition list...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
...
```
**To Reproduce**
Config:
```
FILE_PATTERNS          = *.aaa 
EXTENSION_MAPPING      = aaa=C
INPUT                  =
```
Current directory contains:
```
test1.aaa
test2.md
```
**Version**
1.8.19

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.20.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
