### ISSUE TITLE
\ref commands broken in markdown tables

### ISSUE THREAD

**Issue by mystery-moss** [doxygen/doxygen#7996]
**Describe the bug**
\ref commands within markdown tables are not resolved and generate an error in the doxygen build.

**Expected behavior**
References within markdown tables behave the same as those outside them.

**To Reproduce**

	/** @page page1
		Working ref: @ref page2
	
		Table with | broken ref
		---|---
		@ref page2 | _
	*/
	
	/** @page page2
		Foo
	*/

A project containing the above snippet (using the default configuration file produced with -g) exhibits the issue.
During build the following error is produced:
`example.dox:6: warning: unable to resolve reference to 'page2\ilinebr' for \ref command`
The generated HTML does not contain a hyperlink for the reference within the table.

**Version**
Observed in Windows 10, 64 bit  v1.8.20, 1.8.19. Not present in 1.8.18.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7998 

As an ugly workaround you could use `@ref page2 &zwj; | _`

**Comment by mystery-moss** [comment]
Great, thanks!

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
