### ISSUE TITLE
Add option to exit with non-zero exit code on warnings even if WARN_AS_ERROR is OFF

### ISSUE THREAD

**Issue by georg-emg** [doxygen/doxygen#8023]
Doxygen offers an option, WARN_AS_ERROR, that allows enforcing a no-warnings-allowed policy when generating documentation. However, when this option is set, processing stops at the first warning encountered. This forces the programmer into an endless loop of generating the docs, fixing the first warning, generarating the docs again, fixing the second warning etc. It would be helpful if doxygen would continue processing after warnings even with WARN_AS_ERROR set, and then just return a non-zero exit code at the end. This would allow the programmer to see and fix all warnings in one go even when WARN_AS_ERROR is set. This is analogous to the behaviour of modern compilers, which report as many errors as possible in a single compilation run.

**Comment by albert-github** [comment]
As far as I know the idea behind the `WARN_AS_ERROR` is that doxygen will stop directly so no further computer resources are lost. As soon as this happens the problem lies again with the programmer, who made the mistake, to correct the issue. Best is to fix this error (and when obvious similar warnings as well) and just run doxygen locally but without the `WARN_AS_ERROR` so all warnings are shown (probably placing them in `WARN_LOGFILE` and can be solved, before starting the complete build process again.

**Comment by georg-emg** [comment]
I understand the use case you describe, but it still makes it difficult to use doxygen in a modern continuous integration environment, where we currently have the choice of only logging a single (out of possibly dozens) of warnings, or of letting all warnings slip through unnoticed. This is because there is no way for the CI pipeline to determine whether there were warnings at all if `WARN_AS_ERROR` is `NO`, other than capturing the entire output and using some sort of heuristic on it. There is a reason why all compilers have moved to a strategy where compilation continues after an error, and why make, cmake, ninja etc. all have options to keep going after errors.

To preserve the existing behaviour, I suggest adding a new option instead, something like `FAIL_ON_WARNINGS`, that would return a non-zero exit code if any warnings occurred even if `WARN_AS_ERROR` is `NO`. [This thread](https://sourceforge.net/p/doxygen/mailman/message/34708445/) seems to suggest that this was already implemented at some point, but then (understandibly) rejected because it broke existing pipelines. But an option to reenable it would make implementing robust CI pipelines much easier, IMHO.

I will update the title of this issue to reflect this.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8197

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
