### ISSUE TITLE
Failed to build PDF documentation from "master" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [doxygen/doxygen#8094]
```
[154/154] Generating Doxygen Manual PDF.
FAILED: doc/CMakeFiles/doxygen_pdf
cd /home/elijah/SDA3/rpmbuild/BUILD/doxygen/3.11.2-x86_64-redhat-linux-gnu/latex && /usr/bin/cmake -E remove refman.tex && /usr/bin/cmake -E copy /home/elijah/SDA3/rpmbuild/BUILD/doxygen/3.11.2-x86_64-redhat-linux-gnu/doc/doxygen_manual.tex . && /usr/bin/cmake -E copy /home/elijah/SDA3/rpmbuild/BUILD/doxygen/3.11.2-x86_64-redhat-linux-gnu/doc/manual.sty . && /usr/bin/cmake -E copy /home/elijah/SDA3/rpmbuild/BUILD/doxygen/doc/doxygen_logo.pdf . && /usr/bin/pdflatex -shell-escape doxygen_manual.tex && /usr/bin/makeindex doxygen_manual.idx && /usr/bin/pdflatex -shell-escape doxygen_manual.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(./doxygen_manual.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 3 language(s) loaded.

ninja: build stopped: subcommand failed.
```

**Comment by albert-github** [comment]
- can you give the version of doxygen "master" is a floating version (i.e. we need the full output of `doxygen -v`)
- since when did this problem occur?
- Problem is that there is no error message and that it is not clear which subcommand failed.
- Is there something in the in the doxygen_manual.log (best to attach it in a compresed tar file).
- One reason might be the older version of LaTeX (I see a 2016 version), though I wouldn't expect a problem here.

**Comment by SchweinDeBurg** [comment]
I've just investigated this situation and commit 24db478285843d3e6afa32af734e29a316f42d62 is a show-stopper for me. When I've applied reverse patch created by
```
git show -R 24db478285843d3e6afa32af734e29a316f42d62
```
PDF manual built fine.

**Comment by albert-github** [comment]
The problem that you only see `1.9.0` has probably something to do with the fact that you don't have the .git directory available (which is strange as you build from master) or that there is something in the ninja system that doesn't understand the way the sha5 is extracted. Anyway we know the offending commit.

This is what I was afraid of.
I think the problems come from the lines:
```
\usepackage{xpatch}
\xpatchcmd{\part}{plain}{empty}{}{}
```
together with a bit an older version of LaTeX. Would it be possible to just comment out these 2 lines in `manual.sty` and see what happens?
Note: I didn't need these statements for the "normal" output as it was only needed for the "Part" pages. I know of an alternative implementation (have to test that myself as well) so when it is confirmed that the above statements are the offending ones we should try that possibility.

**Comment by SchweinDeBurg** [comment]
I think I've completely investigated now. :-) File doxygen_manual.log contains
```
! LaTeX Error: File `xpatch.sty' not found.
```
near to the end. So I've just installed "texlive-xpatch" RPM package containing this file and trying to build Doxygen again.

**Comment by albert-github** [comment]
Sounds good.
"Problem" with the building of the doxygen_manual is that it contains `\batchmode` and thus hides a bit the errors, but the `\batchmode` is necessary as otherwise the build might hang during an automatic build and that would not be good at all.

**Comment by SchweinDeBurg** [comment]
Gotcha! With "texlive-xpatch" package installed Doxygen was successfully built now. JFYI here is a part of my RPM spec:
```
BuildRequires: texlive-adjustbox >= svn26555.1.0
BuildRequires: texlive-appendix >= svn39039
BuildRequires: texlive-dvips >= svn41149
BuildRequires: texlive-etoc >= svn38831
BuildRequires: texlive-hanging >= svn15878.1.2
BuildRequires: texlive-import >= svn17361.5.1
BuildRequires: texlive-latex >= svn40218
BuildRequires: texlive-multirow >= svn17256.1.6
BuildRequires: texlive-newunicodechar >= svn28253.1.1
BuildRequires: texlive-sectsty >= svn15878.2.0.2
BuildRequires: texlive-stackengine >= svn32593.3.24
BuildRequires: texlive-tabu >= svn21534.2.8
BuildRequires: texlive-tocloft >= svn30209.2.3
BuildRequires: texlive-xpatch >= svn27897.0.2
BuildRequires: texlive-xtab >= svn23347.2.3
```
Maybe these texlive related packages used to build Doxygen manual are needed to be tested from CMake or listed as required in the build instructions? Anyway many thanks for Your assistance. I am closing this issue.

**Comment by albert-github** [comment]
It is in LaTeX quite often hard to tell which packages are all needed and overview you give is nice (and good) but there might also be other packages needed which are needed by the listed packages. In the "normal" documentation there might also be needs depending on the output languages selected.
I normally advise to completely install the LaTeX version (though this is a bit large and a bit of an overkill) so problems like these don't occur.
For MiKTeX I, personally, set the option that the missing packages are not installed on the fly but that I'm asked for it (and what is installed is nowadays quite a lot also due to tests I did. I installed e.g. the lipsum package although doxygen doesn't use / need it).
Under Cygwin I installed the complete TeXLive so I don't have the problems.

It is a nice suggestion though.
