### ISSUE TITLE
Hyperlink for the member (function or variable) in UML class diagram

### ISSUE THREAD

**Issue by al-hub** [doxygen/doxygen#8135]
**Describe the bug**
The current version could not link for member when we use UML class diagram.  

**Expected behavior**
It should go directly when we click the member (function or variable) on UML class diagram.  

**Version**  
1.8.20

**Comment by albert-github** [comment]
Without an example it is hard to tell what the cause of the problem is, it might even be dependent of the used browser.
The problem might have to do with issue #8053 (pull request #8058).

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by al-hub** [comment]
![Uploading image.png…]()

**Comment by albert-github** [comment]
Looks like something went wrong as you closed the issue and the link posted in the comment: https://github.com/doxygen/doxygen/issues/8135#issuecomment-717168945 points straight back to the issue.
