### ISSUE TITLE
\include{doc} removes all newline

### ISSUE THREAD

**Issue by Herminator** [doxygen/doxygen#8147]
there are line breaks with the other command arguments options ("", "lineno").

Version: 1.8.20
Ubuntu 20.04 LTS

**Comment by doxygen** [comment]
Please add a self contained example (source+config file in a zip or tar) so that we can reproduce the issue.

**Comment by Herminator** [comment]
The is a small example:
[doxyinclude.zip](https://github.com/doxygen/doxygen/files/5497395/doxyinclude.zip)

This is the output it produces:
![include](https://user-images.githubusercontent.com/537961/98295927-80c58480-1fb2-11eb-849a-c3e5d8251989.jpg)

**Comment by albert-github** [comment]
I think we have to distinguish here the situations:
1. including as code (`\include default.dox` and `\include{lineno} lineno.dox`)
2. include ass documentation (`\include{doc} doc.dox` and `\include{doc} doc_newline.dox`)

In case of the including as code the code is included "verbatim" after code has been color coded by the used language (hence the colored "default" as the file is interpreted, historically as C).
In case of including as documentation, the text is included like it is normal documentation and thus the lines are joined together (till the end of the paragraph) resulting in the one line 
```
This is a default include. On two lines.
```
In case one uses the command `\n` this explicitly says go to the next line and thus the output is:
```
This is a default include.
On two lines.
```

I think the problem is usage.
