### ISSUE TITLE
Example in documentation of ALIASES shows using `\n` instead of `^^`

### ISSUE THREAD

**Issue by krempel-pt** [doxygen/doxygen#8160]
**Describe the bug**
In the documentation of ALIASES (https://www.doxygen.nl/manual/custcmd.html) `\n` is used to get a newline but in the text directly below the example it is stated that you cannot do this but have to use `^^`

**Expected behavior**
Have a working example there.

**Version**
Online documentation generated on Mon Aug 24 2020 15:16:42 for Doxygen Manual

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8161

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
