### ISSUE TITLE
inline namespace broken after 075229e

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#8167]
**Describe the bug**
Parsing an inline namespace segfaults.

```cpp
namespace foo
{
inline namespace bar
{
//!\brief Some docs.
struct example
{

};

}
}
```

**Expected behavior**
No segfault.

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/5515983/example.tar.gz)
The Doxyfile was not modified.

**Version**
Current master, 075229e586b391c3ec7ad79597aaeae392ca64e5

**Stack trace**
```console
isSymbolHidden(const Definition * d) (\run\shm\doxygen\src\doxygen.cpp:7919)
computeTooltipTexts() (\run\shm\doxygen\src\doxygen.cpp:7929)
parseInput() (\run\shm\doxygen\src\doxygen.cpp:11539)
main(int argc, char ** argv) (\run\shm\doxygen\src\main.cpp:37)
```

In `computeTooltipTexts()`:
```cpp
    DefinitionMutable *dm = Definition::make_mutable(kv.second);
    if (!isSymbolHidden(dm) && dm->isLinkableInProject())
    {
      dm->computeTooltip();
    }
```
`kv` is non-zero (.first and .second), the result from `make_mutable` is a nullpointer.

**Comment by albert-github** [comment]
Some patches have been applied and the example from this issue now runs, also a similar problem with another package is fixed.

Please have a go at your entire project.

**Comment by albert-github** [comment]
@eseiler 

My goal is to easier be able to run, in the future, some tests (as you found and reported recently some "nice" problems).

I just tried to build the sequan3 documentation. I performed the following steps:
- git clone https://github.com/seqan/seqan3.git
- cd seqan3
- mkdir -p doc-build
- cd doc-build
- cmake ../test/documentation
  - when required with my own doxygen executable as `-DDOXYGEN_EXECUTABLE=<path>/doxygen.exe`
- make download-cppreference-doxygen-web-tag
- ctest . -j 2 --output-on-failure

Questions:
- Is this the right procedure?
- Is it better use instead of `ctest ...`?
  - make doc_usr
  - make doc_dev
- Is there another advised way?

With the `ctest` I get:
```
50% tests passed, 2 tests failed out of 4

Total Test time (real) = 1001.52 sec

The following tests FAILED:
          1 - doc_usr_no_warnings_test (Failed)
          3 - doc_dev_no_warnings_test (Failed)
```
or is this due to the fact that my `dot`  program produces (a lot):
```
DEBUG: FC_WEIGHT didn't match in /usr/share/fonts/microsoft/bahnschrift.ttf
```
for these tests?

**Comment by eseiler** [comment]
> @eseiler
> 
> My goal is to easier be able to run, in the future, some tests (as you found and reported recently some "nice" problems).
> 
> I just tried to build the sequan3 documentation. I performed the following steps:
> 
> * git clone https://github.com/seqan/seqan3.git
> * cd seqan3
> * mkdir -p doc-build
> * cd doc-build
> * cmake ../test/documentation
>   
>   * when required with my own doxygen executable as `-DDOXYGEN_EXECUTABLE=<path>/doxygen.exe`
> * make download-cppreference-doxygen-web-tag
> * ctest . -j 2 --output-on-failure
> 
> Questions:
> 
> * Is this the right procedure?

Yes, this is correct, but also see below.

> * Is it better use instead of `ctest ...`?
>   
>   * make doc_usr
>   * make doc_dev
> * Is there another advised way?

You can do it like you described, i.e.

```
make download-cppreference-doxygen-web-tag
ctest . -j 2 --output-on-failure
```

or after the `cmake` call run

````
make doc_dev
make doc_usr
````

or after the `cmake` call
```
make download-cppreference-doxygen-web-tag
cd doc_dev # or doc_usr
doxygen
```

We use the `ctest` in our CI because we capture the `cout` + `cerr` and check if there were warnings.
The `ctest` needs to build the documentation (because this is when warnings are emitted), hence we do not use `make` in this case - there may actually be some errors that are only emitted the first time you build the documentation (usually related to latex).

We also have another test in the ctest suite that checks if we escaped some stuff with `//!\cond`.

The main difference between `doc_usr` and `doc_dev` is that `doc_usr` excludes every symbol with `detail` in its name.

> 
> With the `ctest` I get:
> 
> ```
> 50% tests passed, 2 tests failed out of 4
> 
> Total Test time (real) = 1001.52 sec
> 
> The following tests FAILED:
>           1 - doc_usr_no_warnings_test (Failed)
>           3 - doc_dev_no_warnings_test (Failed)
> ```
> 
> or is this due to the fact that my `dot` program produces (a lot):
> 
> ```
> DEBUG: FC_WEIGHT didn't match in /usr/share/fonts/microsoft/bahnschrift.ttf
> ```
> 
> for these tests?

If you run `ctest --output-on-failure` it should also print the warnings, if not there should be a `cerr.txt` or similar in the directory.

**Comment by eseiler** [comment]
> Some patches have been applied and the example from this issue now runs, also a similar problem with another package is fixed.
> 
> Please have a go at your entire project.

Works fine on current master, thank you 👍

**Comment by albert-github** [comment]
Thanks for the extensive answer, it makes the entire process clear to me.

The procedure took quite a bit of time on my side and the process used for a long time 100% of the cpu. This is due to the use of the `-j 2` and the fact that `DOT_NUM_THREADS=0`, from the documentation:
> The DOT_NUM_THREADS specifies the number of dot invocations doxygen is allowed to run in parallel. When set to 0 doxygen will base this on the number of processors available in the system. You can set it explicitly to a value larger than 0 to get control over the balance between CPU load and processing speed.

In this case we have 2 processes that run and at one stage both come to the place where `dot` is run and here both processes want to use the total number of processors in the system. I think that for the tests it might be beneficial not to use the `-j 2` or when the number of processors of the known system is used only use half of the processors (I didn't time this with sequan).

**Comment by marehr** [comment]
> In this case we have 2 processes that run and at one stage both come to the place where `dot` is run and here both processes want to use the total number of processors in the system. I think that for the tests it might be beneficial not to use the `-j 2` or when the number of processors of the known system is used only use half of the processors (I didn't time this with sequan).

You are right, you can drop `-j 2`. We personally don't care if we have over subscription.

You can also just use `ctest -R doc_dev_no_warnings_test`, because the user documentation is a subset of our developer (more detailed) documentation.

**Comment by albert-github** [comment]
Code has been integrated in master on github (closing issue as it only occurred in the master version).
