### ISSUE TITLE
Group names behave differently when protected is used instead of private/public (Origin: bugzilla #121830)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#821]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-09-09 12:04:26 +0000, Oliver wrote:

    Hi,
    
    When subgrouping is turned on, protected sections behave differently to 
    private/public sections. Here is an example header file that demonstrates 
    the problem:
    /// \brief Win32 implementation of a WindowSys
    /// \remark This class is a Win32-specific implementation of the WindowSys
    /// interface and can be used to make windows on Win32 platforms.
    class Window
    {
    
    public: /// \name Construction and destruction
        /// @{
        
        /// \brief Window constructor
        /// \remark The default constructor for the Window object
        Window(void);
    
        /// \brief Window destructor
        /// \remark The default destructor for the Window object
        virtual ~Window(void);
    
        /// @}
    private: /// \name Win32-Specific helper functions
        /// @{
    
        /// \brief The static window callback procedure
        /// \param win Handle to the window receiving window message
        /// \param msg Identifier of the window message received
        /// \param wParam Word parameter assocaited with \a msg
        /// \param lParam Long parameter assocaited with \a msg
        /// \return Varies depending on the message, and processing
        /// that occurs as a result of the message
        /// \remark WndProc is a static member function that implements
        /// the Win32-API specific callback functionality. It is used
        /// as a central bottleneck for routing Window messages in a
        /// Win32 system. Messages are forwarded from this function
        /// to the relevent window's Switch() function.
        /// \sa Switch()
        static LRESULT WndProc(HWND win, UINT msg, WPARAM wParam, LPARAM 
    lParam);
    
        /// \brief An object-specific window procedure
        /// \param win Handle to the window receiving window message
        /// \param msg Identifier of the window message received
        /// \param wParam Word parameter assocaited with \a msg
        /// \param lParam Long parameter assocaited with \a msg
        /// \return Varies depending on the message, and processing
        /// that occurs as a result of the message
        /// \remark Switch is an object-local implementation of the
        /// WndProc() function. It's used to allow for objectification
        /// of window message handling in a Win32 window system.
        LRESULT Switch(HWND win, UINT msg, WPARAM wParam, LPARAM lParam);
    
        /// @}
    private: /// \name Member variables
        /// @{
    
        /// \brief Stored handle to the main engine system
        /// \remark Handle used to reference the main engine system
        /// at any point throughout the lifetime of the windowing system
        /// \sa RED::SYS::System, Init()
        RED::SYS::System* m_System;
    
        /// brief Stored handle to the process information
        /// \remark Handle used to reference the process information
        /// at any point throughout the lifetime of the windowing system
        /// \sa RED::SYS::Win32::WinProcess, SetProcessInfo()
        RED::SYS::Win32::WinProcess* m_ProcessInfo;
    
        /// \brief Handle to the window
        /// \remark A stored handle to the Win32-specific window created
        /// to hold the game
        HWND m_Win;
    
        /// \brief Stored string class name
        /// \remark Win32 windows require the name of a class to be used
        /// when registering a window type with the operating system.
        /// This member stores the window class name that's used in
        /// registration and creation of windows.
        std::string m_WindowClass;
    
        /// \brief Stored string window name
        /// \remark This variable contains the name that is displayed
        /// in the caption of the window
        std::string m_WindowTitle;
    
        /// \brief Active flag
        /// \remark If the window is active, this flag is set to true.
        /// Flag is used at various points to check if the window is
        /// active, so that smarter message handling can be done and
        /// CPU resources are not chewed up when the window isn't the
        /// active window.
        bool m_Active;
    
        /// \brief Window width
        /// \remark Stored variable containing the window width
        int m_Width;
    
        /// \brief Window height
        /// \remark Stored variable containing the window height
        int m_Height;
    
        /// @}
    };
    
    
    The documentation creates the following headers/subheaders:
    
    Win32-Specific helper functions 
    
    Public Member Functions 
      Construction and destruction 
    
    Private Attributes 
      Member variables 
    
    The first part is incorrect. It should look something like this:
    
    Protected Member Functions
      Win32-Specific helper functions
    
    For more information please don't hesitate to contact me. Keep up the 
    great work, this product is excellent!
    
    Oliver.

**Comment by albert-github** [comment]
In the mentioned example we nowhere see the word protected and it is also not clear which settings have been used in the doxygen configuration file (especially in respect to `EXTRACT_PRIVATE` and `EXTRACT_STATIC`, interesting in this context is also the enhancement request "Request for an EXTRACT_PROTECTED keyword (Origin: bugzilla #127867)", i.e. #898). 

I made the original problem a little bit smaller and tested with 1.8.18 (note: when replacing the word "protected" bu "private" or "public" we get similar results and conclusions. Also for versions like 1.3.2 we get similar results):
```
class Window
{

public: /// \name Construction and destruction
    /// @{

    /// \brief The default constructor for the Window object
    Window(void);
    /// @}

protected:
    /// \name Win32-Specific helper functions
    /// @{

    /// \brief An object-specific window procedure
    int Switch(void);

    /// \brief The static window callback procedure
    static int WndProc(void);

    /// @}
};
```
and used as doxygen configuaration:
```
GENERATE_LATEX         = NO
FULL_PATH_NAMES        = NO
TAB_SIZE               = 8
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
CASE_SENSE_NAMES       = YES
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
ALPHABETICAL_INDEX     = NO
SEARCHENGINE           = NO
QUIET=YES
STRIP_CODE_COMMENTS=NO
```
This results in:

![exam1](https://user-images.githubusercontent.com/5223533/82804652-f0233e00-9e82-11ea-8791-4cdd4aabab4f.jpg)

We see here that the functions "Switch" and "WndProc" are together underneath the title "Win32-Specific helper functions".  When not declaring the function "WndProc" as a static function we get:

![exam2](https://user-images.githubusercontent.com/5223533/82804928-6d4eb300-9e83-11ea-9589-fef46dd0e08e.jpg)

now we see that also the title "Protected Member Functions" appears.

When keeping the function static but giving it its own (different!) "\name" we get:

![exam3](https://user-images.githubusercontent.com/5223533/82805183-de8e6600-9e83-11ea-8b89-66a701c2d1f2.jpg)

we see that there is the title "Static Protected Member Functions" as well.

Conclusion due to the fact that static member functions have their own "section" with "title" the, possible expected, combing of the "groups" is not performed.

I don't think this is a bug in doxygen, but more a usage.

The full example: [example.tar.gz](https://github.com/doxygen/doxygen/files/4676793/example.tar.gz)
