### ISSUE TITLE
Insecure (http) links are bad for SEO

### ISSUE THREAD

**Issue by allanbowe** [doxygen/doxygen#8212]
**Describe the bug**
The default html pages are being created with insecure (http) links

**Expected behavior**
Where a site is available over https, that should be the default

**Screenshots**

![image](https://user-images.githubusercontent.com/4420615/100538759-f202fb00-3231-11eb-9575-d4579250a8e9.png)

**To Reproduce**

 `doxygen -w html header.html footer.html customdoxygen.css`
`
**Version**
![image](https://user-images.githubusercontent.com/4420615/100538782-119a2380-3232-11eb-8839-5c40b2c12e10.png)

**Stack trace**
n/a

**Additional context**
Google will penalise sites that contain links to insecure (http) sources

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
