### ISSUE TITLE
missing lang attribute and meta description for SEO

### ISSUE THREAD

**Issue by allanbowe** [doxygen/doxygen#8214]
**Describe the bug**
Missing lang attribute and meta type description

**Expected behavior**
Expecting certain attributes due to SEO penalisation without them

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/4420615/100545570-ba5d7880-325c-11eb-92b2-5d9b72ee8fe8.png)

After:
![image](https://user-images.githubusercontent.com/4420615/100545576-c2b5b380-325c-11eb-8db4-769eba62d5d3.png)

**To Reproduce**
n/a

**Version**
n/a

**Stack trace**
n/a

**Additional context**
The SEO tool used was google lighthouse (developer tools, chromium)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9457 

It is unclear what is meant with "meta type description", so no solution for this (might have been solved already though).

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
