### ISSUE TITLE
Unexpected warning "unbalanced grouping commands" with nested group definition

### ISSUE THREAD

**Issue by rstahn** [doxygen/doxygen#8267]
With #7102 Doxygen issues a very helpful warning for unbalanced group markers `@{ ... @}`.
While upgrading from Doxygen v1.8.13 to 1.8.20 I stumbled about a situation, where this warning is issued for no apparent reason.
The following file intents to define a nested hierarchy of groups:
```
//! @defgroup groupAPPL  APPL: Application Layer
//! @{
//!
//!     @defgroup group_Main       Main: Main Program
//!     @{
//!         @defgroup group_Main_Config             Main Configuration
//!         @defgroup group_Main_Public_Functions   Main Public Functions
//!         @defgroup group_Main_Defines_Typedefs   Main Definitions and Typedefs
//!         @defgroup group_Main_Global_Data        Main Global Data
//!     @}
//!
//! @}
//!
```
This will produce a warning "DoxygenGroups.c:12: warning: unbalanced grouping commands", which is unexpected.
Removing the empty line 3 or not indenting line 4 fixes the warning.

I have attached a minimal example [doxygen_unbalanced_group.zip](https://github.com/doxygen/doxygen/files/5724162/doxygen_unbalanced_group.zip) which reproduces the problem.

**Comment by albert-github** [comment]
The problem here is cause by the handling of the spaces a the the beginning of the comment in combination with the empty comment line after the first `@{`. As in this case 4 (or more) spaces at the beginning of a line are seen as the start of a verbatim section and the handling of `@}`  this results in the observed behavior.
When using `doxygen -d markdown` we see:
```
---- input -------
@defgroup groupAPPL  APPL: Application Layer
@{

    @defgroup group_Main       Main: Main Program
    @{
        @defgroup group_Main_Config             Main Configuration
        @defgroup group_Main_Public_Functions   Main Public Functions
        @defgroup group_Main_Defines_Typedefs   Main Definitions and Typedefs
        @defgroup group_Main_Global_Data        Main Global Data
---- output -----
@defgroup groupAPPL  APPL: Application Layer
@{
@verbatim
@defgroup group_Main       Main: Main Program
@{
    @defgroup group_Main_Config             Main Configuration
    @defgroup group_Main_Public_Functions   Main Public Functions
    @defgroup group_Main_Defines_Typedefs   Main Definitions and Typedefs
    @defgroup group_Main_Global_Data        Main Global Data
@endverbatim
```
but in fact the problem is already introduced a bit earlier, in the comment converter , `doxygen -d commentcnv`:
```
doxygen -d commentcnv
-----------
CommentCnv: D:/speeltuin/issue_8267/DoxygenGroups.c
output=[
/** @defgroup groupAPPL  APPL: Application Layer
 *  @{
 *
 *      @defgroup group_Main       Main: Main Program
 *      @{
 *          @defgroup group_Main_Config             Main Configuration
 *          @defgroup group_Main_Public_Functions   Main Public Functions
 *          @defgroup group_Main_Defines_Typedefs   Main Definitions and Typedefs
 *          @defgroup group_Main_Global_Data        Main Global Data */
//!     @}
/** */
//! @}
//!
]
```

Converting the comments from `//!` into `/** ..*/` comments, removes the warning but not the effect (the inner defgroups are not seen, the converted code:
```
/** @defgroup group1APPL  APPL: Application Layer
  * @{
  *
  *     @defgroup group1_Main       Main: Main Program
  *     @{
  *         @defgroup group1_Main_Config             Main Configuration
  *         @defgroup group1_Main_Public_Functions   Main Public Functions
  *         @defgroup group1_Main_Defines_Typedefs   Main Definitions and Typedefs
  *         @defgroup group1_Main_Global_Data        Main Global Data
  *     @}
  *
  * @}
  */
```

How to solve the problem:
- remove the empty comment line (here line 3)

or
- reduce the number of spaces at the beginning of the comment lines.

or
- set `MARKDOWN_SUPPORT=NO` (but I think this is the least attractive possibility)

The problem (shown through the `/** */` commenting way) is not a bug but usage.

**Comment by rstahn** [comment]
Thanks for the explanation. Knowing about the (markdown) verbatim section, Doxygens behavior is consistent - otherwise it is hard to spot.

I am wondering if there might be a way to help the user to understand the reason of the error message -- but I actually have no immediate idea on how to improve the existing documentation or the error message.

**Comment by albert-github** [comment]
@doxygen is there any reason for the rule `<SComment>\n[ \t]*"//"[\/!]("<")?[ \t]*[\\@]"}".*\n {` (currently line 732 of commentcnv.l).
I tried with the above example and the message is gone, the inner defgroups are shown as verbatim part but this is due to the white space.
I also looked at: last entry missing in a @name group of typedefs (Origin: bugzilla #752712) #5832
and iy looks to me that this is working without this rule as well.
