### ISSUE TITLE
\until and \skipline don't hide doxygen comments like \skip does

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#8338]
**Describe the bug**
Normally on text included from an file via `\dontinclude` or `\include` doxygen comment should be hidden; this works fine with `\snippet`, `\skip` and `\include`, but `\until` and `\skipline` don't omit doxygen line comment (`//!` or `///`)

**Expected behavior**
`\until` and `\skipline` should work as `\skip`, `\snippet` and `\include`

**To Reproduce**
s. attached ZIP file
[Test13_until.zip](https://github.com/doxygen/doxygen/files/5822315/Test13_until.zip)

**Version**
Tested with Doxygen V.1.9.1
also observed in earlier version, but figured out in detail

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8339

**Comment by thom-sch** [comment]
Thanks for quick fix; seems it solves the problem 👍 

Regards from Meerbusch
Thomas Schneider

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
