### ISSUE TITLE
Doxygen 1.9.1 confused by C++ using/typedef declaration

### ISSUE THREAD

**Issue by pkl97** [doxygen/doxygen#8370]
The attached test case [TestCase.tar.gz](https://github.com/doxygen/doxygen/files/5917346/TestCase.tar.gz) shows the behavior.
Doxygen 1.9.1 returns this warning message:

> Test.hpp:14: warning: no matching file member found for
> void A::f(const std::map &p_map)
> Possible candidates:
>  'void f(const TheMap &p_map)' at line 5 of file Test.cpp

It does not matter if the type alias is created via the _using_ or _typedef_ keyword. The warning occurs in both cases.

The warning disappears if either the namespace or the member in the struct is removed. It also goes away if the type is _std::map<int,int>_ instead of _std::map<int,std::string>_.

Doxygen 1.8.18-1.8.20 displays no warning.

**Comment by doxygen** [comment]
@pkl97 I've just committed a possible fix. Please verify if it indeed solves your problem. Don't close the issue as it will be closed automatically when a new official release is made available.

**Comment by pkl97** [comment]
Yes, it fixes the issue!
A run over a codebase that previously returned lots of those cases now returns with zero warnings.

Thanks a lot for identifying and fixing the issue that quick!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
