### ISSUE TITLE
Alternative to HHC? And dead link at https://www.doxygen.nl/manual/install.html#install_bin_windows

### ISSUE THREAD

**Issue by maettu-this** [doxygen/doxygen#8408]
Doxygen currently supports HHC to compile to .chm. The name `HHC_LOCATION` implies that `hhc.exe` is the sole option. Is there any alternative to compile to .chm?

Background of this inquiry:
`hhc.exe` is dated 1999-12-03, at least in the build environment I work with. And IT starts complaining about using such "old" pieces of software. We as software engineers are fully aware that old doesn't necessarily mean bad. Actually simple often means better. And old things tend to be simpler than new fancy stuff.

But in any case, sooner or later an alternative to `hhc.exe` might be required for true reasons.

When trying to find such alternative in Doxygen I came around the dead link mentioned in the title. It can be found at https://www.doxygen.nl/manual/install.html#install_bin_windows in:

> If you want to produce compressed HTML files (see GENERATE_HTMLHELP) in the configuration file, then you need the Microsoft HTML help workshop. You can download it from Microsoft.

The link https://www.microsoft.com/en-us/download/details.aspx?id=21138 results in error 404.

**Comment by albert-github** [comment]
I don't know which version you have of the hhc.exe, my version reports:
```
Microsoft HTML Help Compiler 4.74.8702
```
and is dated: `23-Jul-13  04:28` but this might be deceptive due to copy actions.

A long time ago Microsoft decided to abandon the path of the HTML Help in favor of something different, it is (to me) amazing how long the hhc.exe still works and was available. I recently detected also the them link https://www.microsoft.com/en-us/download/details.aspx?id=21138 doesn't work anymore (@doxygen do you know of an alternative link?).
Also the official HTML Help Workshop was only available on Windows.

I sometimes see in stack overflow questions an alternative (but I never tried it ad don't know its current status): FAR Html (see https://softwarerecs.stackexchange.com/questions/36123/successor-of-alternative-to-html-help-workshop) but some links here give a 404 error as well. 


I found a link but I don't know it so I don't know whether it is manipulated or not (looks like it also contains the version from 1999): https://www.helpandmanual.com/download/htmlhelp.exe

**Comment by albert-github** [comment]
I posted a question with the question: https://softwarerecs.stackexchange.com/a/38926/27803

and got as answer back:
> Further development of FAR HTML has been discontinued. A year ago, the shop at helpwaregroup.com was closed. As the translator (DE) of the software at the time, I have no contact with the former developer at the moment. I assume the domain was abandoned. I will continue to provide the download of FAR HTML as freeware and the corresponding licence keys as far as possible at https://www.help-info.de/download.html

**Comment by albert-github** [comment]
Some more info was provided:
> the download link microsoft.com/en-us/download/details.aspx?id=21138 was dropped by Microsoft last month - nothing news about this. You can get files from web archives: - http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe - http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/helpdocs.zip

**Comment by albert-github** [comment]
I've just pushed a proposed documentation patch, pull request #8411 

It looks to me that there are no, maintained, alternatives for the HTML Help Workshop, so the only thing that can be done is to update the documentation.

**Comment by albert-github** [comment]
Documentation update has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by maettu-this** [comment]
Note that **Sandcastle** supports generating to `.mshc`. But this only seems interesting for Visual Studio integration of help content. Also note **DocFX** which solely outputs to a static web page. Both options for sure have their place, but `.chm` seems so much superior for standalone use outside Visual Studio. Strange how Microsoft could abandon this path...

Concluding: Doxygen will still support HHC in the future. No intention nor option to replace by something equal.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
