### ISSUE TITLE
Trips over @verbatim

### ISSUE THREAD

**Issue by t-b** [doxygen/doxygen#8532]
**Describe the bug**

For the input

```c
    //////////////////////////////////////////////////////////////
    /// Some kind of method
    ///
    /// @param something a parameter
    /// @returns the same value provided in something param
    ///
    /// @verbatim embed:rst:leading-slashes
    ///    .. code-block:: c
    ///       :linenos:
    ///
    ///       bool foo(bool something) {
    ///           return something;
    ///       };
    ///
    /// @endverbatim
    //////////////////////////////////////////////////////////////
    virtual void rawLeadingSlashesVerbatim(int something) const = 0;
```

I get the following xml output

```xml
....
        <detaileddescription>
<para><verbatim>Some kind of method

@param something a parameter
@returns the same value provided in something param

@verbatim embed:rst:leading-slashes
</verbatim> /// .. code-block:: c /// :linenos: /// /// bool foo(bool something) { /// return something; /// }; /// ///  </para>
        </detaileddescription>
....
```

Doxygen does not recognize `@verbatim` and I also get a a warning `E:/test-verbatim.c:15: warning: unexpected command endverbatim`.

**Expected behavior**

Doxygen should parse verbatim correctly.

**To Reproduce**

[doxygen-verbatim-bug.zip](https://github.com/doxygen/doxygen/files/6411571/doxygen-verbatim-bug.zip)

**Version**

1.9.1 (ef9b20ac7f8a8621fcfc299f8bd0b80422390f4b*)
Windows 10 x64

**Comment by albert-github** [comment]
This is a complex interaction of the used comment signs `///` and the `@verbatim` command.
The `@verbatim` command takes all the documentation from that point till the `@endverbatim` as verbatim, i.e. takes everything literal.

It is interesting to look at the output of the different debug stages.

First is the comment conversion stage (i.e. `doxygen  -d commentcnv`), which results in:
```
    /**
     *  Some kind of method
     *
     *  @param something a parameter
     *  @returns the same value provided in something param
     *
     *  @verbatim embed:rst:leading-slashes
    ///    .. code-block:: c
    ///       :linenos:
    ///
    ///       bool foo(bool something) {
    ///           return something;
    ///       };
    ///
    /// @endverbatim
                                                                *  */
    virtual void rawLeadingSlashesVerbatim(int something) const = 0;
```
we see that here doxygen converts the `///` to a block of comment starting with `/**` but leves the part between `verbatim` ... `@endverbatim` untouched.

The next interesting is the markdown stage (`doxygen -d markdown`) which gives:
```
---- input -------

    Some kind of method

    @param something a parameter
    @returns the same value provided in something param

    @verbatim embed:rst:leading-slashes
///    .. code-block:: c
///       :linenos:
///
///       bool foo(bool something) {
///           return something;
///       };
///
/// @endverbatim

---- output -----
@verbatim
Some kind of method

@param something a parameter
@returns the same value provided in something param

@verbatim embed:rst:leading-slashes
@endverbatim\ilinebr ///    .. code-block:: c
///       :linenos:
///
///       bool foo(bool something) {
///           return something;
///       };
///
/// @endverbatim


=========
-----------
```
so we see that it gets the block stripped from the `/**` and `*` comment parts and now we have for the first line 4 spaces and this is for markdown the signal to start a `@verbatim ` block end it ends this at the first line with `///` as this is not indented with at least 4 spaces and this includes a `@verbatim` which is later on explicitly closed by `@endverbatim` but doxygen (correctly missed the corresponding `@verbatim`.

What solutions do we have:
- remove the space before all the `Some`, this will will have some effect, but due to the earlier describe working of `@verbatim` this will result in lines with `///`.
- convert, by hand, block to a block with `/**` and `*` for all lines, here we also see `@verbose` effect i.e. there are here `*`
- convert, by hand, block to a block with `/**` and `*` for all lines except the lines in the verbose block:
  ```
    /**
     *  Some kind of method
     *
     *  @param something a parameter
     *  @returns the same value provided in something param
     *
     *  @verbatim embed:rst:leading-slashes
           .. code-block:: c
              :linenos:

              bool foo(bool something) {
                  return something;
              };

        @endverbatim
     */
  ```
  this results in, what I think, the intended output.

So I think that this problem, how inconvenient, is usage.

**Comment by t-b** [comment]
Thanks for the detailed analysis.

I found this snipped in the wild in breathe's documentation, see https://github.com/michaeljones/breathe/blob/42bc2afe1446d173ccc17a2095deb9798e1fac9d/examples/specific/rst.h#L68.

If I disable MARKDOWN_SUPPORT doxygen does not warn anymore, so I think this should work as well. Thanks again.
