### ISSUE TITLE
@file ignored if indented

### ISSUE THREAD

**Issue by davidi17** [doxygen/doxygen#8539]
On updating to v1.9.1 of doxygen I find that the @file instruction is ignored if it is indented. The following is OK

```
/**
@file
    @brief My superb interface
    @par Note re foo bar
*/
```
But this is not, with the `@file` indented.

```
/**
    @file
    @brief Not so good
    @par Note re foo bar    
*/  
```
I've attached two sample projects in the one zip file, the source code is identical except for the indented `@file`. The objective is solely to get the `myIncludeFile.h File Reference` page in HTML. In the first case, with the indented `@file` the only output are empty HTML pages. But in the second case, we get the required `my_include_file1_8h.html` file.

This used to work OK with v1.8.3.1. This is a follow up prompted by 
[Unable to Document Header File with Doxygen](https://stackoverflow.com/questions/28890103/unable-to-document-header-file-with-doxygen/67383662#67383662)

```
doxygen -v
1.9.1 (ef9b20ac7f8a8621fcfc299f8bd0b80422390f4b)
```
[Doxygen-test-v1_9.zip](https://github.com/doxygen/doxygen/files/6445834/Doxygen-test-v1_9.zip)

**Comment by albert-github** [comment]
Between the code in the issue and the code in the attched example theer is an essential difference:

In the issue:
```
/**
    @file
    @brief Not so good
    @par Note re foo bar    
*/
```

In the attached example:
```
/**
     @file
        @brief My superb interface.

        @par Output to szFoo buffer
Functions that output to the szFoo buffer use the throgglethorp algorithm.
*/
```
The essential difference is the line:
```
Functions that output to the szFoo buffer use the throgglethorp algorithm.
```
that starts at the beginning of the line whilst all other content lines have 4 spaces or 1 tab (i.e. due to the default tab setting also 4 spaces, mixing tabs and spacing is definitely not advised) in front of them.

What is the significance of the 4 spaces?:
From the "Code blocks" paragraph in the chapter "Markdown support" of the documentation:
> Preformatted verbatim blocks can be created by indenting each line in a block of text by at least 4 extra spaces

and due to the "Function ..." line all the spaces are significant here (see below for solutions).

One can see this also nicely when using the doxygen debug option `-d markdown` (so `doxygen -d markdown Doxyfile`) which gives:
```
@verbatim
 @file
@brief My superb interface.

@par Output to szFoo buffer
@endverbatim\ilinebr Functions that output to the szFoo buffer use the throgglethorp algorithm.
```
so we see that `@file` is in a `@verbatim` block and thus not seen as a real `Adfile` command.

**Solutions**
- disable `MARKDOWN_SUPPORT`, not really advised
- Properly indent the "Functions..." line
- indent the `@file` with at least 1 space less (be careful to do it also with the following lines when putting `@file at the beginning of the line)


So I think the problem is usage.

**Comment by davidi17** [comment]
OK that's good. The reason the second line of the `@par` block was not indented is because back in the day (2013 or so) that seemed to be the only way to include that text inside the `@par` block (from memory if you indented that line then it and all following lines were excluded from the `@par` block). In light of your explanation it was probably always an accidental `@verbatim` issue. 

The markdown debug option is really neat and should be better advertised. As an aside I note it renders `` `foo` `` using the now-unsupported `` <tt>foo</tt> `` in the debugging output but that is fixed in the final output to use `<code>`
