### ISSUE TITLE
[Enhancement] Allow HTML table in Markdown file

### ISSUE THREAD

**Issue by higaski** [doxygen/doxygen#8540]
**Describe the bug**
Afair it is currently not possible to place HTML tables inside Markdown files used as mainpages.

**Expected behavior**
It would be great if HTML tables in Markdown files get shown just as when including one in regular documentation (e.g. header files).

**Screenshots**
The table in the example as generated by doxygen (index.html):
![index html](https://user-images.githubusercontent.com/13762516/117628449-752d6300-b179-11eb-86d1-755cc74f1d36.png)

The table opened by VSCode markdown preview:
![readme md](https://user-images.githubusercontent.com/13762516/117628460-78285380-b179-11eb-91a2-58dcbff01b54.png)

**To Reproduce**
[MarkdownHtmlTable.zip](https://github.com/doxygen/doxygen/files/6450566/MarkdownHtmlTable.zip)

**Version**
1.9.1

**Comment by albert-github** [comment]
In the description of the issue we miss the warnings:
```
.../MarkdownHtmlTable/README.md:5: warning: expected <tr> or <caption> tag but found <thead> instead!
.../MarkdownHtmlTable/README.md:19: warning: Unsupported xml/html tag </thead> found
.../MarkdownHtmlTable/README.md:20: warning: Unsupported xml/html tag <tbody> found
.../MarkdownHtmlTable/README.md:29: warning: Unsupported xml/html tag </tbody> found
.../MarkdownHtmlTable/README.md:5: warning: expected <tr> or <caption> tag but found <thead> instead!
.../MarkdownHtmlTable/README.md:19: warning: Unsupported xml/html tag </thead> found
.../MarkdownHtmlTable/README.md:20: warning: Unsupported xml/html tag <tbody> found
.../MarkdownHtmlTable/README.md:29: warning: Unsupported xml/html tag </tbody> found
```
as the tags `<thead>`,  `</thead>`, `<tbody>` and `</tbody>` are not supported by doxygen.

Removing the `<thead>`,  `</thead>`, `<tbody>` and `</tbody>` solves the issue at hand and results is:

![image](https://user-images.githubusercontent.com/5223533/117629980-0224ec00-b17b-11eb-9b4d-bbce99fc012c.png)

In this matter there also exists the issue #3289 and the proposed patch #7215 (to just ignore the tags).

So this issue is a combination of duplicate and usage.
