### ISSUE TITLE
input buffer overflow, can't enlarge buffer because scanner uses REJECT

### ISSUE THREAD

**Issue by sdrgroup** [doxygen/doxygen#8564]
**Describe the bug**
Describe what you see that (you think) is wrong.

**Expected behavior**
Describe what you would have expected or think is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/12608702/119226891-f1db1c80-bb3d-11eb-8617-6b71fa27f429.png)

**To Reproduce**
[bigflow.zip](https://github.com/doxygen/doxygen/files/6526399/bigflow.zip)
[Doxyfile.zip](https://github.com/doxygen/doxygen/files/6526405/Doxyfile.zip)

**Version**
1.9.2
**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
In the documentation there is a section:
> 18.14 Help! I get the cryptic message "input buffer overflow, can't enlarge buffer because scanner uses REJECT"
>
> This error happens when doxygen's lexical scanner has a rule that matches more than 256K of input characters
in one go. I've seen this happening on a very large generated file (>256K lines), where the built-in preprocessor
converted it into an empty file (with >256K of newlines). Another case where this might happen is if you have lines
in your code with more than 256K characters.
If you have run into such a case and want me to fix it, you should send me a code fragment that triggers the
message. To work around the problem, put some line-breaks into your file, split it up into smaller parts, or exclude
it from the input using EXCLUDE.
Another way to work around this problem is to use the cmake command with the option:
> ```
> -Denlarge_lex_buffers=<size>
> ```
> where <size> is the new size of the input (YY_BUF_SIZE) and read (YY_READ_BUF_SIZE) buffer. In case
this option is not given the default value of 262144 (i.e. 256K) will be used.

Most likely cause is that there are some defines in the include files that expand to a very large statement.

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
(Just dumping the full code will take a lot of time from our side to look into it).

**Comment by doxygen** [comment]
Looks like the problem is in bigflow_python/get-pip.py.
It has variable DATA which is assign a huge blob of encoded data.
Even though this is split over multiple lines, doxygen's scanner seems to want to read it all at once.

As a workaround, try to exclude that file using the `EXCLUDE` option.

**Comment by albert-github** [comment]
Even though I think the solutions in the comments might still be valid (and the comment from doxygen certainly makes sense for this case), I've just pushed a proposed patch, pull request #8565

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by julian5392** [comment]
Hi, this problem still exists,when I use doxygen to analyze the Deepin OS kernel source code.

**Comment by julian5392** [comment]
> Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

Hi, this problem still exists,when I use doxygen to analyze the Deepin OS kernel source code.

**Comment by albert-github** [comment]
@julian5392 as there is no reference to the any source code or used doxygen version it is hard to tell wheer an improvement might be possible, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

Furthermore of interest is here:
- https://github.com/doxygen/doxygen/issues/8564#issuecomment-846433865
