### ISSUE TITLE
Doxygen reference link failed when path is directory

### ISSUE THREAD

**Issue by zchrissirhcz** [doxygen/doxygen#8567]
https://stackoverflow.com/questions/67687428/doxygen-reference-link-failed-when-path-is-directory

**Comment by albert-github** [comment]
A link alone is not good as the link to stack overflow might not be persistent (e.g. when you close your account there or when the issue is removed on git overflow) and this issue would missing relevant information, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by zchrissirhcz** [comment]
Figured out my fault due to EXCLUDE my doc dir.
