### ISSUE TITLE
Upgrade jQuery to latest 3.5 or 3.6 release to get rid of security issues.

### ISSUE THREAD

**Issue by LaurenceL** [doxygen/doxygen#8616]
In the latest Doxygen release (1.9.1), the jquery version used is 3.4.1. This version contains two security issue:

- CVE-2020-11022 (https://nvd.nist.gov/vuln/detail/CVE-2020-11022)
- CVE-2020-11023 (https://nvd.nist.gov/vuln/detail/CVE-2020-11023)

jquery have released 3.5.1 to fix it (https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/).

If upgrading to 3.5.x (or 3.6) is too complicated, there is a patch for 3.4.1 that can be applied. See https://github.com/DanielRuf/snyk-js-jquery-565129

**Comment by doxygen** [comment]
I've upgraded jquery to 3.6.0 with the latest commit.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
