### ISSUE TITLE
Alias in fenced code block not working

### ISSUE THREAD

**Issue by Austriker** [doxygen/doxygen#8655]
**Describe the bug**
Adding alias in code block doesn't work as expected :
```
@code{.sh}
cd ~/v@major_version.@minor_version.@patch_version/
@endcode
```
outputs:
```
cd ~/v@major_version.@minor_version.@patch_version/
```

**Expected behavior**
it should output:
```
cd ~/v1.0.0/
```

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.

**Version**
1.9.2 (6200bc83119593e1f37adae88284a2d3bf8beed6)
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by albert-github** [comment]
From the documentation of the `\code` command:
> Starts a block of code. A code block is treated differently from ordinary text. It is interpreted as source code.
The names of classes and members and other documented entities are automatically replaced by links to the
documentation.

There is no mention (and would not be logical either in my opinion) that doxygen commands are interpreted.

```
@code{.sh}
cd \b some bold text
@endcode
```
will result in:

![image](https://user-images.githubusercontent.com/5223533/124934909-75c16900-e005-11eb-8763-faa090ca5b93.png)

so the `\b` is still present too.

You could use e.g.:
```
<pre>
cd ~/v@major_version.@minor_version.@patch_version/
</pre>
```
though you would use the code coloring.

I think the problem is usage.

Note:  (in this case it was "easy" to create a small configuration file), normally:
> please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by Austriker** [comment]
I have used cmake to configure my files before doxygen
