### ISSUE TITLE
Ask for help, i want to know an exact version number about doxygen.

### ISSUE THREAD

**Issue by dieryuan** [doxygen/doxygen#8688]
i know doxygen from 1.8.13 to 1.9.1 solve a bug. because of some reasons, i can't use doxygen 1.9.1.  i want to know the minimum version ahout the issue. Thanks a lot.

Doxygen 1.9.0
doxygen 1.8.13

Running Sphinx v4.1.0

Sphinx error:
Builder name ht not registered or available through entry point
make: *** [ht] Error 2
[1]$ make html
Running Sphinx v4.1.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                               
Exception occurred:
  File "/meda_home/1/.local/lib/python3.6/site-packages/sphinx/util/cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 8]
  typename
  --------^

**Comment by albert-github** [comment]
This looks like more a sphinx error than a doxygen error and is better asked with sphinx (what is ht?).
You wrote "i know doxygen from 1.8.13 to 1.9.1 solve a bug" but you didn't write which bug, best is to check through the changelog (https://www.doxygen.nl/manual/changelog.html) to see where your problem is solved.
Things you could try is to find executables for your OS and try these or take the different source trees and build from these your executables (see https://www.doxygen.nl/manual/install.html).
