### ISSUE TITLE
Option to hide primitive types?

### ISSUE THREAD

**Issue by lockywolf** [doxygen/doxygen#8708]
Although sometimes seeing primitive types on the code diagram can be useful, for example when adapting code to work in kernel space (without floating point operations), generally primitive types are not very useful to grasp the structure of code.

Would it be possible to add an option to omit c++ primitive (and STL) types when generating diagrams?

References:
https://stackoverflow.com/questions/14396099/can-doxygen-be-configured-to-omit-fundamental-c-types-from-collaboration-diagr

**Comment by lockywolf** [comment]
Hm... I don't seem to be able to reproduce this behaviour with the latest version, so, I guess, my bug has already been resolved.

**Comment by GuillaumeHM** [comment]
Hi,
First of all, thank you for the great work in Doxygen !

I agree this request. I'm generating documentation with a maximum of information for easing developers to understand a codebase. So I disable the configuration `HIDE_UNDOC_RELATIONS` (_hide inheritance and usage if target isn't documented or is not a class_). But this also includes the language primitive types like `int`, `bool`, etc, which does complicates diagrams with more blocks and much more arrows.

I reproduce with 1.9.8 (2023).

I would like an option `HIDE_PRIMITIVE_TYPES` (with priority over `EXTRACT_ALL` like has `HIDE_UNDOC_RELATIONS`).

Concerning the C++ STL's types, they should be under another new configuration like `HIDE_EXTENDED_PRIMITIVE_TYPES` because this information is valuable in my use case.

**Comment by albert-github** [comment]
@GuillaumeHM 

- The doxygen version 1.9.8 is a bit older, the current doxygen version is 1.14.0 so have a try with the new version
- As this issue closed (since 2021) it is better to open a new issue describing your enhancement request including:
  - attaching a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem / enhancement request?
   Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
