### ISSUE TITLE
links to template specializations with nested template parameters do not work

### ISSUE THREAD

**Issue by georg-emg** [doxygen/doxygen#8715]
When attempting to create a link to the documentation of a template specialization whose parameters are themselves templates, Doxygen does not correctly create the link in html output. The following links to the given template specialization do not work, for example:

~~~cpp
template <>
struct Test<std::vector<std::string>>;
~~~

Links to simple template specializations, like `struct Test<std::string>` work correctly. (but see bug #8714)

**Expected behavior**
Links to template specializations with templates as parameters should work the same as links to template specializations with plain classes as parameters.

**Screenshots**
![links-to-nested-templates](https://user-images.githubusercontent.com/71000124/129181187-9fcc1f4f-67b0-4a25-9377-2a25c14255ca.png)

**To Reproduce**
This is the project that created the above screenshot:

[links-to-nested-templates.zip](https://github.com/doxygen/doxygen/files/6974662/links-to-nested-templates.zip)

**Version**
Doxygen version 1.9.1. on 64 bit Windows 10

**Comment by doxygen** [comment]
@georg-emg Please verify if the referenced commit fixes the problem.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
