### ISSUE TITLE
Dead-Link to mailinglist archive

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [doxygen/doxygen#8742]
See this website
https://www.doxygen.nl/support.html

There is a link to the "the archives" of the mailinglist pointing to
http://doxygen.10944.n7.nabble.com/

This is link is dead.

**Comment by albert-github** [comment]
Code has been adjusted in the offline version and will be adjusted at the next update of the website / with the next release of doxygen (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
