### ISSUE TITLE
<tt> missinterpreted

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [doxygen/doxygen#8743]
Please see this line in your doc files.

https://github.com/doxygen/doxygen/blob/0b13cc6d2469c1241b575f7c3e45e99599faed1d/doc/docblocks.doc#L462

I am not sure which doc technology you are using. But in fact the result is not correct.
See https://www.doxygen.nl/manual/docblocks.html#pythonblocks

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8744

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
