### ISSUE TITLE
export "something" { } wrong parsing

### ISSUE THREAD

**Issue by FoxOneReal** [doxygen/doxygen#8838]
**Describe the bug**
I have something like this
```
extern "OldAsmCall" {
	void func1();
	void func2();
}
```
in my sources (old VDSP compiler). Doxygen parse this as extern **variable** `OldAsmCall` with intializer `{ void func1()` and normal function `void func2()`

extern "C" { } or "C++" do parsed normally

**Expected behavior**
Expected to see extern void func1() and extern void func2()

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/63783780/138142770-3b9895c1-813c-4c9f-929a-671a718d3160.png)

**Version**
Tested 1.9.2

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
