### ISSUE TITLE
Python call graph is not completely correct

### ISSUE THREAD

**Issue by zlonqi** [doxygen/doxygen#8851]
I used doxywizard to genarate call and caller graph for a large python project. call graph was not completely correct.
```python
 class SawtoothSubmitter:
        def a:
                xxx
        def b:
               xxx
        def c:
               xxx
```
The result is a->b->c,  But in fact there is no call relationship between them. Thank you so much~

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
