### ISSUE TITLE
LaTeX generated output fails to compile

### ISSUE THREAD

**Issue by brianp1414** [doxygen/doxygen#8853]
**Describe the bug**
When attempting to run the make.bat file to compile the generated LaTeX file, TeX reports:
```
l.3 {\ttfamily \texorpdfstring
                              {$<$}{<}some text\texorpdfstring{$>$}{>}}
?
```
**Expected behavior**
Expect the execution of make to complete successfully and deliver a pdf file.

**To Reproduce**
The attached markdown file [minimal.zip](https://github.com/doxygen/doxygen/files/7415677/minimal.zip)  when processed with PDF_HYPERLINKS set to NO will produce a LaTeX file that will not process. Change the PDF_HYPERLINKS to YES and it works successfully. Essentially the following markdown sequence causes the problem
```
 `<some text>`
```
It is the presence of less than in the backtick environment.

**Version**
1.9.2 (caa4e3de211fbbef2c3adf58a6bd4c86d0eb7cb8) on Windows 10, 64 bit.
(MiKTeX 21.10)

**Additional context**
Experimenting with the generated output seems to indicate that when PDF_HYPERLINKS = NO then refman.tex should contain the following lines:
```
% Hyperlinks
    \usepackage{nohyperref}
```
instead of just removing the `\usepackage[options]{hyperref}`

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
