### ISSUE TITLE
[PATCH] Typo in install documentation

### ISSUE THREAD

**Issue by duncan-roe** [doxygen/doxygen#8934]
**Describe the bug**
In the HTML documentation, section "Doxygen/Installation/ Installing the binaries on UNIX", there is mention of a *DEP* package.

**Expected behavior**
This should read *DEB* (short for Debian). The following patch worked for me:
[install.doc.patch.txt](https://github.com/doxygen/doxygen/files/7647439/install.doc.patch.txt)

**Comment by albert-github** [comment]
Can You please make a pull request out of this?

**Comment by duncan-roe** [comment]
Pull request submitted

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by duncan-roe** [comment]
Confirm fixed at 1.9.3
