### ISSUE TITLE
SEARCHDATA_FILE (searchdata.xml) keyword elements blank

### ISSUE THREAD

**Issue by neilsimon** [doxygen/doxygen#9027]
**Describe the bug**
The searchdata.xml keyword elements are empty when it is generated with external search enabled.

**Expected behavior**
The keyword elements should contain keywords.

**To Reproduce**
1. Run cmake thus: `cmake -Dbuild_search=ON`.
1. Run `make`.
1. Edit Doxyfile and change `EXTERNAL_SEARCH` to `YES`.
1. Run `bin/doxygen Doxyfile`.
1. Verify that there are no keywords in the generated searchdata.xml file: `grep keywords doxygen_docs/searchdata.xml`.
1. Check out Release_1_9_1 and do the same noting that there are keywords in the searchdata.xml file.

**Version**
Versions 1.9.3 and master are affected. Version 1.9.1 and 1.8.20 are not.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9033

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
