### ISSUE TITLE
Feature Request: Doxywizard: Customize Doxyfile Line Endings

### ISSUE THREAD

**Issue by AntumDeluge** [doxygen/doxygen#9054]
Could you add a setting the Doxywizard GUI that would allow changing exported Doxyfile line endings from system default to between `CRLF`, `LF`, & `CR`? This would be useful for shared projects where developers are using different platforms.

**Comment by albert-github** [comment]
- Which version of doxygen are you using?
- what kind of problems do you encounter between the different systems?
- are there still systems that use just the `CR` (`\r`) as line separator? In my recollection in the past the Apple systems did. (I know *nix uses `LF` i.e. `\n` and Windows `CRLF` `\r\n`).

**Comment by AntumDeluge** [comment]
```
doxygen --version
1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)
```

It's not serious problems. It's just that I'm on a Windows system. So if another developer creates a Doxyfile with `LF` line endings, if I edit it with the Doxywizard GUI, it get exported with `CRLF` line endings. So I have to open the file & change it back to `LF` manually.

I don't know a whole lot about Apple systems. I just see Apple referenced whenever I see `CR` posted. So I assumed that Apple system still use it by default.

Interestingly, the `doxygen -g` command generates a file with `LF` line endings on Windows. Not important, just interesting.

**Comment by albert-github** [comment]
Interesting observation the difference between doxygen and doxywizard.
It has to do with the default write settings in doxygen and doxywizard, they should be consistent, hence best to write out everywhere `\n`.

I've just pushed a proposed patch, pull request #9061

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by AntumDeluge** [comment]
Works for me. 😄

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by pisoir** [comment]
Hi, I am using doxywizard 1.11.0 and there is still strange behavior with the line endings. I have Doxyfile with Windows `\r\n` endings. When I open it in doxywizard and click  on save (not even changing anything) the doxywizard changes the endings on `\n`.
This is problematic since multiple people can work on it with various systems (linux/windows) and git notices the change although nothing has been changed. 
In my opinion, doxywizard should keep the endings from the doxyfile and not force it to `\n`.

**Comment by albert-github** [comment]
@pisoir 
It is not strange the issue and resulting PR clearly states that doxygen will change the line endings to `\n` and all a bit normal editors will understand these line endings.
In respect to git have a look at e.g. https://git-scm.com/book/en/v2/Customizing-Git-Git-Configurationor or https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows

**Comment by paule32** [comment]
For Windows Developers, I suggest to use the **_NOTEPAD++.EXE_** Application.
It is a Free OpenSource Software that is better as ALL WebEditors like SubLime and Co.
- You can extend the Editor with plugin's, or use the already built-in Function's.
- You can open multiple Files at the same time.
- You can load and save your Document's in different kind of Encoding (ASCII, UTF-8/16/32 - with/without BOM)
- It is fast.
- You can set highlight Colors for your source codes.
- You can save and load a group of Files like as a Project
