### ISSUE TITLE
Commands fail to render when quoted

### ISSUE THREAD

**Issue by hemberger** [doxygen/doxygen#9131]
**Describe the bug**
If a quote is opened before a command, and closed after the command, then the command does not display correctly.

Here is an example:

```
/** \page Test

End tags inside " will be broken:

\code
Some code
\endcode

Everything after the next " displays correctly:

\code
More code
\endcode

*/
```
In doxygen 1.9.3, this displays as:
![image](https://user-images.githubusercontent.com/846186/154608303-1675333a-b8bf-412a-b85a-31bfe55740a1.png)

**Expected behavior**
In doxygen 1.8.20, the exact same input displays correctly:
![image](https://user-images.githubusercontent.com/846186/154608612-38ecc6e3-a9ff-46d0-b823-df47e12a2225.png)

**Version**
1.9.3 (last known working version was 1.8.20)

**Additional context**
I'm not sure any of this is relevant, but here's the Doxyfile (with project details omitted):
```
RECURSIVE = YES
JAVADOC_AUTOBRIEF =  NO 
EXTRACT_PRIVATE = YES
EXTRACT_ANON_NSPACES = YES
EXTRACT_ALL = YES
EXTRACT_STATIC = YES
INLINE_SOURCES = NO
BUILTIN_STL_SUPPORT = YES
OPTIMIZE_OUTPUT_FOR_C = NO
STRIP_CODE_COMMENTS = NO
HAVE_DOT = NO
DOT_IMAGE_FORMAT = svg
MAX_DOT_GRAPH_DEPTH = 3
SEARCHENGINE = YES
SERVER_BASED_SEARCH = NO
GENERATE_LATEX = NO
FULL_PATH_NAMES = YES
PREDEFINED = __cplusplus
SHOW_USED_FILES = YES
DIRECTORY_GRAPH = NO
SORT_BY_SCOPE_NAME = YES
SHOW_INCLUDE_FILES = NO 
INCLUDE_GRAPH = NO 
INCLUDED_BY_GRAPH = NO 
GROUP_GRAPHS = NO
CASE_SENSE_NAMES = YES
MARKDOWN_SUPPORT = YES
FORMULA_FONTSIZE = 13
FORMULA_TRANSPARENT = YES
LATEX_BATCHMODE = YES
HTML_TIMESTAMP = YES
HTML_DYNAMIC_SECTIONS = YES
CALL_GRAPH = YES
CALLER_GRAPH = YES
COLLABORATION_GRAPH = YES
CLASS_GRAPH = YES
SOURCE_BROWSER = YES
VERBATIM_HEADERS = YES
```

There were a lot of other recent bug reports relating to quotes, but none seemed to directly address this issue, so I apologize if this is a duplicate!

**Comment by albert-github** [comment]
I think this one of  the exceptions mentioned in the documentation:

> 24.192 \"
> 
> This command writes the " character to the output. This character has to be escaped in some cases, because it is
used in pairs to indicate an unformatted text fragment.

The behavior of the usage of the `"`s was in the 1.8.20 version (actually version 1.9.1) incorrect and has been corrected for the 1.9.2 version.
See also #8525 and #8527.

So I think the output is correct and the problem is usage.

**Comment by hemberger** [comment]
Here is a minimal example showing that the quote environment changes `\code` to `@code` (but not `\endcode` to `@endcode`):
[issue9131.tar.gz](https://github.com/doxygen/doxygen/files/8099358/issue9131.tar.gz)

So that I'm sure I understand: it seems like the reason `"\"` no longer closes the quote environment is because there's no other way to get a literal `"` in a quote environment without supporting the special `\"` command inside it?

**Comment by albert-github** [comment]
I see what you mean with the `@code` problem the output is the unexpected:
```
" @code Some code \endcode " 
```
the problem is not only with the `\code` command but with a number of other commands as well, to the handling routine (in `commentscan.l`) just the name is given and not the invoking `@` of `\`  and as output the `@` is used. The later should be done a bit more sophisticated.

I'm not 100% sure by what you mean by your "So that I'm sure I understand" , but as far as I unders stand your comment this is indeed the case.

**Comment by albert-github** [comment]
It looks an easy problem to solve but it might not be the case, have to check the `handle...` functions in `commentscan.l` thoroughly and see whether or not "new" rules compared to other parts are necessary. 

Regarding the requirement of a new issue, yes I think that it is better to have a new issue as we have 2 issues:
- usage of the double quotes (as discussed in this issue)
- the representation of e.g. `\code` inside quotes
