### ISSUE TITLE
DOC: Mention `-x` switch in the "Support" page

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [doxygen/doxygen#9190]
I would recommend to mention the `doxygen -x` option in the [Support](https://www.doxygen.nl/support.html) page where the access to mailinglists and stackoverflow is the topic.

Maybe this would improve some questions on SO and the mailinglist.

And maybe it is also a good idea to mention that `-x` in the first `#`-lines of the `Doxyfile` template.

**Comment by ferdymercury** [comment]
as well as x_noenv if https://github.com/doxygen/doxygen/issues/9187 gets merged.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Maybe I misunderstand the commits. But it seems to me that you did not addressed the "Support page" I mentioned.
https://www.doxygen.nl/support.html

**Comment by albert-github** [comment]
The support page is in a different repository (not visible to the users) and the files there are constructed / created in a different way.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
