### ISSUE TITLE
GHC_NO_DIRENT_D_TYPE should be defined on Solaris

### ISSUE THREAD

**Issue by lukyhruska96** [doxygen/doxygen#9243]
**Describe the bug**
Doxygen fails to compile (`filesystem/filesystem.hpp`) on Solaris because of missing `d_type` in `dirent` structure.

**Version**
1.9.3

**Comment by albert-github** [comment]
A proposed patch is available as #9243

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
