### ISSUE TITLE
incomplete doxygen help message

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9302]
**Describe the bug**
A common situation in GitHub is that users are requested to run the debug / preprocessor to see what might be going wrong. A common answer by users is: how do I run that?

**Expected behavior**
`doxygen --help` or `man doxygen` contain information about all usage flags.

For example:
`doxygen -d qhp` or `-d preprocessor` --> Runs the debug option of ...

Ideally also the website is updated: https://www.doxygen.nl/manual/doxygen_usage.html

**To Reproduce**
`doxygen --help`
`man doxygen`

**Version**
1.9.4 (b81ef4d433445de75404689f3d8c06853bb39b5f*)

**Comment by ferdymercury** [comment]
Proposed patch: https://github.com/doxygen/doxygen/pull/9304

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
