### ISSUE TITLE
Unable to remove namespaces from being displayed in class file

### ISSUE THREAD

**Issue by Namyalg** [doxygen/doxygen#9303]
**Describe the bug**
I am generating C++ source docs and integrating it with Sphinx.
Using the `.. doxygenfile::`, the cpp file is being linked, however, the namespaces are [displayed ](https://tranquil-dolphin-231c4e.netlify.app/moja.modules.cbm/cbmaggregatorpostgresqlwriter.html)

![image](https://user-images.githubusercontent.com/53875297/166099605-680a5020-1a00-40b2-8d30-dd1435713453.png)

I want to retain the class definition but remove the namespaces.

This is the [Doxyfile](https://github.com/Namyalg/moja.canada/blob/source-docs/Source/docs_sphinx/Doxyfile.in)

**Comment by albert-github** [comment]
- What is the output you are expecting, how does it look like when you look at the HTML doxygen output (to understand the problem and to see whether or not the problem is from doxygen or from sphinx)
- Don't link to external resources, the might not be persistent, attach the files to the issue.
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by Namyalg** [comment]
Thank you for the quick response, I found that it was an issue with the breathe-doxygen directives.
