### ISSUE TITLE
I have a problem with the ALIASES command and ARGUMENTS 

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#9408]
**Describe the bug**
the parameter expanse seems not to work proper

**To Reproduce**

_config file…_

```
ALIASES             += "Ccmd{2}=Mk\1\2" 
ALIASES             += "Icmd{3}=Mk\1\3(\2,…)" 
```

_input file…_

```
\Ccmd{Class,Attribute}
\Icmd{Class,Instance,Attribute}
```

_output (html)_

```
MkClass\2
MkClass\3(Instance,…)
```

_expected output_

```
MkClassAttribute
MkClassAttribute(Instance,…)
```
as you see the \2 and \3 should be **NOT** there. If I put a space between the arguments(\1\2\3) in the ALIASES definition then the expansion works but the "space" is wrong for my documentation.

**Version**
1.8.19 (84084bebe0544650513dbcd75e71a50b2119360d)

**Comment by albert-github** [comment]
With the 1.8.17 version I can see the problem you have (at the moment no 1.8.19 version present)  with the following example:
```
/// \file

/**
\Ccmd{Class,Attribute}

\Icmd{Class,Instance,Attribute}
*/
void fie();
```

in the 1.9.4 version I see as output:

![image](https://user-images.githubusercontent.com/5223533/174436127-df453297-fd14-4257-bf81-2c30e487d0d2.png)

The advise is to update your doxygen version to the current version.

So I think the problem is solved in the mean time.

**Comment by aotto1968** [comment]
thanks, the "update" solved this problem. The reason was that I had my-private-docxgen installed because my "old" linux doesn't NOT support a proper doxygen-version. after upgrade my "old" linux I forget to remove my-private-doxygen link.
