### ISSUE TITLE
Doxygen 1.8.13 [Linux ARM64] producing poor output 

### ISSUE THREAD

**Issue by mnguyenpdftron** [doxygen/doxygen#9427]
Doxygen 1.8.13 produces poor output compared to Doxygen 1.8.5.
I attached the two outputs for comparison. I used `"GENERATE_HTMLHELP=NO"` in both cases. The reason I used Doxygen 1.8.13 because it's for Linux arm64 openjdk:8-jdk-slim-buster.
Any recommendation on how to fix it?
Thanks
[Linux_ARM64_Doxygen1.8.13.zip](https://github.com/doxygen/doxygen/files/8994857/Linux_ARM64_Doxygen1.8.13.zip)
[Linux_x86_64_Doxygen1.8.5.zip](https://github.com/doxygen/doxygen/files/8994858/Linux_x86_64_Doxygen1.8.5.zip)

**Comment by doxygen** [comment]
@mnguyenpdftron without being able to reproduce the problem (since you only provided output and not a way to generated said output), it looks like your project uses a custom HTML header and/or footer which is tailored for 1.8.5, but is no longer compatible with 1.8.13. 

Please check your Doxyfile and clear the `HTML_HEADER`, `HTML_FOOTER`, and `HTML_STYLESHEET` options and then try again. If the output works ok, you can try to upgrade the customization. 
You can use `doxygen -w html header.html footer.html doxygen.sty` to generate the defaults file that match your doxygen version and then customize them to match the desired style.

**Comment by mnguyenpdftron** [comment]
Thank you very much for your prompt reply. It looks like this is the information that I'm looking for.

**Comment by mnguyenpdftron** [comment]
If we'd like to build doxygen 1.8.5 in the arm64 docker (to keep using our current custom header and foot and css), do you think it's feasible?

**Comment by mnguyenpdftron** [comment]
FYI, I was able to build ARM64 executable for 1.8.5.
