### ISSUE TITLE
Upgrade jQuery UI to latest 1.13 release to get rid of security issues.

### ISSUE THREAD

**Issue by LaurenceL** [doxygen/doxygen#9444]
In the latest Doxygen release (1.9.2), the jquery UI version used is 1.12.1. This version contains three security issue:

- CVE-2021-41182 (https://nvd.nist.gov/vuln/detail/CVE-2021-41182)
- CVE-2021-41183 (https://nvd.nist.gov/vuln/detail/CVE-2021-41183)
- CVE-2021-41184 (https://nvd.nist.gov/vuln/detail/CVE-2021-41184)

The fix is include in the 1.13.x branch (latest is 1.13.1)

**Comment by albert-github** [comment]
Doxygen version 1.9.2 is not the latest release, it was released on August 18, 2021.
The latest release is doxygen 1.9.4 released on May 5, 2022.
Of course there is also the latest doxygen master version, to be obtained from this GitHub repository.

That said though: all mentioned versions use jQuery 1.12.1

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
