### ISSUE TITLE
The code block is too ugly, is there a way to beautify it?

### ISSUE THREAD

**Issue by niuzijia** [doxygen/doxygen#9538]
**Describe the bug**
The code block is too ugly, is there a way to beautify it?
This is my code
```
/**
 * @brief get dbc path data
 * 
 * @param file_path DBC file path
 * #### example
 * ```
 * char all_files_absolute_paths[kBLDBC_AttrsLength][kBLDBC_FileAbsolutePathMaxLength];
 * BLDBC_GetFilesPathList(file_path, all_files_absolute_paths);
 * BLDBC_GetDBCData(all_files_absolute_paths);
 * ```
 */
void BLDBC_Init(char file_path[])
{
  char all_files_absolute_paths[kBLDBC_AttrsLength][kBLDBC_FileAbsolutePathMaxLength];
  
  BLDBC_GetFilesPathList(file_path, all_files_absolute_paths);
  BLDBC_GetDBCData(all_files_absolute_paths);
}
```
Here is the result

![image](https://user-images.githubusercontent.com/68538774/186872688-187d9dd0-2d43-4578-b53c-b5eab9356c58.png)

**Expected behavior**
I want the code block to be displayed better, such as the code block of the python documentation
![image](https://user-images.githubusercontent.com/68538774/186872383-2d74b23d-c2ce-4684-a1d8-d78bbabdb19a.png)

**Comment by albert-github** [comment]
- Which version of doxygen are you using? (Please also specify the **full** doxygen version used (`doxygen -v`).)
- Which output format are you using?
   - When looking at the output is HTML (looks like) did you have a look at the possibilities of adding your own CSS file and changing some definitions)?
- is it about the syntax highlighting or about the `>>>` or ....

**Comment by niuzijia** [comment]
> * Which version of doxygen are you using? (Please also specify the **full** doxygen version used (`doxygen -v`).)
> * Which output format are you using?
>   
>   * When looking at the output is HTML (looks like) did you have a look at the possibilities of adding your own CSS file and changing some definitions)?
> * is it about the syntax highlighting or about the `>>>` or ....

My doxygen is 1.9.3.
My output format is HTML and I don't have my own CSS file.
I think the indentation of the default code block and the distance between lines look ugly, how can I make my code block look better (I don't use CSS a lot)

**Comment by albert-github** [comment]
When you look at the HTML code you see here:
```
<h4><a class="anchor" id="autotoc_md0"></a>
example</h4>
<div class="fragment"><div class="line"><span class="keywordtype">char</span> all_files_absolute_paths[kBLDBC_AttrsLength][kBLDBC_FileAbsolutePathMaxLength];</div>
<div class="line">BLDBC_GetFilesPathList(file_path, all_files_absolute_paths);</div>
<div class="line">BLDBC_GetDBCData(all_files_absolute_paths);</div>
```
so you have to change e.g. the settings for `class="line"` and `class="keywordtype"`.
- Search them in the html/doxygen.css, for `ketwordtype` we see:
   ```
   span.keywordtype {
        color: #604020
   }
   ```
- create a new css file e.g. `my.css` and add here the definitions you want for `span.keywordtype` e.g.
   ```
   color: #604020;
   font-size: 26px;
   ```
- add the `my_css` to your settings as `HTML_EXTRA_STYLESHEET = my.css` (see also the documentation https://www.doxygen.nl/manual/customize.html and  https://www.doxygen.nl/manual/customize.html#minor_tweaks_header_css)
- rerun doxygen

Note I used here also the doxygen 1.9.3 version though the current version is 1.9.4 and especially in the current master (1.9.5 (4bdab1ad58f76e29bedbcae3de51ff948dc2b71a)) and thus upcoming releases there will be changes that might have influence on the settings.

All in all the problem is usage.

**Comment by doxygen** [comment]
@niuzijia Beauty is in the eye of the beholder of course, but you can also look at alternative styles made by others such as this one: https://jothepro.github.io/doxygen-awesome-css/

**Comment by niuzijia** [comment]
@doxygen Thanks bro, I am too radical, I am a bit obsessive-compulsive, thank you very much for sharing the theme, I like it very much

**Comment by niuzijia** [comment]
@albert-github Thanks bro, thank you very much for your answer

**Comment by niuzijia** [comment]
@doxygen Brother, I like your software very much. Do you have a donation page? I can't help donating to you.
