### ISSUE TITLE
How to get the calling relationship of a class function

### ISSUE THREAD

**Issue by Mikesaosao** [doxygen/doxygen#9619]
**Describe the bug**
I tried to get the calling relationship of a class function, but I didn't get it. Is it because the configuration is wrong? Or still don't have this feature?

**Expected behavior**
I want to get the function call relationship of the class

C++

**Comment by albert-github** [comment]
The issue is quite vague. What do you mean by "calling relationship of a class function", doxygen has possibilities to show call graphs / reference relations.
See in the doxygen manual a.o. 
Configuration:
- [CALL_GRAPH](https://www.doxygen.nl/manual/config.html#cfg_call_graph)
- [CALLER_GRAPH](https://www.doxygen.nl/manual/config.html#cfg_caller_graph)
- [REFERENCED_BY_RELATION](https://www.doxygen.nl/manual/config.html#cfg_referenced_by_relation)
- [REFERENCES_RELATION](https://www.doxygen.nl/manual/config.html#cfg_references_relation)

Commands:
- [\callgraph](https://www.doxygen.nl/manual/commands.html#cmdcallgraph)
- [\callergraph](https://www.doxygen.nl/manual/commands.html#cmdcallergraph)
- [\showrefby](https://www.doxygen.nl/manual/commands.html#cmdshowrefby)
- [\showrefs](https://www.doxygen.nl/manual/commands.html#cmdshowrefs)


Also:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
unfortunately no further information, setting issue to incomplete.
