### ISSUE TITLE
No docs for namespace members

### ISSUE THREAD

**Issue by silvio3105** [doxygen/doxygen#9655]
Hi,
Doxygen v1.9.5(Windows, GUI) does not create documentation for functions declarations, classes and structs from namespace.
Namespace has a name.
It does not work even when __cplusplus is removed.
Here's screenshots.

![image](https://user-images.githubusercontent.com/104866334/199311666-b66dac10-1448-4cef-90fb-eca5e5cc09f0.png)
![image](https://user-images.githubusercontent.com/104866334/199311719-8dfec9db-a975-486a-aef5-a8f3bc26249f.png)

![image](https://user-images.githubusercontent.com/104866334/199311796-c9a0050b-fc5e-4cf0-b04a-1649bd7bb207.png)

Why it does not work?
Thanks!

**Comment by silvio3105** [comment]
Seems it's because `__cplusplus`
When Doxygen will recognize `__cplusplus`?

**Comment by albert-github** [comment]
The Screenshots (especially the one from the code) are useless as based on this is hard to test it.
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

You can always set `__cplusplus` as a predefined setting, see chapter "Preprocessing" (https://www.doxygen.nl/manual/preprocessing.html) where analogous situations are shown for e.g. `__attribyte__` and `__dllspec`, though they are non-standard and `__cplusplus` is standard C++ (though also the other standard "Predefined macro names" are not recognized by doxygen).
Regarding the `__cplusplus` which value should doxygen use as the standard sys:
> __cplusplus
>    The integer literal 202002L. [Note: It is intended that future versions of this International Standard
will replace the value of this macro with a greater value. —end note]

**Comment by albert-github** [comment]
@silvio3105 
Any possibility of getting: a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
@silvio3105 
Please don't add the file from master as this is not persistent but:
- please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

Furthermore looks also that the source code is from a different file than the original problem but probably both having a similar root type of cause.

Problem here looks like to be caused by `__attribute__` so setting:
```
MACRO_EXPANSION = YES
PREDEFINED = __attribute__(x)=
```
might solve your problem (but due to a missing configuration file it cannot be said with 100% certainty).

See also the mentioned (in https://github.com/doxygen/doxygen/issues/9655#issuecomment-1299885904) chapter about preprocessing
