### ISSUE TITLE
Error dot graph in class diagram

### ISSUE THREAD

**Issue by DamonsJ** [doxygen/doxygen#9717]
I installed doxygen from url: https://www.doxygen.nl/files/Doxygen-1.9.5.dmg in my macbook
I tried to generate class diagram from my test code,  the diagram appears wierd as shown in attachment.

what's happened?

![1](https://user-images.githubusercontent.com/28893028/206632333-f2b1946c-c93a-4149-a011-4a2bd6cb3853.png)

this is the test code:

![image](https://user-images.githubusercontent.com/28893028/206632414-733b90de-45d1-44d9-be60-ca7b96d6bba1.png)
![image](https://user-images.githubusercontent.com/28893028/206632433-ca38aaa6-f009-4ed1-acc9-10cdf1929710.png)

macos: 12.4
install graphviz using : brew install graphviz 

doxygen file is :

[Doxyfile.txt](https://github.com/doxygen/doxygen/files/10192105/Doxyfile.txt)

**Comment by DamonsJ** [comment]
dot version is : 
dot - graphviz version 7.0.4 (20221203.1631)

**Comment by doxygen** [comment]
@DamonsJ Can you please attach a self-contained example (sources + config file in a zip)? Screenshots are hard to work with.

**Comment by DamonsJ** [comment]
sorry, here is the source and config file :

[doxygen-test.zip](https://github.com/doxygen/doxygen/files/10193320/doxygen-test.zip)

**Comment by albert-github** [comment]
Looks like that in the 1.9.4 version it is OK so is it in a recent master version 1.9.6 (b6c9da458bc6abc793db31ed5d39883d048710b6)), in the version 1.9.5 it is indeed not correct. The problem has to do with the shape of the rectangles show, in the 1.9.5 version this is "shape=box" and in the other versions "shape=record",

I think the problem has been fixed but not released.

**Comment by DamonsJ** [comment]
> Looks like that in the 1.9.4 version it is OK so is it in a recent master version 1.9.6 ([b6c9da4](https://github.com/doxygen/doxygen/commit/b6c9da458bc6abc793db31ed5d39883d048710b6))), in the version 1.9.5 it is indeed not correct. The problem has to do with the shape of the rectangles show, in the 1.9.5 version this is "shape=box" and in the other versions "shape=record",
> 
> I think the problem has been fixed but not released.

by the way!
if I change width value in "shape=record,height=0.2,width=0.8", it would't change the width of the diagram's .

It appears like this: 

![image](https://user-images.githubusercontent.com/28893028/206700355-ae3237b1-2ff1-40d7-8a11-6e9bbdff044b.png)

**Comment by albert-github** [comment]
I didn't test it but as far as i know this is outside the scope of doxygen  as the line break is done by the dot program.
I don't know, by head, whether or not `dot` supports columns. This problem is a problem different from the original problem and needs further investigations. Best is to open a new issue for it including an example.

Please don't close this issue, this will be done automatically with a new release.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.6.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
