### ISSUE TITLE
Buggy docs for unnamed union

### ISSUE THREAD

**Issue by silvio3105** [doxygen/doxygen#9751]
There's a bug with unnamed unions.

This is code

![image](https://user-images.githubusercontent.com/104866334/209863560-f7e79de3-83cf-4ba3-a920-ceda987da3ac.png)

This is output

![image](https://user-images.githubusercontent.com/104866334/209863591-70c9c93c-fe60-4408-893d-0b9349c25909.png)

About:

![image](https://user-images.githubusercontent.com/104866334/209863625-d4010377-0612-4c42-af68-1f8cd2b6f17a.png)

Windows 10 Pro x64

**Comment by albert-github** [comment]
- Did you try the current 1.9.6 version of doxygen? What is the result?
- What is the exact problem, what do you mean with "There's a bug with unnamed unions.", please indicate what is wrong in your opinion.
- images are not good to reproduce a problem and also the given image is incomplete:
  - Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
Unfortunately no readable example is provided.
I did a test based on the partial images and was able to reproduce the problem (as far as I can tell) with the example:
```
/// \file
/// test unamed union


/**
 * @brief the union
 * @note the union note
 */
union {
  /**
   * @brief the element
   * @note the element note
   */
  int elem1;
  /**
   * @brief the first struct
   * @note the first struct note
   */
  struct {
    /**
     * @brief the second element
     * @note the second element note
     */
    int elem2;
  } __attribute__((packed,aligned(1))) data2;
  /**
   * @brief the second struct
   * @note the second struct note
   */
  struct {
    /**
     * @brief the third element
     * @note the third element note
     */
    int elem3;
  } __attribute__((packed,aligned(1))) data3;
};
```
with just the settings:
```
QUIET = YES
GENERATE_TREEVIEW = YES
```
this resulted in:
![image](https://github.com/user-attachments/assets/a6503dd0-2ad6-4b67-b87b-ad81263acd43)


but also gave the warnings:
```
.../aa.h:14: warning: documented symbol 'struct @0::@2 @0::__attribute__' was not declared or defined.
.../aa.h:14: warning: documented symbol 'struct @0::@3 @0::__attribute__' was not declared or defined.
```

The problem are the non standard `__attribute__` that are, by design, not handled by doxygen see also the documentation https://www.doxygen.nl/manual/preprocessing.html

When setting:
```
MACRO_EXPANSION        = YES
PREDEFINED             = __attribute__(x)=
```

we get:
![image](https://github.com/user-attachments/assets/1a6fb2f2-b2e3-4c77-9aa9-96e635bcbbfe)


So I think the problem is usage.

Example: [example.tar.gz](https://github.com/user-attachments/files/18027067/example.tar.gz)
