### ISSUE TITLE
false positive warning: argument has multiple @param documentation sections

### ISSUE THREAD

**Issue by igagis** [doxygen/doxygen#9796]
**Describe the bug**
False positive warning is generated:
```
warning: argument 'format' from the argument list of utki::make_string_va_list has multiple @param documentation sections
```

**Expected behavior**
No warnings generated

**To Reproduce**
Have the function declaration in C++ as follows:
```cpp
/**
 * @brief Format string.
 * va_list version of make_string().
 * @param format - printf-like string format.
 * @param args - va_list of string arguments.
 * @return formatted string.
 */
std::string make_string_va_list(const char* format, va_list args);
```

Generate doxygen docs from the file as usual.

**Version**
1.9.1 from Debian Bullseye
1.9.6-1 from `msys2` pacman repo

**Additional context**
Here is the build log from Github actions which shows the problem in Debian Bullseye:
https://github.com/cppfw/utki/actions/runs/3881378828/jobs/6740886946#step:11:48

Here is the build log from `msys2` environment with `doxygen-1.9.6-1-x86_64`:
https://github.com/cppfw/utki/actions/runs/3881378828/jobs/6740888401#step:6:82

**Comment by albert-github** [comment]
With the provided code snippet it is not possible to reproduce the problem, so inn future:
- please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

When looking in the repository we see (in `string.hpp`):
```
namespace utki {

/**
 * @brief Format string.
 * @param format - printf-like string format.
 * @return formatted string.
 */
#if CFG_COMPILER != CFG_COMPILER_MSVC
__attribute__((format(printf, 1, 2)))
#endif
std::string
make_string(const char* format, ...);

/**
 * @brief Format string.
 * va_list version of make_string().
 * @param format - printf-like string format.
 * @param args - va_list of string arguments.
 * @return formatted string.
 */
std::string make_string_va_list(const char* format, va_list args);
```

![image](https://user-images.githubusercontent.com/5223533/212954697-ed7bb917-00f5-48ac-8c17-776987c27293.png)

as `__attribute__` is not a standard feature it confuses doxygen and you have to define it yourself in the `Doxyfile`:
```
PREDEFINED =  __attribute__(x)=
MACRO_EXPANSION = YES
```

this solves the issue.
You can also have a look at the standard way of specifying an attribute (since C++ 11) by means of `[[ ... ]]`.

So I think the problem is usage.

**Comment by igagis** [comment]
Ok, this is a usage problem of course. Thanks for providing a solution.

Although, I think `doxygen` messaging could be improved here, because from the warning message I couldn't even think that it is due to the `__attribute__` from the _previous_ function declaration. I think doxygen could give a warning already when encountering the `__attribute__`, since it is a not known thing for `doxygen` it could complain about that. But in my case it is just silent about that and gives a warning in some other place.
