### ISSUE TITLE
Doxygen >= 1.9.2 not available on Sourceforge

### ISSUE THREAD

**Issue by gmarull** [doxygen/doxygen#9801]
**Describe the bug**

It looks like Doxygen versions >= 1.9.2 have disappeared from Sourceforge download site.

**Expected behavior**

Old versions can be downloaded

**Screenshots**

![image](https://user-images.githubusercontent.com/25011557/213469194-05af3cd4-a96c-4f95-9121-83b8a28caaf0.png)

![image](https://user-images.githubusercontent.com/25011557/213469317-54fea1bc-ac2e-495a-9c77-d63367adf862.png)

**To Reproduce**

Go to https://sourceforge.net/projects/doxygen/files/

**Version**

`>= 1.9.2`

**Stack trace**
N/A

**Additional context**
N/A

**Comment by albert-github** [comment]
They probably disappeared during the conversion to GitHub releases, you can find the releases at https://github.com/doxygen/doxygen/releases and was not intentionally.

- It is strange hat 1.9.2 and up are not present but 1.9.0 and 1.9.1 are  present (I would have expected that if my assumption is correct also these 2 versions would have disappeared).
- the green button about downloading the current version (1.9.6) looks like to point to nowhere.

@doxygen is this intentional behavior?

**Comment by gmarull** [comment]
It has been fixed, so closing.

**Comment by doxygen** [comment]
Not sure what happened, but the problem seems to have been fixed by itself; I did not remove, nor restore, any of the files.
