### ISSUE TITLE
C# enums in same namespace forced into a single file

### ISSUE THREAD

**Issue by morrikan** [doxygen/doxygen#9879]
**Describe the bug**
I have a project with a very large number of enumerations (588, all in the same namespace) that results in a single HTML file that is too large to be useful. I've spent a couple hours looking for an option to separate enumerations into their own HTML files, but have not found anything. The file I just generated is 28,756KB and takes 30+ seconds to load in my browser. It doesn't load at all when using a mobile browser.

**Expected behavior**
In order for Doxygen to be useful for my project, I need a more performant option. I'd suggest an option to split enums out into separate files, but I don't want to tell you how to solve the problem. I'm just saying a 29MB HTML file is unusable.

**Screenshots**
![image](https://user-images.githubusercontent.com/41192301/221279060-17cafbae-052e-42ee-8651-3d4fcc0aecf9.png)

**To Reproduce**
Public repo of a demo project linked below. My project with the 588 enums is private, but I tested this one and it generates both enums into the same HTML file, which is what I need to avoid.
https://gitlab.com/VaultOfKundarak/doxygen-sample

**Version**
Downloaded installer, version 1.9.6. Win 10 Pro x64

**Stack trace**
N/A

**Additional context**

**Comment by albert-github** [comment]
You gave a reference to an external site with the example but this might not be persistent so:
-Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

Large files of course don't load fast an depending on the way the files are accessed (through a server, from a remote disk, from a local disc) the loading can take more time.
I can understand that the large file is a problem, but the problem is that all the enumerations belong in one namespace and should also be shown as belonging to that namespace unless the developer of the here C#) package decides that it should be different. I see here a number of possibilities (not an exhaustive list):
- create different sub-namespaces that logically represent part of the code
- place the enumerations in classes so their scope is limited (not sure whether or not this is possible in C#)
- use for the documentation the grouping facilities (doxygen commands like `\defgroup`, `\addgroup`...., see chapter "Grouping" in the documentation: https://www.doxygen.nl/manual/grouping.html)


I think the problem is usage.

**Comment by morrikan** [comment]
Thanks for the suggestions. Unfortunately, redesigning the code for the sake of documentation isn't something the project owners are going to accept. I'll look into the grouping options. If it doesn't mess up the .net documentation, we can probably use it.
