### ISSUE TITLE
Error on commenting function parameters 

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#9899]
**Describe the bug**
Comments after function parameters (using //!<) with an "ref" at the end results in an error output:

`warning: unable to resolve reference to 'Type@param' for \ref command`

**To Reproduce**
See attached example: [Test21.zip](https://github.com/doxygen/doxygen/files/10912029/Test21.zip)

**Version**
- Version 1.9.6 and 1.9.5 produce this error
- Version 1.9.3 is ok
- other Versions not tested

Regards from Meerbusch
Thomas

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9900

**Comment by thom-sch** [comment]
Hello Albert,
I've just done a quick test - problems seems to be resolved - thanks for quick solution.

Regards from Meerbusch
Thomas

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
