### ISSUE TITLE
template constructors not recognized (Origin: bugzilla #134739)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#990]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-18 14:21:48 +0000, Rueschi wrote:

    Constructors of template classes are not recognized. Instead, they are
    handled as normal member functions.

**Comment by albert-github** [comment]
Due to the lack of an example it is unclear what the conditions are that lead to the issue and where it shows.

We see that a constructor of a templated class is show under "Constructor & Destructor Documentation" in the detailed documentation but in the brief documentation that are shown under "Public Member Functions". 
I think that the later is intended.

I think the issue is incomplete.
