### ISSUE TITLE
File containing regex ($) is ignored

### ISSUE THREAD

**Issue by feanor12** [doxygen/doxygen#9934]
**Describe the bug**
I have a c sharp file(*.cs) containing a string with a regex.
```
var pattern = "^t\\d+$";
```
This file is not shown in the generated html pages, only when I remove the dollar sign from the pattern I see it in the export.

**Expected behavior**
Detect that it is not a comment line with a dollar sign and include the file correctly in the export.

**Version**
Latest windows binary from doxygen.nl 1.9.6

**Comment by albert-github** [comment]
I tried it with the 1.9.6 version and I can reproduce the issue, with the current master (1.9.7 (f482317986aa9e8b6cb062085682d124e1b5630d)) the file is shown:
![image](https://user-images.githubusercontent.com/5223533/226437416-8a644026-498f-4e75-98c5-d400ac7093f6.png)


I think the problem has been fixed but is not released

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
